Repository aio-libs/aiohttp, pull requests merged in 2018-12, with the labels that each got.

#3434 Add 'speedups' extra dependencies group
  setup.py
Labels: enhancement, question

#3430 Rename request fixture for compatibility with a new pytest
  tests/test_client_connection.py
  tests/test_web_exceptions.py
Labels: bug

#3436 Discourage ClientSession.requote_redirect_url changing
  CHANGES/2278.removal
  aiohttp/client.py
  docs/client_reference.rst
  tests/test_client_session.py
Labels: Hacktoberfest, client, easy

#3442 Create a task per request handling.
  CHANGES/3406.feature
  aiohttp/web_protocol.py
  tests/test_web_protocol.py
Labels: enhancement
