Repository aio-libs/aiohttp, pull requests merged in 2019-01, with the labels that each got.

#3481 Remove deprecation warning
  CHANGES/3480.bugfix
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bug

#3500 Ignore done tasks
  CHANGES/3497.bugfix
  aiohttp/helpers.py
Labels: bug

#3503 [3.5] Ignore done tasks (#3500)
  CHANGES/3497.bugfix
  aiohttp/helpers.py
Labels: bug

#3504 Allow run_app(access_log=None)
  CHANGES/3504.bugfix
  aiohttp/web.py
Labels: bug, need backport, server

#3511 Fix aiohttp.ClientTimeout type annotations to accept None for fields
  CHANGES/3511.bugfix
  aiohttp/client.py
Labels: need backport

#3515 Send custom per-request cookies even if session jar is empty
  CHANGES/3515.bugfix
  aiohttp/client.py
Labels: bug

#3533 Permit empty reason strings in ClientResponse.raise_for_status()
  CHANGES/3532.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  tests/test_client_response.py
Labels: bug
