Repository aio-libs/aiohttp, pull requests merged in 2020-11, with the labels that each got.

#5176 Only query host address families over DNS that the local network stack supports
  CHANGES/5156.bugfix
  aiohttp/resolver.py
Labels: backport-3.7, backport-3.8, bot:chronographer:provided

#5191 Add pytest-aiohttp-client library to third party usage list
  CHANGES/5191.doc
  docs/third_party.rst
Labels: bot:chronographer:provided

#4734 Implemented readuntil in StreamResponse
  CHANGES/4054.feature
  aiohttp/streams.py
  docs/streams.rst
  tests/test_streams.py
Labels: backport-3.8, bot:chronographer:provided

#5197 Http exception cookies support
  CHANGES/4277.feature
  aiohttp/helpers.py
  aiohttp/web_exceptions.py
  aiohttp/web_protocol.py
  aiohttp/web_response.py
  docs/web_exceptions.rst
  tests/test_helpers.py
  tests/test_web_functional.py
  tests/test_web_response.py
Labels: backport:skip, bot:chronographer:provided

#5228 Docs: Add aiohttp-pydantic to third party libraries
  CHANGES/5228.doc
  docs/third_party.rst
Labels: backport-3.7, backport-3.8, bot:chronographer:provided

#5235 Fix x86 wheels building
  .github/workflows/ci.yml
  CHANGES/5230.bugfix
Labels: bot:chronographer:provided

#5237 [3.7] Fix x86 wheels building (#5235)
  .github/workflows/ci.yml
  CHANGES/5230.bugfix
Labels: bot:chronographer:provided

#5236 [3.8] Fix x86 wheels building (#5235)
  .github/workflows/ci.yml
  CHANGES/5230.bugfix
Labels: bot:chronographer:provided

#5252 Fix CI badge in docs
  docs/conf.py
Labels: backport-3.7, backport-3.8

#4732 AioHTTPTestCase more async friendly
  CHANGES/4700.feature
  CONTRIBUTORS.txt
  aiohttp/test_utils.py
  requirements/base.txt
  setup.cfg
  setup.py
  tests/test_test_utils.py
Labels: backport-3.8, bot:chronographer:provided

#5257 [3.8] AioHTTPTestCase more async friendly (#4732)
  CHANGES/4700.feature
  CONTRIBUTORS.txt
  aiohttp/test_utils.py
  requirements/base.txt
  setup.cfg
  setup.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided

#5256 Added typing to examples
  examples/background_tasks.py
  examples/cli_app.py
  examples/client_auth.py
  examples/client_json.py
  examples/client_ws.py
  examples/curl.py
  examples/fake_server.py
  examples/lowlevel_srv.py
  examples/server_simple.py
  examples/web_classview.py
  examples/web_cookies.py
  examples/web_rewrite_headers_middleware.py
  examples/web_srv.py
  examples/web_srv_route_deco.py
  examples/web_srv_route_table.py
  examples/web_ws.py
Labels: backport:skip

#5261 No update-precommit on forks
  .github/workflows/update-pre-commit.yml
  CHANGES/5258.bugfix
Labels: bot:chronographer:provided

#4985 Custom error message for Unix connect errors
  CHANGES/4984.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_exceptions.py
  aiohttp/connector.py
  docs/client_reference.rst
Labels: backport-3.8, bot:chronographer:provided

#5264 [3.8] Custom error message for Unix connect errors (#4985)
  CHANGES/4984.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_exceptions.py
  aiohttp/connector.py
  docs/client_reference.rst
Labels: bot:chronographer:provided

#5262 Removed duplicate timeout parameter in ClientSession reference docs.
  CONTRIBUTORS.txt
  docs/client_reference.rst
Labels: backport-3.7, backport-3.8

#5267 Make type hints for http parser stricter
  CHANGES/5267.feature
  aiohttp/client_exceptions.py
  aiohttp/client_proto.py
  aiohttp/http_parser.py
  aiohttp/web_protocol.py
Labels: backport-3.8, bot:chronographer:provided

#5268 [3.8] Make type hints for http parser stricter (#5267).
  CHANGES/5267.feature
  aiohttp/client_exceptions.py
  aiohttp/client_proto.py
  aiohttp/http_parser.py
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided

#5227 Add client Brotli support
  CHANGES/5219.feature
  aiohttp/client_reqrep.py
  docs/glossary.rst
  docs/index.rst
  docs/spelling_wordlist.txt
  requirements/test.txt
  tests/test_client_request.py
  tests/test_web_functional.py
Labels: backport-3.8, bot:chronographer:provided

#5274 Fix CI link and typo in setup.py
  setup.py
Labels: backport-3.8

#5198 Update close status codes ws
  CHANGES/5192.bugfix
  aiohttp/client_ws.py
  aiohttp/http_websocket.py
  aiohttp/web_ws.py
  docs/client_reference.rst
  docs/web_reference.rst
  docs/websocket_utilities.rst
  tests/test_web_websocket_functional.py
Labels: backport-3.8, bot:chronographer:provided

#5279 [3.8] Update close status codes ws (#5198).
  CHANGES/5192.bugfix
  aiohttp/client_ws.py
  aiohttp/http_websocket.py
  aiohttp/web_ws.py
  docs/client_reference.rst
  docs/web_reference.rst
  docs/websocket_utilities.rst
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#5249 Cookie jar delete specific cookie
  CHANGES/4942.feature
  aiohttp/abc.py
  aiohttp/cookiejar.py
  docs/abc.rst
  docs/client_reference.rst
  tests/test_cookiejar.py
Labels: backport-3.8, bot:chronographer:provided

#5280 [3.8] Cookie jar delete specific cookie
  CHANGES/4942.feature
  aiohttp/abc.py
  aiohttp/cookiejar.py
  docs/abc.rst
  docs/client_reference.rst
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#5278 Drop Python 3.6 support
  .github/workflows/ci.yml
  CHANGES/5278.removal
  README.rst
  aiohttp/client.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/helpers.py
  aiohttp/pytest_plugin.py
  aiohttp/resolver.py
  aiohttp/web.py
  aiohttp/web_protocol.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  docs/index.rst
  setup.py
  tests/test_client_functional.py
  tests/test_connector.py
  tests/test_helpers.py
  tests/test_pytest_plugin.py
  tests/test_run_app.py
  tests/test_web_log.py
Labels: bot:chronographer:provided

#5287 Use a distinct type for sentinel
  CHANGES/5287.feature
  aiohttp/client.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/payload.py
  aiohttp/test_utils.py
  aiohttp/web_request.py
Labels: backport-3.8, bot:chronographer:provided

#5284 Replace attrs with dataclasses
  CHANGES/5284.feature
  CHANGES/5284.removal
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/tracing.py
  aiohttp/web_request.py
  aiohttp/web_routedef.py
  aiohttp/web_ws.py
  requirements/base.txt
  setup.py
  tests/test_client_request.py
  tests/test_client_response.py
Labels: backport:skip, bot:chronographer:provided

#5285 Fix race condition on connect when tracing is active (#5259)
  CHANGES/5259.bugfix
  CONTRIBUTORS.txt
  aiohttp/connector.py
Labels: backport-3.8, bot:chronographer:provided

#4031 Fix #4012 encoding of content-disposition parameters
  CHANGES/4012.bugfix
  CONTRIBUTORS.txt
  aiohttp/helpers.py
  aiohttp/payload.py
  tests/test_client_functional.py
  tests/test_formdata.py
  tests/test_helpers.py
  tests/test_multipart.py
  tests/test_web_functional.py
Labels: backport-3.8, bot:chronographer:provided

#5293 Switch to external frozenlist and aiosignal libraries
  .gitignore
  CHANGES/5293.feature
  aiohttp/__init__.py
  aiohttp/_frozenlist.pyx
  aiohttp/frozenlist.py
  aiohttp/frozenlist.pyi
  aiohttp/signals.py
  aiohttp/signals.pyi
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/web_app.py
  requirements/base.txt
  setup.py
  tests/test_frozenlist.py
  tests/test_signals.py
  tests/test_web_response.py
  tests/test_web_websocket.py
Labels: backport-3.8, bot:chronographer:provided

#5294 [3.8] Switch to external frozenlist and aiosignal libraries (#5293).
  .gitignore
  CHANGES/5293.feature
  aiohttp/__init__.py
  aiohttp/_frozenlist.pyx
  aiohttp/frozenlist.py
  aiohttp/frozenlist.pyi
  aiohttp/signals.py
  aiohttp/signals.pyi
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/web_app.py
  requirements/base.txt
  setup.py
  tests/test_frozenlist.py
  tests/test_signals.py
  tests/test_web_exceptions.py
  tests/test_web_response.py
  tests/test_web_websocket.py
Labels: bot:chronographer:provided

#5270 Refactor web error handling
  aiohttp/client_proto.py
  aiohttp/http_parser.py
  aiohttp/streams.py
  aiohttp/web_protocol.py
  tests/test_streams.py
  tests/test_web_protocol.py
Labels: backport-3.8

#5296 Add aiohttp_retry to third-party docs
  docs/third_party.rst
Labels: backport-3.8

#5299 Bump async-timeout version for aiohttp 3.8
  aiohttp/client.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/web_protocol.py
  aiohttp/web_ws.py
  requirements/base.txt
  setup.py
  tests/test_client_ws_functional.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#5233 [3.8] Backport fix for setting cookies
  CHANGES/5233.bugfix
  aiohttp/web_protocol.py
  tests/test_web_exceptions.py
Labels: bot:chronographer:provided
