Repository aio-libs/aiohttp, pull requests merged in 2020-12, with the labels that each got.

#5263 Ensure cleanup contexts are completed when an exception occurs on startup
  CHANGES/4799.bugfix
  aiohttp/web_app.py
  aiohttp/web_runner.py
  tests/test_web_app.py
Labels: backport-3.8, bot:chronographer:provided

#5312 Add more pre-commit hooks
  .pre-commit-config.yaml
Labels: backport-3.8

#5335 Backport brotli
  CHANGES/3803.feature
  aiohttp/http_parser.py
  docs/client_quickstart.rst
  docs/index.rst
  requirements/base.txt
  setup.py
Labels: bot:chronographer:provided

#5329 Add missing slots to `_RequestContextManager` and `_WSRequestContextManager`
  CHANGES/5329.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
Labels: backport-3.8, bot:chronographer:provided

#5326 DOC: Refactor OpenAPI/Swagger aiohttp addons
  CHANGES/5326.doc
  docs/third_party.rst
Labels: backport-3.8, bot:chronographer:provided

#5351 [3.8] Add a changelog fragment for PR #3860
  CHANGES/3853.feature
Labels: bot:chronographer:provided

#5353 [3.8] doc: added OpenAPI/Swagger section, added aio-openapi (#5326).
  CHANGES/5326.doc
  docs/third_party.rst
Labels: bot:chronographer:provided

#5310 Added final declarations to constants (#5275)
  CHANGES/5275.feature
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_ws.py
  aiohttp/formdata.py
  aiohttp/hdrs.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/web.py
  aiohttp/web_fileresponse.py
  aiohttp/web_middlewares.py
  aiohttp/web_request.py
  aiohttp/web_server.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  requirements/cython.txt
Labels: backport-3.8, bot:chronographer:provided

#5354 [3.8] Added final declarations to constants (#5275) (#5310)
  CHANGES/5275.feature
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/formdata.py
  aiohttp/hdrs.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/web.py
  aiohttp/web_fileresponse.py
  aiohttp/web_request.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  requirements/cython.txt
Labels: bot:chronographer:provided
