Repository aio-libs/aiohttp, pull requests merged in 2020-10, with the labels that each got.

#4986 Correct a spelling mistake in quickstart: "canonize"->"canonicalize"
  CHANGES/4986.doc
  docs/client_quickstart.rst
Labels: bot:chronographer:provided

#4912 Fix the tracing module's type hints
  CHANGES/4912.bugfix
  aiohttp/tracing.py
Labels: backport-3.7, bot:chronographer:provided

#4943 Fix example code in client quickstart.
  CHANGES/3376.doc
  docs/client_quickstart.rst
Labels: backport-3.7, bot:chronographer:provided

#4911 chore(docs): fix brackets in quickstart example
  docs/web_quickstart.rst
Labels: backport-3.7

#4844 Docs: Add several aiohttp.web third party libraries
  docs/third_party.rst
Labels: backport-3.7

#4781 Typo
  docs/multipart.rst
Labels: backport-3.7

#4854 Fix missing default value in the doc
  docs/client_reference.rst
Labels: backport-3.7

#4825 Small updates to contributors guide
  CHANGES/4810.doc
  docs/contributing.rst
Labels: backport-3.7, bot:chronographer:provided

#4730 Fix typo in ClientResponse reference
  docs/client_reference.rst
Labels: backport-3.7

#4721 fix incorrect case: Host -> host
  docs/tracing_reference.rst
Labels: backport-3.7

#4769 Fix markup in web_advanced.rst
  docs/web_advanced.rst
Labels: backport-3.7

#4897 Missing exception
  CHANGES/4897.bugfix
  CONTRIBUTORS.txt
  aiohttp/web_exceptions.py
  docs/web_exceptions.rst
Labels: backport-3.7, bot:chronographer:provided

#4881 Added `quote_cookie` option to CookieJar
  CHANGES/2571.feature
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  docs/client_advanced.rst
  tests/test_client_request.py
  tests/test_cookiejar.py
Labels: backport-3.7, bot:chronographer:provided

#4937 Fix for race condition on connections in BaseConnector
  CHANGES/4936.bugfix
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_connector.py
Labels: backport-3.7, bot:chronographer:provided

#4993 Set websocket writer compression to Z_BEST_SPEED
  CHANGES/2856.misc
  aiohttp/http_websocket.py
Labels: backport-3.7, bot:chronographer:provided

#4813 Fix HEAD requests for static content
  CHANGES/4809.bugfix
  CONTRIBUTORS.txt
  aiohttp/web_fileresponse.py
  tests/test_web_urldispatcher.py
Labels: backport-3.7, bot:chronographer:provided

#4736 Fix @reify type hints
  CHANGES/4736.bugfix
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/helpers.py
  aiohttp/http_websocket.py
  aiohttp/web_request.py
  aiohttp/web_urldispatcher.py
Labels: backport-3.7, bot:chronographer:provided

#5051 Fix bug in route name validation
  CHANGES/4691.bugfix
  CONTRIBUTORS.txt
  aiohttp/web_urldispatcher.py
  tests/test_urldispatch.py
Labels: backport-3.7, bot:chronographer:provided

#4573 Fix websocket header for rfc6455
  aiohttp/hdrs.py
Labels: backport-3.7

#4890 Supports for multibytes and multidimensional memoryview
  CHANGES/4890.bugfix
  CONTRIBUTORS.txt
  aiohttp/http_writer.py
  aiohttp/payload.py
  tests/test_http_writer.py
  tests/test_payload.py
Labels: backport-3.7, bot:chronographer:provided

#4778 #4587 Always check transport is not closing before reuse
  CHANGES/4587.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_proto.py
  aiohttp/connector.py
  tests/test_connector.py
Labels: backport-3.7, bot:chronographer:provided

#4873 Fix OverflowError with 32-bit (signed) time_t
  CHANGES/4515.bugfix
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: backport-3.7, bot:chronographer:provided

#4894 TCPSite to bind on all interfaces when None is passed in
  CHANGES/4894.feature
  aiohttp/web_runner.py
  docs/web_reference.rst
  tests/test_run_app.py
  tests/test_web_runner.py
Labels: backport-3.7, bot:chronographer:provided

#4938 Fixed application/rdap+json response character set detection
  CHANGES/4938.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
Labels: backport-3.7, bot:chronographer:provided

#4846 [RESEND] Fix HttpPayloadParser dealing with chunked response (#4630)
  CHANGES/4630.bugfix
  CONTRIBUTORS.txt
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#4556 🔗 Fix connecting to link-local IPv6 addresses
  CHANGES/4554.bugfix
  aiohttp/resolver.py
  tests/test_connector.py
Labels: backport-3.7, bot:chronographer:provided

#5012 Fix closing connection after HEAD request
  CHANGES/5012.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_proto.py
  tests/test_client_functional.py
Labels: backport-3.7, bot:chronographer:provided

#4674 Added method and url info to tracking signals
  CHANGES/4674.feature
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  aiohttp/tracing.py
  docs/tracing_reference.rst
  tests/test_client_response.py
  tests/test_tracing.py
Labels: backport-3.7, bot:chronographer:provided

#5064 Header prep before hook
  CHANGES/1958.feature
  CONTRIBUTORS.txt
  aiohttp/web_response.py
  docs/web_advanced.rst
  docs/web_reference.rst
  tests/test_web_response.py
Labels: backport-3.7, bot:chronographer:provided

#5066 Drop Python 3.5-only code branches
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/http_exceptions.py
  aiohttp/payload.py
  aiohttp/typedefs.py
  aiohttp/web.py
  aiohttp/worker.py
  tests/test_client_session.py
  tests/test_helpers.py
  tests/test_http_exceptions.py
  tests/test_web_app.py
Labels: backport-3.7

#5065 Customize the input buffer size
  CHANGES/4453.feature
  aiohttp/_http_parser.pyx
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/http_parser.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/web_protocol.py
  aiohttp/web_ws.py
  docs/client_reference.rst
  docs/spelling_wordlist.txt
  docs/web_reference.rst
  tests/test_client_functional.py
  tests/test_http_parser.py
  tests/test_multipart.py
  tests/test_streams.py
  tests/test_web_functional.py
  tests/test_web_request.py
Labels: backport-3.7, bot:chronographer:provided

#4562 Fix a problem with connection waiters that are never awaited
  CHANGES/4562.bugfix
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_connector.py
Labels: backport-3.7, bot:chronographer:provided

#4956 Fix keepalive connections not being closed in time
  CHANGES/3296.bugfix
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#4771 [3.7] Don't cancel web handler on disconnection (#4080)
  CHANGES/4080.feature
  aiohttp/http_websocket.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_ws.py
  docs/web_advanced.rst
  tests/test_client_ws.py
  tests/test_web_protocol.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided

#4848 Fix #4798: no response on invalid request methods
  CHANGES/4798.bugfix
  CONTRIBUTORS.txt
  aiohttp/_http_parser.pyx
  tests/test_http_parser.py
  tests/test_web_functional.py
Labels: backport-3.7, bot:chronographer:provided

#5072 Fix multipart file uploads without content type
  CHANGES/4089.bugfix
  CONTRIBUTORS.txt
  aiohttp/web_request.py
  tests/test_web_request.py
Labels: backport-3.7, bot:chronographer:provided

#4815 Fix exception causes in client.py
  aiohttp/client.py
Labels: backport-3.7

#5077 Relax multidict
  CHANGES/5075.feature
  setup.py
Labels: backport-3.7, bot:chronographer:provided

#5078 Better typing
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/tracing.py
  aiohttp/web_app.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  aiohttp/worker.py
  setup.cfg
Labels: backport-3.7

#5084 Add aiohttp-sse-client library to third party usage list
  CHANGES/5084.doc
  docs/third_party.rst
Labels: backport-3.7, bot:chronographer:provided

#5086 Fix type hint on BaseRunner.addresses
  CHANGES/5086.bugfix
  aiohttp/web_runner.py
Labels: backport-3.7, bot:chronographer:provided

#5091 Don't ceil small timeouts
  CHANGES/4850.feature
  aiohttp/helpers.py
  docs/client_quickstart.rst
  docs/spelling_wordlist.txt
  requirements/ci-wheel.txt
  tests/test_client_functional.py
  tests/test_client_ws_functional.py
  tests/test_helpers.py
  tests/test_web_protocol.py
  tests/test_web_websocket_functional.py
Labels: backport-3.7, bot:chronographer:provided

#4415 Fix a warning about unfinished task in web_protocol.py
  CHANGES/4408.bugfix
  aiohttp/web_protocol.py
  tests/test_web_protocol.py
Labels: backport-3.7, bot:chronographer:provided

#5098 Reduce sleep time on Windows
  CHANGES/5098.bugfix
  aiohttp/web.py
Labels: backport-3.7, bot:chronographer:provided

#5104 Fix a regression about printing absolute time instead of request elapsed time
  aiohttp/web_protocol.py
Labels: backport-3.7

#5108 Update CONTRIBUTION instructions
  docs/contributing.rst
  docs/spelling_wordlist.txt
Labels: backport-3.7

#5111 Import `Protocol` from typing_extensions
  CHANGES/5111.bugfix
  aiohttp/helpers.py
Labels: backport-3.7, bot:chronographer:provided

#5113 [3.7] Import `Protocol` from typing_extensions (#5111)
  CHANGES/5111.bugfix
  aiohttp/helpers.py
Labels: bot:chronographer:provided

#5114 fix run_app typing (#4957)
  CHANGES/4957.bugfix
  aiohttp/web.py
  tests/test_run_app.py
Labels: backport-3.7, bot:chronographer:provided

#5115 Annotate all attrs members
  CHANGES/5115.bugfix
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  aiohttp/helpers.py
  aiohttp/tracing.py
  aiohttp/web_request.py
  aiohttp/web_routedef.py
  aiohttp/web_ws.py
Labels: backport-3.7, bot:chronographer:provided

#5117 Fix flaky test_when_timeout_smaller_second
  CHANGES/5116.bugfix
  tests/test_helpers.py
Labels: backport-3.7, bot:chronographer:provided

#5119 No Content-Length header for 1xx 204
  CHANGES/4901.bugfix
  aiohttp/web_response.py
  tests/test_web_functional.py
Labels: backport-3.7, bot:chronographer:provided

#5118 Return hostnames from ThreadedResolver
  CHANGES/5110.bugfix
  aiohttp/resolver.py
  tests/test_connector.py
  tests/test_resolver.py
Labels: backport-3.7, bot:chronographer:provided

#5123 Always require typing_extensions library
  CHANGES/5107.bugfix
  setup.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#5125 Ensure zero byte files can be sent
  CHANGES/5124.bugfix
  aiohttp/web_fileresponse.py
  tests/data.zero_bytes
  tests/test_web_sendfile_functional.py
Labels: backport-3.7, bot:chronographer:provided

#5130 Fix a bug in web.run_app() about Python version checking on Windows
  CHANGES/5127.bugfix
  aiohttp/web.py
Labels: backport-3.7, bot:chronographer:provided

#5132 Fix documentation for update_cookies/filter_cookies
  docs/client_reference.rst
Labels: backport-3.8

#5134 Apply awesome re-assert library for regex assertions in tests
  aiohttp/web_fileresponse.py
  requirements/ci-wheel.txt
  tests/test_client_session.py
  tests/test_signals.py
  tests/test_streams.py
  tests/test_urldispatch.py
  tests/test_web_functional.py
  tests/test_web_response.py
Labels: backport-3.8

#5122 Trace headers
  CHANGES/5105.feature
  aiohttp/client_reqrep.py
  aiohttp/http_writer.py
  aiohttp/tracing.py
  docs/tracing_reference.rst
  tests/test_client_session.py
  tests/test_tracing.py
Labels: bot:chronographer:provided

#5136 Setup pre-commit hooks configuration
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  docs/contributing.rst
  requirements/lint.txt
Labels: backport-3.7, backport-3.8

#5139 Convert HttpVersion from collections.namedtuple to typing.NamedTuple
  aiohttp/http_writer.py
Labels: backport-3.8

#5140 Execute 'pre-commit run --all-files' on 'make fmt'
  Makefile
Labels: backport-3.7, backport-3.8

#5135 StreamResponse use Transfer-Encoding: chunked for 204 responses
  CHANGES/5106.bugfix
  aiohttp/web_response.py
  tests/test_web_functional.py
Labels: backport-3.8, bot:chronographer:provided

#5144 [3.8] StreamResponse use Transfer-Encoding: chunked for 204 responses (#5135)
  CHANGES/5106.bugfix
  aiohttp/web_response.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#5157 Fixed static files handling for loops without .sendfile()
  CHANGES/5149.bugfix
  CONTRIBUTORS.txt
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile_functional.py
Labels: backport-3.7, backport-3.8

#5160 Strip unnecessary noqa
  .pre-commit-config.yaml
  aiohttp/__init__.py
  aiohttp/abc.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/formdata.py
  aiohttp/helpers.py
  aiohttp/http.py
  aiohttp/http_parser.py
  aiohttp/http_writer.py
  aiohttp/locks.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/pytest_plugin.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/typedefs.py
  aiohttp/web_app.py
  aiohttp/web_fileresponse.py
  aiohttp/web_middlewares.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  aiohttp/worker.py
  tests/test_run_app.py
  tests/test_streams.py
Labels: backport-3.7, backport-3.8

#5095 Add keepalive_timeout parameter to web.run_app
  CHANGES/5094.feature
  CONTRIBUTORS.txt
  aiohttp/web.py
  docs/web_reference.rst
  tests/test_run_app.py
Labels: backport-3.8, bot:chronographer:provided

#5164 Tune C source generation
  .gitignore
  Makefile
  aiohttp/_find_header.c
  aiohttp/_headers.pxi
  aiohttp/client.py
  aiohttp/hdrs.py
  requirements/base.txt
  requirements/cython.txt
  requirements/multidict.txt
  tests/test_client_ws.py
  tools/gen.py
Labels: backport-3.7, backport-3.8

#5165 Change __aiter__ return type to AsyncIterator
  CHANGES/5163.bugfix
  CONTRIBUTORS.txt
  aiohttp/multipart.py
Labels: backport-3.7, backport-3.8, bot:chronographer:provided

#5166 Use md5 checksums instead of file timestamps
  .gitignore
  Makefile
Labels: backport-3.7, backport-3.8

#5178 Tune pre-commit config file
  .pre-commit-config.yaml
  Makefile
  examples/cli_app.py
  examples/client_auth.py
  examples/client_json.py
  examples/fake_server.py
  examples/static_files.py
Labels: backport-3.7, backport-3.8

#5183 Better checksum calculation
  .github/workflows/ci.yml
  .gitignore
  Makefile
  requirements/lint.txt
  tools/check_sum.py
Labels: backport-3.7, backport-3.8

#5184 Return Request.
  aiohttp/test_utils.py
Labels: backport-3.7, backport-3.8
