Repository aio-libs/aiohttp, pull requests merged in 2021-12, with the labels that each got.

#6345 Use str.partition() instead of .split() with a limit and a check
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CHANGES/6345.misc
  CONTRIBUTORS.txt
  aiohttp/helpers.py
Labels: bot:chronographer:provided

#6363 Fix example in `client_quickstart.rst`
  docs/client_quickstart.rst
Labels: documentation, bot:chronographer:skip, backport-3.8, backport-3.9

#6369 Fix setting branch protection failure in GHA
  .github/workflows/ci.yml
  CHANGES/6369.misc
Labels: bug, infra, meta, bot:chronographer:provided, backport-3.8, backport-3.9

#6375 Add a test for circular imports in the project
  tests/test_circular_imports.py
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6374 Revert assert
  .github/workflows/ci.yml
  aiohttp/client.py
  aiohttp/connector.py
  setup.cfg
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:skip

#6373 Patchback/backports/3.9/bd008ca646df25e043738aa85acca0d30ddcf128/pr 5898
  CHANGES/5898.feature
  aiohttp/typedefs.py
  aiohttp/web_app.py
  aiohttp/web_middlewares.py
Labels: bot:chronographer:provided

#6379 Add changes for dropping Python 3.6 support in aiohttp 3.9
  CHANGES/6378.removal
Labels: bot:chronographer:provided

#6344 [PR #6340/f6334e2 backport][3.9] Add an argument to override request body size (#6340)
  CHANGES/5704.feature
  aiohttp/web_request.py
  docs/web_advanced.rst
  docs/web_reference.rst
  tests/test_web_request.py
Labels: bot:chronographer:provided

#6380 Bump proxy.py to v2.4.0 pre-release
  requirements/constraints.txt
  requirements/test.txt
  tests/test_proxy_functional.py
Labels: enhancement, client, infra, dependencies, bot:chronographer:skip, backport-3.8, python, backport-3.9

#6316 Misc/app configure timeout ceil threshold
  CHANGES/6316.misc
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/web_protocol.py
  aiohttp/web_server.py
  aiohttp/web_ws.py
  docs/client_quickstart.rst
  docs/web_advanced.rst
  tests/test_helpers.py
  tests/test_web_runner.py
Labels: bot:chronographer:provided, backport-3.9

#6396 Fix Python 3.11 alpha incompatibilities
  CHANGES/6396.bugfix
  requirements/constraints.txt
  requirements/cython.txt
Labels: bot:chronographer:provided

#6397 [3.9] Misc/app configure timeout ceil threshold (#6316)
  CHANGES/6316.misc
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/web_protocol.py
  aiohttp/web_server.py
  aiohttp/web_ws.py
  docs/client_quickstart.rst
  docs/web_advanced.rst
  tests/test_helpers.py
  tests/test_web_runner.py
Labels: bot:chronographer:provided

#6400 Do not install C sources in binary distributions
  CHANGES/6399.misc
  setup.cfg
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6401 Edited the web.run_app declaration.
  CHANGES/6401.doc
  CONTRIBUTORS.txt
  aiohttp/web.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6409 Support absolute-form and authority-form URLs by web server
  CHANGES/6227.bugfix
  aiohttp/_http_parser.pyx
  aiohttp/http_parser.py
  aiohttp/web_request.py
  tests/test_http_parser.py
  tests/test_proxy_functional.py
  tests/test_web_request.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6410 Convert type comments to type annotations
  aiohttp/abc.py
  aiohttp/base_protocol.py
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/formdata.py
  aiohttp/helpers.py
  aiohttp/http.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  aiohttp/locks.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/web.py
  aiohttp/web_app.py
  aiohttp/web_exceptions.py
  aiohttp/web_log.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  aiohttp/worker.py
  setup.py
Labels: bot:chronographer:skip

#6411 Convert type comments to type annotations
  aiohttp/abc.py
  aiohttp/base_protocol.py
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/formdata.py
  aiohttp/helpers.py
  aiohttp/http.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  aiohttp/locks.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/web.py
  aiohttp/web_app.py
  aiohttp/web_exceptions.py
  aiohttp/web_log.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  aiohttp/worker.py
  setup.py
Labels: bot:chronographer:skip

#6412 Convert type comments to type annotations
  aiohttp/abc.py
  aiohttp/base_protocol.py
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/formdata.py
  aiohttp/helpers.py
  aiohttp/http.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  aiohttp/locks.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/web.py
  aiohttp/web_app.py
  aiohttp/web_exceptions.py
  aiohttp/web_log.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  aiohttp/worker.py
  setup.py
Labels: bot:chronographer:skip

#6415 Typing Errors Fixed
  CHANGES.rst
Labels: bot:chronographer:skip

#6452 Upgrade mypy to 0.930
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/test_utils.py
  aiohttp/web.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  requirements/constraints.txt
  requirements/lint.txt
  requirements/test.txt
  requirements/typing-extensions.txt
  tests/test_circular_imports.py
Labels: bot:chronographer:skip, backport-3.9

#6454 [3.9] Upgrade mypy to 0.930
  aiohttp/client.py
  aiohttp/helpers.py
  aiohttp/payload_streamer.py
  aiohttp/web.py
  aiohttp/web_urldispatcher.py
  requirements/constraints.txt
  requirements/lint.txt
  requirements/test.txt
  requirements/typing-extensions.txt
  tests/test_circular_imports.py
Labels: bot:chronographer:skip

#6451 Regression test for handling unsupported Upgrade requests (issue #6446)
  tests/test_web_server.py
Labels: bot:chronographer:skip, backport-3.9

#6460 Update return type of Resource.__iter__()
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.9

#6464 Fix typos
  CHANGES/3994.misc
  CHANGES/5494.misc
  CONTRIBUTING.rst
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/multipart.py
  docs/faq.rst
  tests/test_http_parser.py
  tests/test_streams.py
  tests/test_web_response.py
  tools/cleanup_changes.py
Labels: documentation, bot:chronographer:skip, backport-3.8, backport-3.9

#6456 [PR #6451/a60e8a58 forwardport][3.9] Regression test for handling unsupported Upgrade requests (issue #6446)
  tests/test_web_server.py
Labels: bot:chronographer:skip
