Repository aio-libs/aiohttp, pull requests merged in 2021-11, with the labels that each got.

#6189 Fix setup.cfg not to install "examples" top-level package
  CHANGES/6189.bugfix
  setup.cfg
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6193 Bump async-timeout to >=4.0
  CHANGES/6193.feature
  setup.cfg
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6201 Remove Signal from __all__, replace aiohttp.Signal with aiosignal.Signal in docs
  CHANGES/6201.bugfix
  aiohttp/__init__.py
  docs/conf.py
  docs/signals.rst
  docs/utilities.rst
  docs/web_reference.rst
  tests/test___all__.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6205 Set the minimum required `setuptools` to v46.4.0
  CHANGES/6205.misc
  pyproject.toml
Labels: infra, meta, bot:chronographer:provided, backport-3.8, backport-3.9

#6238 Requirements cleanup
  .github/workflows/ci.yml
  .github/workflows/post-dependabot.yml
  .pre-commit-config.yaml
  Makefile
  requirements/constraints.in
  requirements/constraints.txt
  requirements/cython.in
  requirements/cython.txt
  requirements/dev.in
  requirements/dev.txt
  requirements/doc-spelling.in
  requirements/doc-spelling.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6180 Fix too lax application/json prefix-only matching
  CHANGES/6180.bugfix
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/web_request.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#6240 update quick start demo codes
  CHANGES/6240.doc
  docs/client_quickstart.rst
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.8, backport-3.9

#6255 Changed `dev` to `development` in CONTRIBUTING.rst
  CONTRIBUTING.rst
  docs/contributing.rst
Labels: enhancement, documentation, bot:chronographer:skip, backport-3.8, backport-3.9

#6261 Revert bump of typing-extensions.
  requirements/typing-extensions.txt
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6251 Drop types-chardet mypy dependency
  requirements/constraints.txt
  requirements/lint.txt
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6276 Add flake8-docstrings, fix bunch of flagged issues
  .pre-commit-config.yaml
  CHANGES/6276.doc
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/connector.py
  aiohttp/formdata.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/locks.py
  aiohttp/multipart.py
  aiohttp/pytest_plugin.py
  aiohttp/resolver.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/web_middlewares.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_urldispatcher.py
  docs/spelling_wordlist.txt
  examples/web_classview.py
  examples/web_cookies.py
  examples/web_rewrite_headers_middleware.py
  examples/web_srv.py
  examples/web_srv_route_deco.py
  examples/web_srv_route_table.py
  examples/web_ws.py
  setup.cfg
  tests/test___all__.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6278 Improve documentation for running complex applications
  CHANGES/6278.doc
  docs/web_advanced.rst
  docs/web_reference.rst
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6274 Clarify tiny timeouts behavior and how it can affect performance
  CHANGES/6274.doc.rst
  docs/client_reference.rst
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6305 Made chunked encoding HTTP header check stricter
  CHANGES/6305.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6309 Restored ability to connect IPv6-only host.
  CHANGES/6195.bugfix
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6313 docs: Fix statement about `setUpAsync()` and `tearDownAsync()`
  docs/testing.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6328 Drop dead code, float timeout support was removed
  aiohttp/client.py
Labels: bot:chronographer:skip

#6329 Replace sentinel definition from object() with enum
  CHANGES/6329.misc
  aiohttp/client.py
  aiohttp/helpers.py
  aiohttp/web_request.py
Labels: bot:chronographer:provided, backport-3.9

#6163 Add clarification to configuring app
  CHANGES/4137.doc
  docs/web_advanced.rst
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6340 Add an argument to override request body size
  CHANGES/5704.feature
  aiohttp/web_request.py
  docs/web_advanced.rst
  docs/web_reference.rst
  tests/test_web_request.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9
