Repository aio-libs/aiohttp, pull requests merged in 2021-05, with the labels that each got.

#5706 Fix broken references in `docs/web_quickstart.rst`
  docs/web_quickstart.rst
Labels: backport-3.8

#5678 Use an SVG logo across the docs
  README.rst
  docs/_static/aiohttp-icon-128x128.png
  docs/_static/css/logo-adjustments.css
  docs/conf.py
Labels: backport-3.8

#5610 Fix broken references in `docs/abc.rst`
  docs/abc.rst
  docs/conf.py
Labels: backport-3.8

#5713 Fix broken references in `streams.rst`
  docs/streams.rst
Labels: backport-3.8

#5673 Add regression test for HTTPUnathorized per #5657
  CHANGES/5657.misc
  tests/test_web_exceptions.py
Labels: bot:chronographer:provided

#5637 Update client/server implementation in the autobahn tests
  CHANGES/5606.bugfix
  CONTRIBUTORS.txt
  tests/autobahn/client.py
  tests/autobahn/server.py
Labels: bot:chronographer:provided

#5720 Fix broken references in `websocket_utilities.rst`
  docs/websocket_utilities.rst
Labels: backport-3.8

#5721 Hotfix references in docs
  docs/abc.rst
  docs/conf.py
Labels: backport-3.8

#5729 Adjust type of iscoroutine() argument
  aiohttp/helpers.py
Labels: backport-3.8

#5620 Fix broken references in `docs/client_reference.rst`
  docs/client_reference.rst
  docs/conf.py
Labels: backport-3.8, bot:chronographer:skip, documentation

#5725 Update docs on request cookies
  CHANGES/5725.doc
  docs/web_reference.rst
Labels: backport-3.8, bot:chronographer:provided

#5736 Fix broken references in `multipart_reference.rst`
  docs/multipart_reference.rst
Labels: backport-3.8

#5619 Fix broken references in `docs/testing.rst`
  docs/conf.py
  docs/testing.rst
Labels: backport-3.8

#5744 Fix broken reference in `docs/web-lowlevel.rst`
  docs/web_lowlevel.rst
Labels: backport-3.8

#5749 Fix broken references in `docs/logging.rst`
  docs/conf.py
Labels: backport-3.8
