Repository aio-libs/aiohttp, pull requests merged in 2021-03, with the labels that each got.

#5516 Remove @unittest_run_loop
  CHANGES/5516.misc
  aiohttp/test_utils.py
  docs/testing.rst
  tests/test_loop.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided

#5515 Deprecate @unittest_run_loop
  CHANGES/5515.misc
  aiohttp/test_utils.py
  docs/testing.rst
  tests/test_loop.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided

#5517 Fix the link to `MultiDict` in `client_quickstart.rst`
  docs/client_quickstart.rst
Labels: backport-3.8, documentation, enhancement

#5529 Fix sock_connect timeout being applied when 0.
  CHANGES/5527.bugfix
  aiohttp/helpers.py
  tests/test_client_session.py
Labels: bot:chronographer:provided

#5533 Add test for 0 timeout
  CHANGES/5533.misc
  aiohttp/helpers.py
  tests/test_client_session.py
Labels: bot:chronographer:provided

#5508 Complete pip-tools setup (backport #5486)
  .pre-commit-config.yaml
  CHANGES/5486.misc
  Makefile
  requirements/base.txt
  requirements/cython.in
  requirements/cython.txt
  requirements/dev.txt
  requirements/doc-spelling.in
  requirements/doc-spelling.txt
  requirements/lint.in
  requirements/lint.txt
Labels: bot:chronographer:provided

#5464 Backport #5457
  .mypy.ini
  CHANGES/5457.misc
  Makefile
  aiohttp/connector.py
  aiohttp/resolver.py
  aiohttp/worker.py
  examples/__init__.py
  examples/background_tasks.py
  examples/client_json.py
  examples/client_ws.py
  examples/fake_server.py
  examples/web_classview.py
  examples/web_cookies.py
Labels: bot:chronographer:provided

#5374 Fix imports of typing_extensions
  CHANGES/5107.bugfix
  aiohttp/client.py
  aiohttp/hdrs.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/locks.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/tracing.py
  aiohttp/typedefs.py
  aiohttp/web_fileresponse.py
  aiohttp/web_request.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  setup.py
Labels: bot:chronographer:provided

#4445 Add support for the `no_proxy` env var mechanism in the HTTP client
  CHANGES/4431.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: backport-3.8, bot:chronographer:provided

#5562 [backport][3.8][PR#5298] ETag backport
  CHANGES/4594.feature
  aiohttp/__init__.py
  aiohttp/helpers.py
  aiohttp/web_fileresponse.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  docs/client_reference.rst
  docs/spelling_wordlist.txt
  docs/web_reference.rst
  tests/test_web_request.py
  tests/test_web_response.py
  tests/test_web_sendfile.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided
