Repository aio-libs/aiohttp, pull requests merged in 2021-06, with the labels that each got.

#5743 Fix broken references in `docs/new_router.rst`
  docs/new_router.rst
Labels: backport-3.8

#5750 Fix broken references in `docs/multipart.rst`
  docs/conf.py
  docs/multipart.rst
Labels: backport-3.8

#5751 Fix broken reference in `docs/web_exceptions.rst`
  docs/web_exceptions.rst
Labels: backport-3.8

#5741 Fix broken references in `docs/whats_new_1_1.rst`
  docs/whats_new_1_1.rst
Labels: backport-3.8

#5714 Fix broken references in `docs/web_advanced.rst`
  docs/conf.py
  docs/web_advanced.rst
Labels: backport-3.8

#5711 Fix broken references in `docs/web_reference.rst`
  docs/conf.py
  docs/web_reference.rst
Labels: backport-3.8

#5742 Fix broken reference in `docs/faq.rst`
  docs/conf.py
Labels: backport-3.8

#5774 Enable Nitpicky mode in Sphinx docs
  docs/conf.py
Labels: backport-3.8

#5776 Show all Sphinx warnings together
  docs/Makefile
Labels: backport-3.8, documentation, enhancement, infra

#5762 [PR #5637/6fb3efc backport][3.8] Update client/server implementation in the autobahn tests
  CHANGES/5606.bugfix
  CONTRIBUTORS.txt
  tests/autobahn/client.py
  tests/autobahn/server.py
Labels: bot:chronographer:provided

#5778 Ensure all sphinx-build invocations are strict
  Makefile
Labels: backport-3.8, documentation, enhancement

#5781 Use a newer `issue_cert()` method of `trustme`
  tests/conftest.py
Labels: backport-3.8, infra

#5731 Fix a test for HTTPUnauthorized with a Unicode string body argument
  CHANGES/5657.bugfix
  tests/test_web_exceptions.py
Labels: bot:chronographer:provided

#5679 Update the Autobahn test suite to v0.8.2
  CHANGES/4247.misc
  CONTRIBUTORS.txt
  tests/autobahn/.gitignore
  tests/autobahn/Dockerfile.aiohttp
  tests/autobahn/client/client.py
  tests/autobahn/client/docker-compose.yml
  tests/autobahn/client/fuzzingserver.json
  tests/autobahn/docker-compose.yml
  tests/autobahn/fuzzingclient.json
  tests/autobahn/run-tests.sh
  tests/autobahn/server/docker-compose.yml
  tests/autobahn/server/fuzzingclient.json
  tests/autobahn/server/server.py
Labels: backport-3.8, bot:chronographer:provided

#5572 Use a new loop in run_app()
  CHANGES/5572.feature
  aiohttp/web.py
  tests/test_run_app.py
  tests/test_web_runner.py
Labels: backport-3.8, bot:chronographer:provided

#5820 Backport #5572: Use new loop for web.run_app().
  CHANGES/5572.feature
  aiohttp/web.py
  tests/test_run_app.py
  tests/test_web_runner.py
Labels: bot:chronographer:provided

#5829 Disallow untyped defs in tests
  .mypy.ini
  CHANGES/5829.misc
Labels: bot:chronographer:provided

#5835 Fix(doc): ClientResponse.release should be a instance method, not a c…
  CHANGES/5836.doc
  docs/client_reference.rst
Labels: bot:chronographer:provided
