Repository aio-libs/aiohttp, pull requests merged in 2021-09, with the labels that each got.

#5452 Add validation of HTTP status line, header keys and values
  CHANGES/4818.feature
  CONTRIBUTORS.txt
  aiohttp/_http_writer.pyx
  aiohttp/http_writer.py
  tests/test_http_writer.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.8

#6001 Quick fix: Bump funcparserlib
  requirements/doc.txt
Labels: bot:chronographer:skip

#5870 Simplify generator expression
  CHANGES/5870.misc
  CONTRIBUTORS.txt
  tools/gen.py
Labels: bot:chronographer:provided

#6004 Quick fix: Ignore python internal deprecation warning
  setup.cfg
Labels: bot:chronographer:skip

#6024 Fix double "abstract" in docs for access logger
  docs/abc.rst
Labels: bot:chronographer:skip, backport-3.8
