Repository aio-libs/aiohttp, pull requests merged in 2021-02, with the labels that each got.

#5407 [3.8] Eliminate side-effects from the `ClientResponse.ok` property
  CHANGES/5403.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  tests/test_client_response.py
Labels: bot:chronographer:provided

#5457 Mypy coverage
  .mypy.ini
  CHANGES/5457.misc
  Makefile
  aiohttp/resolver.py
  aiohttp/worker.py
  examples/background_tasks.py
  examples/client_json.py
  examples/fake_server.py
  examples/web_cookies.py
Labels: backport-3.8, bot:chronographer:provided

#5298 Implement ETag support
  CHANGES/4594.feature
  aiohttp/__init__.py
  aiohttp/helpers.py
  aiohttp/web_fileresponse.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  docs/client_reference.rst
  docs/spelling_wordlist.txt
  docs/web_reference.rst
  tests/test_web_request.py
  tests/test_web_response.py
  tests/test_web_sendfile.py
  tests/test_web_sendfile_functional.py
Labels: backport-3.8, bot:chronographer:provided

#5494 Release all forgotten resources in tests
  CHANGES/5494.bugfix
  CHANGES/5494.misc
  aiohttp/web_request.py
  setup.cfg
  tests/test_client_request.py
  tests/test_client_response.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_proxy.py
  tests/test_run_app.py
  tests/test_web_functional.py
  tests/test_web_request.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, bug, infra

#5466 Fix annotations
  CHANGES/5466.bugfix
  aiohttp/http_parser.py
  aiohttp/web_request.py
Labels: bot:chronographer:provided

#5498 Fix how pure-Python HTTP parser interprets `//`
  CHANGES/5498.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: backport-3.8, bot:chronographer:provided, reproducer: present, server

#5499 [backport][3.7][PR#5498] Fix how pure-Python HTTP parser interprets `//`
  CHANGES/5498.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#5500 [backport][3.8][PR#5498] Fix how pure-Python HTTP parser interprets `//`
  CHANGES/5498.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#5486 Complete pip-tools setup
  .pre-commit-config.yaml
  CHANGES/5470.bugfix
  Makefile
  requirements/cython.in
  requirements/cython.txt
  requirements/dev.txt
  requirements/doc-spelling.in
  requirements/doc-spelling.txt
  requirements/lint.in
  requirements/lint.txt
Labels: backport-3.8, bot:chronographer:provided
