Repository aio-libs/aiohttp, pull requests merged in 2021-04, with the labels that each got.

#5588 Fix `StreamReader` reference @ `client_quickstart`
  docs/client_quickstart.rst
  docs/conf.py
Labels: backport-3.8

#5585 Add types for pytest plugin
  CHANGES/5585.feature
  aiohttp/pytest_plugin.py
Labels: backport-3.8, bot:chronographer:provided

#5600 Add types for pytest plugin
  CHANGES/5585.feature
  aiohttp/pytest_plugin.py
Labels: bot:chronographer:provided

#5556 Add support for the `no_proxy` env var mechanism in the HTTP client
  CHANGES/4431.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#5635 Add regression test for #5621
  CHANGES/5635.misc
  tests/test_web_urldispatcher.py
Labels: backport-3.8, bot:chronographer:provided

#5649 Fix pip upgrade on windows machines #5648
  CHANGES/5648.misc
  Makefile
Labels: backport-3.8, bot:chronographer:provided
