Repository aio-libs/aiohttp, pull requests merged in 2021-10, with the labels that each got.

#6002 Add xfailing integration tests against ``proxy.py``
  .github/workflows/ci.yml
  CHANGES/6002.misc
  requirements/dev.txt
  requirements/test.txt
  tests/test_proxy_functional.py
Labels: client, infra, bot:chronographer:provided, backport-3.8, python

#6033 [PR #6002/d66e07c6 backport][3.8] Add xfailing integration tests against ``proxy.py``
  .github/workflows/ci.yml
  CHANGES/6002.misc
  requirements/dev.txt
  requirements/test.txt
  tests/test_proxy_functional.py
Labels: client, infra, bot:chronographer:provided, python

#6045 Add custom RST roles extlinks to the docs setup
  CHANGES/6045.misc
  docs/conf.py
Labels: enhancement, documentation, infra, meta, Hacktoberfest, bot:chronographer:provided, backport-3.8

#5992 Add secure proxy support in the client
  CHANGES/5992.feature
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  docs/client_advanced.rst
  tests/test_client_request.py
  tests/test_proxy.py
  tests/test_proxy_functional.py
Labels: enhancement, client, bot:chronographer:provided, reproducer: present, backport-3.8, python

#6047 Add a README to the change notes dir
  CHANGES/README.rst
Labels: documentation, bot:chronographer:skip, backport-3.8

#6050 Fix the `check_changes` script to allow README&rst
  tools/check_changes.py
Labels: bot:chronographer:skip, backport-3.8

#6055 Implement future changelog previews in the docs
  .readthedocs.yml
  CHANGES.rst
  CHANGES/3559.doc
  CHANGES/3828.feature
  CHANGES/4054.feature
  CHANGES/4277.feature
  CHANGES/4299.bugfix
  CHANGES/4302.bugfix
  CHANGES/4452.doc
  CHANGES/4700.feature
  CHANGES/5326.doc
  CHANGES/5783.feature
  CHANGES/5905.bugfix
  docs/changes.rst
  docs/conf.py
  docs/spelling_wordlist.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
Labels: bot:chronographer:skip, backport-3.8

#5977 Docs: Add aiohttp-socks to third party libraries
  docs/third_party.rst
Labels: bot:chronographer:skip, backport-3.8

#6178 fix(5432): add query parameters in tracing url
  CHANGES/5432.bugfix
  aiohttp/client.py
  tests/test_client_session.py
Labels: bot:chronographer:provided, backport-3.8

#5894 Do not restrict +json media type suffix to application/
  CHANGES/5894.bugfix
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.8

#5534 StaticResource only matches folder-like URL prefix
  CHANGES/5250.bugfix
  CONTRIBUTORS.txt
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.8

#6181 Make JSON media type matching case insensitive
  CHANGES/6181.bugfix
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#5557 test_proxy_from_env did not clear proxies already set in the
  CHANGES/5554.bugfix
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.8

#6182 Raise '400: Content-Length can't be present with Transfer-Encoding' if both Content-Length and Transfer-Encoding are sent by peer
  CHANGES/6182.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.8

#6129 Add a `base_url` option to `ClientSession`
  CHANGES/6013.feature
  aiohttp/client.py
  docs/client_quickstart.rst
  docs/client_reference.rst
  tests/test_client_session.py
Labels: bot:chronographer:provided, backport-3.8

#6183 [PR #4661/50753eac backport][3.8] Support websocket proxies configured via environment variables
  CHANGES/4648.bugfix
  aiohttp/helpers.py
  docs/client_advanced.rst
  tests/test_helpers.py
Labels: bot:chronographer:provided

#6184 [PR #5557/bb4ee18d backport][3.8] test_proxy_from_env did not clear proxies already set in the
  CHANGES/5554.bugfix
  tests/test_helpers.py
Labels: bot:chronographer:provided

#6185 Add a no-op checking job to GHA
  .github/workflows/ci.yml
Labels: bot:chronographer:skip, backport-3.8
