Repository aio-libs/aiohttp, pull requests merged in 2021-07, with the labels that each got.

#5847 Ascola/add handler type aliases
  CHANGES/4686.feature
  CONTRIBUTORS.txt
  aiohttp/typedefs.py
  aiohttp/web_app.py
  aiohttp/web_middlewares.py
  aiohttp/web_routedef.py
  aiohttp/web_urldispatcher.py
  examples/web_rewrite_headers_middleware.py
  tests/test_web_app.py
  tests/test_web_functional.py
  tests/test_web_log.py
  tests/test_web_middleware.py
Labels: backport-3.8, bot:chronographer:provided

#5861 Ascola/add handler type aliases (#5847)
  CHANGES/4686.feature
  CONTRIBUTORS.txt
  aiohttp/typedefs.py
  aiohttp/web_app.py
  aiohttp/web_middlewares.py
  aiohttp/web_routedef.py
  aiohttp/web_urldispatcher.py
  examples/web_rewrite_headers_middleware.py
  tests/test_web_app.py
  tests/test_web_functional.py
  tests/test_web_log.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided

#5862 Use `MultiLoopChildWatcher` in tests where available
  CHANGES/3450.bugfix
  CONTRIBUTORS.txt
  aiohttp/test_utils.py
Labels: backport-3.8, bot:chronographer:provided

#5887 Update built_with.rst
  docs/built_with.rst
Labels: backport-3.8

#5890 Update to Mypy 0.910
  .mypy.ini
  CHANGES/5890.misc
  requirements/dev.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/test.txt
  tests/autobahn/client/client.py
  tests/autobahn/server/server.py
Labels: backport-3.8, bot:chronographer:provided

#5892 Backport: Update Mypy (#5890)
  .mypy.ini
  CHANGES/5890.misc
  requirements/dev.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/test.txt
  tests/autobahn/client/client.py
  tests/autobahn/server/server.py
Labels: bot:chronographer:provided

#5828 Remove incorrect default from docs
  CHANGES/5727.bugfix
  docs/web_reference.rst
Labels: backport-3.8, bot:chronographer:provided

#5908 Improve English grammar on the deployment doc page
  docs/deployment.rst
Labels: backport-3.8, documentation

#5848 Keep auth header during http->https redirect
  CHANGES/5783.feature
  aiohttp/client.py
  docs/client_advanced.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#5877 Switch to ThreadedChildWatcher and test
  CHANGES/5877.bugfix
  aiohttp/test_utils.py
  tests/test_loop.py
Labels: backport-3.8, bot:chronographer:provided
