Repository aio-libs/aiohttp, pull requests merged in 2021-08, with the labels that each got.

#5928 fix: remove deprecated loop argument for asnycio.sleep/gather calls
  CHANGES/5905.bugfix
  aiohttp/web.py
  tests/test_connector.py
  tests/test_locks.py
Labels: bot:chronographer:provided

#5932 Dependabot auto-merge
  .github/workflows/auto-merge.yml
  CHANGES/5932.misc
Labels: bot:chronographer:provided, backport-3.8

#5939 🔥 Remove the mypy section from `setup.cfg`
  setup.cfg
Labels: backport-3.8

#5850 Clarify auth header destiny during the redirect
  CHANGES/5850.doc
  docs/client_advanced.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#5960 Remove remaining attrs
  CHANGES/5806.misc
  README.rst
  aiohttp/client.py
  aiohttp/web_protocol.py
  docs/index.rst
  tests/autobahn/Dockerfile.aiohttp
Labels: bot:chronographer:provided, backport-3.8

#5963 Stop codecov emailing bad reports
  .codecov.yml
Labels: bot:chronographer:skip

#5971 Second attempt to delay codecov status
  .codecov.yml
Labels: bot:chronographer:skip

#5973 Last attempt to delay codecov reports
  .codecov.yml
Labels: bot:chronographer:skip

#5978 Cleanup English on third_party.rst
  docs/third_party.rst
Labels: bot:chronographer:skip, backport-3.8
