Repository aio-libs/aiohttp, pull requests merged in 2022-12, with the labels that each got.

#6969 Downgrade the `GITHUB_TOKEN` privileges in GitHub Workflows CI/CD
  .github/workflows/ci.yml
  .github/workflows/post-dependabot.yml
  .github/workflows/update-pre-commit.yml
Labels: bot:chronographer:skip, backport-3.9

#7056 Added a configuration flag for enable request task handler cancelling when client connection closing.
  CHANGES/7056.feature
  aiohttp/web.py
  aiohttp/web_protocol.py
  aiohttp/web_server.py
  docs/web_reference.rst
  tests/test_web_server.py
Labels: bot:chronographer:provided

#7127 Patchback/backports/3.9/38b9ec51e52fdcab11bbe322cc66392c599ca183/pr 7056
  CHANGES/7056.feature
  aiohttp/web.py
  aiohttp/web_protocol.py
  aiohttp/web_server.py
  docs/web_reference.rst
  tests/test_web_server.py
Labels: bot:chronographer:provided

#7134 Fix CI
  .github/workflows/ci.yml
  docs/web_reference.rst
Labels: bot:chronographer:skip

#7144 Remove discourse links
  .github/ISSUE_TEMPLATE/config.yml
  README.rst
  docs/conf.py
  docs/index.rst
Labels: bot:chronographer:skip, backport-3.9

#7143 [3.9] Fix CI
  .github/workflows/ci.yml
  aiohttp/helpers.py
  docs/web_reference.rst
  tests/test_client_request.py
  tests/test_streams.py
  tests/test_web_app.py
Labels: bot:chronographer:skip, backport-3.8

#7146 [3.9] Remove discourse links
  README.rst
  docs/conf.py
  docs/index.rst
Labels: bot:chronographer:skip

#7154 fixed error in ContentDisposition doc
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9
