Repository aio-libs/aiohttp, pull requests merged in 2022-11, with the labels that each got.

#6810 Fix readuntil work
  CHANGES/6701.bugfix
  CONTRIBUTORS.txt
  aiohttp/streams.py
  tests/test_streams.py
Labels: bot:chronographer:provided, backport-3.9

#7084 change requote_redirect_url docs default to true
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.9

#7044 Fix unicode errors
  CHANGES/7044.bugfix
  aiohttp/http_parser.py
  aiohttp/multipart.py
  tests/test_http_parser.py
  tests/test_multipart.py
Labels: bot:chronographer:provided, backport-3.9

#7055 Add `auto_decompress` parameter to `ClientSession.request()`
  CHANGES/3751.feature
  aiohttp/client.py
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.9

#6591 Improve import time
  .coveragerc
  CHANGES/6591.misc
  aiohttp/__init__.py
  requirements/constraints.txt
  requirements/lint.txt
  requirements/test.txt
  setup.cfg
  tests/test___all__.py
  tests/test_imports.py
Labels: bot:chronographer:provided, backport-3.9

#7092 Backport #6598
  .coveragerc
  CHANGES/6591.misc
  aiohttp/__init__.py
  setup.cfg
  tests/test___all__.py
  tests/test_imports.py
Labels: bot:chronographer:provided

#7096 Better import time test
  tests/test_imports.py
Labels: bot:chronographer:skip, backport-3.9

#7099 Fix unicode errors (#7044)
  CHANGES/7044.bugfix
  aiohttp/http_parser.py
  aiohttp/multipart.py
  tests/test_http_parser.py
  tests/test_multipart.py
Labels: bot:chronographer:provided

#7100 Add client Brotli support (#5227)
  CHANGES/5219.feature
  aiohttp/client_reqrep.py
  docs/glossary.rst
  docs/index.rst
  docs/spelling_wordlist.txt
  tests/test_client_request.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#6903 Refactor code to use HTTPStatus instead of http.server
  CHANGES/6903.misc
  CONTRIBUTORS.txt
  aiohttp/connector.py
  aiohttp/http.py
  aiohttp/web_response.py
  tests/test_imports.py
Labels: bot:chronographer:provided, backport-3.9

#7104 Backport #6903
  CHANGES/6903.misc
  CONTRIBUTORS.txt
  aiohttp/connector.py
  aiohttp/http.py
  aiohttp/web_response.py
  tests/test_imports.py
Labels: bot:chronographer:provided

#6967 Compute XOR table lazily
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip, backport-3.9

#6916 Add missing __repr__ to streams.EmptyStreamReader
  CHANGES/6916.bugfix
  CONTRIBUTORS.txt
  aiohttp/streams.py
  tests/test_streams.py
Labels: bot:chronographer:provided, backport-3.9

#6876 Use PathLike
  aiohttp/web.py
  aiohttp/web_fileresponse.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  docs/web_reference.rst
  tests/test_web_sendfile.py
Labels: bot:chronographer:skip, backport-3.9

#7054 Third-Part/Other addition: RSocket
  docs/third_party.rst
Labels: bot:chronographer:skip, backport-3.9

#7111 Use PathLike (backport #6876)
  aiohttp/web.py
  aiohttp/web_fileresponse.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  docs/web_reference.rst
  tests/test_web_sendfile.py
Labels: bot:chronographer:skip
