Repository aio-libs/aiohttp, pull requests merged in 2022-08, with the labels that each got.

#6857 Stop installing cchardet speedup under >Python 3.9
  CHANGES/6857.misc
  docs/_snippets/cchardet-unmaintained-admonition.rst
  docs/glossary.rst
  docs/index.rst
  requirements/base.txt
  setup.cfg
Labels: bug, enhancement, meta, dependencies, bot:chronographer:provided, backport-3.8, backport-3.9

#6872 ignore the ResourceWarnings before they become unraisable exceptions
  CHANGES/6872.misc
  setup.cfg
  tests/test_run_app.py
  tests/test_tcp_helpers.py
Labels: bot:chronographer:skip, backport-3.9

#6877 work around the changes in 3.11, eg asyncio.TimeoutError is an OSError, and IsolatedAsyncioTestCase calls set_event_loop differently
  CHANGES/6757.misc
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/test_utils.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6892 Remove unused type: ignore
  tests/test_run_app.py
Labels: bot:chronographer:skip

#6875 Change single link and add frozenlist.
  README.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9
