Repository aio-libs/aiohttp, pull requests merged in 2022-10, with the labels that each got.

#6998 Add documentation section on client authentication
  CHANGES/6998.doc
  docs/client_advanced.rst
Labels: bot:chronographer:provided

#6979 Grammar improvements around backwards-compatibility policy.
  CHANGES/6979.doc
  docs/index.rst
Labels: bot:chronographer:provided

#7014 Cover ttl=0 (expire always) _DNSCacheTable case
  CHANGES/7014.bugfix
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.9

#7045 Cover ttl=0 (expire always) _DNSCacheTable case (#7014)
  CHANGES/7014.bugfix
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#7057 Raise allowed charset version
  setup.cfg
Labels: bot:chronographer:skip, backport-3.9

#7025 Fix expect handler when returning a response
  CHANGES/7025.bugfix
  aiohttp/abc.py
  aiohttp/web_urldispatcher.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.9

#7058 Patchback/backports/3.9/18de88ce1e0a176adb12bf9ee44783289c6bed63/pr 7025
  CHANGES/7025.bugfix
  aiohttp/abc.py
  aiohttp/web_urldispatcher.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#6907 docs: Update redis to follow the latest spec
  CHANGES/6907.doc
  docs/web_advanced.rst
Labels: bot:chronographer:provided
