Repository aio-libs/aiohttp, pull requests merged in 2022-03, with the labels that each got.

#6638 Fix cookie handling
  CHANGES/6638.bugfix
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.9

#6665 Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6664 Fix pytest.warns(None) usage, deprecated in pytest 7
  CHANGES/6663.bugfix
  CONTRIBUTORS.txt
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9
