Repository aio-libs/aiohttp, pull requests merged in 2022-05, with the labels that each got.

#6731 Patchback/backports/3.9/e5beaca052434cbf1c1814170917085eb271ba43/pr 3892 implement response check
  CHANGES/3892.feature
  aiohttp/client.py
  docs/client_reference.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#6734 Stop using the cgi module, deprecated in Python 3.11 per PEP 594
  CHANGES/6708.misc
  aiohttp/helpers.py
Labels: bot:chronographer:provided

#6733 Powered By: Remove Morpheus messaging microservice
  docs/powered_by.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6727 Fix asyncio.CancelledError again (#6719)
  CHANGES/6719.bugfix
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6725 Remove max headers parameter
  CHANGES/6721.misc
  aiohttp/http_parser.py
  aiohttp/web_protocol.py
  docs/web_reference.rst
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#6749 fix DeprecationWarning
  README.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6756 Fix pip reinstallation on windows due to constraints
  Makefile
Labels: bot:chronographer:skip
