Repository aio-libs/aiohttp, pull requests merged in 2022-01, with the labels that each got.

#6477 Typo in docs, should mention cchardet
  docs/index.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6491 Switch to cleanup_ctx in example
  docs/web_advanced.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6502 Add aiohttp-catcher to 3rd party libraries
  docs/third_party.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6524 Simplify graceful shutdown example
  docs/client_advanced.rst
Labels: bot:chronographer:skip, backport-3.9

#6321 Ignore protocol exceptions after it is closed
  CHANGES/4526.bugfix
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6539 Recover missing import in circular import test
  tests/test_circular_imports.py
Labels: bug, reproducer: present, bot:chronographer:skip, backport-3.8, backport-3.9

#6536 Fix missing AttributeError
  aiohttp/test_utils.py
  tests/test_test_utils.py
Labels: bot:chronographer:skip, backport-3.9

#6498 Introduce AppKey for type safety
  CHANGES/5864.feature
  aiohttp/helpers.py
  aiohttp/web.py
  aiohttp/web_app.py
  docs/client_advanced.rst
  docs/faq.rst
  docs/spelling_wordlist.txt
  docs/testing.rst
  docs/web_advanced.rst
  docs/web_reference.rst
  examples/background_tasks.py
  examples/cli_app.py
  examples/web_ws.py
  tests/autobahn/server/server.py
  tests/test_web_app.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.9

#6548 Introduce AppKey
  CHANGES/5864.feature
  aiohttp/helpers.py
  aiohttp/web.py
  aiohttp/web_app.py
  docs/faq.rst
  docs/spelling_wordlist.txt
  docs/testing.rst
  docs/web_advanced.rst
  docs/web_reference.rst
  examples/background_tasks.py
  examples/cli_app.py
  examples/web_ws.py
  tests/autobahn/server/server.py
  tests/test_web_app.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#6550 Pin down multidict
  CHANGES/6550.misc
  setup.cfg
Labels: bot:chronographer:provided

#6533 Add HTTP method validation
  CHANGES/6533.feature
  aiohttp/client_reqrep.py
  tests/test_client_request.py
  tests/test_web_request.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6547 Remove overlapping slots and fix broken slots inheritance
  .github/workflows/ci.yml
  CHANGES/6547.bugfix
  CONTRIBUTORS.txt
  aiohttp/helpers.py
  aiohttp/web_protocol.py
  aiohttp/web_response.py
  requirements/lint.txt
  tests/test_helpers.py
Labels: bot:chronographer:provided

#6568 Unused type: ignores
  aiohttp/web_ws.py
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6553 Add aioredis for type checking examples
  examples/background_tasks.py
  requirements/constraints.txt
  requirements/lint.txt
Labels: bot:chronographer:skip, backport-3.9

#6549 Cleanup after dropping Python 3.6
  .pre-commit-config.yaml
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/multipart.py
  aiohttp/streams.py
  aiohttp/web_fileresponse.py
  docs/third_party.rst
  docs/web_advanced.rst
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/test.txt
  tests/conftest.py
  tests/test_client_exceptions.py
Labels: bot:chronographer:skip, backport-3.9

#6571 Backport aioredis typing
  .mypy.ini
  examples/background_tasks.py
  requirements/constraints.txt
  requirements/lint.txt
Labels: bot:chronographer:skip

#6577 Patchback/backports/3.9/1dbfbb433f3f7cd05ca97288805dec9e296d75de/pr 6549
  .pre-commit-config.yaml
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/multipart.py
  aiohttp/streams.py
  aiohttp/web_fileresponse.py
  docs/third_party.rst
  docs/web_advanced.rst
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/test.txt
  tests/conftest.py
  tests/test_client_exceptions.py
Labels: bot:chronographer:provided, bot:chronographer:skip
