Repository aio-libs/aiohttp, pull requests merged in 2022-04, with the labels that each got.

#6676 Bump black to fix CI
  .pre-commit-config.yaml
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/cookiejar.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/tcp_helpers.py
  aiohttp/test_utils.py
  aiohttp/web_app.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_ws.py
  tests/conftest.py
  tests/test_client_functional.py
  tests/test_http_parser.py
  tests/test_multipart.py
  tests/test_payload.py
  tests/test_proxy_functional.py
  tests/test_streams.py
  tests/test_web_functional.py
  tests/test_web_request.py
Labels: bot:chronographer:skip

#6677 Fix 3.9 CI
  .github/workflows/ci.yml
Labels: bot:chronographer:skip

#6683 [doc] clarify ClientTimeout behavior
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6687 Update constraints.txt
  requirements/constraints.txt
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6700 fix ClientResponseError docstring
  CHANGES/6700.doc
  aiohttp/client_exceptions.py
Labels: bot:chronographer:provided

#6714 Add experimental 3.11 test
  .github/workflows/ci.yml
Labels: bot:chronographer:skip, backport-3.9

#6715 Add experimental 3.11 tests
  .github/workflows/ci.yml
Labels: bot:chronographer:skip

#6708 Stop using the cgi module, deprecated in Python 3.11 per PEP 594
  CHANGES/6708.misc
  aiohttp/helpers.py
Labels: bot:chronographer:provided, backport-3.9
