Repository aio-libs/aiohttp, pull requests merged in 2022-09, with the labels that each got.

#6889 Export `PrefixedSubAppResource` in `aiohttp.web`
  CHANGES/6889.bugfix
  aiohttp/web.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#6923 Exclude the `object` possibility from the `ClientSession.timeout` type
  CHANGES/6917.bugfix
  CHANGES/6917.doc
  CHANGES/6923.bugfix
  CHANGES/6923.doc
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.9

#6950 Increase the upper boundary of the multidict dependency allowing v6
  CHANGES/6950.bugfix
  aiohttp/web_ws.py
  setup.cfg
Labels: bot:chronographer:provided

#6956 Merge-in the 3.9 stream into master
  .github/workflows/ci.yml
  CHANGES.rst
  CHANGES/4046.removal
  CHANGES/4137.doc
  CHANGES/4663.bugfix
  CHANGES/6227.bugfix
  CHANGES/6369.misc
  CHANGES/6378.removal
  CHANGES/6399.misc
  CHANGES/6401.doc
  CHANGES/6663.bugfix
  CHANGES/6708.misc
  CHANGES/6719.bugfix
  CHANGES/6757.misc
  CHANGES/6857.misc
  CHANGES/6872.misc
  CHANGES/6889.bugfix
  CHANGES/6917.bugfix
  CHANGES/6917.doc
  CHANGES/6923.bugfix
  CHANGES/6923.doc
  aiohttp/__init__.py
  docs/conf.py
  examples/curl.py
  tests/test_run_app.py
Labels: bot:chronographer:provided

#6957 [PR #6843/f90cb195 backport][3.9] Add type Path on web app run
  CHANGES/6839.feature
  CONTRIBUTORS.txt
  aiohttp/web.py
  aiohttp/web_runner.py
  docs/web_reference.rst
Labels: bot:chronographer:provided

#6974 [3.8] Fix cookie handling (#6638)
  CHANGES/6638.bugfix
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#6891 [3.9] Fix cookie handling (#6638)
  CHANGES/6638.bugfix
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#6993 Remove Extra Spaces
  README.rst
Labels: bot:chronographer:skip, backport-3.9
