Repository aio-libs/aiohttp, pull requests merged in 2022-07, with the labels that each got.

#6825 Ignore black commits in `git blame`
  .git-blame-ignore-revs
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6829 Allow linking to request()
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#6840 Cleanup sphinx nitpicks
  docs/conf.py
Labels: bot:chronographer:skip, backport-3.9

#6843 Add type Path on web app run
  CHANGES/6839.feature
  CONTRIBUTORS.txt
  aiohttp/web.py
  aiohttp/web_runner.py
  docs/web_reference.rst
  tests/test_run_app.py
Labels: bot:chronographer:provided, backport-3.9

#6846 Fixed ClientConnectorError docstring
  aiohttp/client_exceptions.py
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.8, backport-3.9
