Repository aio-libs/aiohttp, pull requests merged in 2023-11, with the labels that each got.

#7756 Ensure empty body response for 1xx/204/304 per RFC 9112 sec 6.3
  CHANGES/7756.bugfix
  aiohttp/helpers.py
  aiohttp/web_fileresponse.py
  aiohttp/web_response.py
  tests/test_client_functional.py
  tests/test_helpers.py
  tests/test_web_functional.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.9

#7776 Bugfix Edge Case Handling for ResponseParser for missing reason value
  CHANGES/7776.bugfix
  CONTRIBUTORS.txt
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.9

#7718 Redesign shutdown process
  CHANGES/7718.feature
  aiohttp/web.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/worker.py
  docs/web_advanced.rst
  tests/test_run_app.py
  tests/test_worker.py
Labels: bot:chronographer:provided

#7778 Ensure empty body response for 1xx/204/304 per RFC 9112 sec 6.3 (#7756)
  CHANGES/7756.bugfix
  aiohttp/helpers.py
  aiohttp/web_fileresponse.py
  aiohttp/web_response.py
  tests/test_client_functional.py
  tests/test_helpers.py
  tests/test_web_functional.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#7780 Redesign shutdown process
  CHANGES/7718.feature
  aiohttp/web.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/worker.py
  docs/web_advanced.rst
  tests/test_run_app.py
  tests/test_worker.py
Labels: bot:chronographer:provided

#7764 Fix missing eof when writer cancelled
  CHANGES/7764.bugfix
  aiohttp/client.py
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
  tests/test_client_response.py
  tests/test_proxy_functional.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.9

#7781 Fix missing eof when writer cancelled (#7764)
  CHANGES/7764.bugfix
  aiohttp/client.py
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
  tests/test_client_response.py
  tests/test_proxy_functional.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#7782 Possibly fix some flaky tests
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#7783 Possibly fix some flaky tests
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#7785 Fix coroutine wrapper to await after exception
  CHANGES/7785.bugfix
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.9

#7786 Fix coroutine wrapper to await after exception (#7785)
  CHANGES/7785.bugfix
  aiohttp/client.py
Labels: bot:chronographer:provided

#7797 Fix increase in latency with small messages from websocket compression changes
  CHANGES/7797.bugfix
  aiohttp/http_websocket.py
Labels: bot:chronographer:provided, backport-3.9

#7775 Add codespell support: pre-commit entry, configuration, some typoes get fixed
  .pre-commit-config.yaml
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  docs/abc.rst
  docs/client_quickstart.rst
  docs/client_reference.rst
  docs/index.rst
  docs/spelling_wordlist.txt
  pyproject.toml
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport-3.9

#7806 Add HTTP method validation (#6533)
  CHANGES/6533.feature
  aiohttp/client_reqrep.py
  tests/test_client_request.py
  tests/test_web_request.py
Labels: bot:chronographer:provided

#7809 Update pyupgrade to --py37-plus
  .pre-commit-config.yaml
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip, backport-3.9

#7819 Skip filtering ``CookieJar`` when the jar is empty or all cookies have expired
  CHANGES/7819.feature
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
Labels: bot:chronographer:provided, backport-3.9

#7820 Bump pypy to 3.9
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.9

#7822 [PR #7819/dfc3f899 backport][3.9] Skip filtering ``CookieJar`` when the jar is empty or all cookies have expired
  CHANGES/7819.feature
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
Labels: bot:chronographer:provided

#7821 Only check origin if insecure scheme and there are origins to treat as secure, in CookieJar.filter_cookies()
  CHANGES/7821.feature
  aiohttp/cookiejar.py
Labels: bot:chronographer:provided, backport-3.9

#7815 Ensure writer is always reset on completion
  CHANGES/7815.bugfix
  aiohttp/client_reqrep.py
  tests/test_client_response.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.9

#7827 Test fixes
  tests/test_client_request.py
Labels: bot:chronographer:skip

#7826 Ensure writer is always reset on completion (#7815)
  CHANGES/7815.bugfix
  aiohttp/client_reqrep.py
  tests/test_client_request.py
  tests/test_client_response.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#7835 Disallow arbitrary sequence types in version
  CHANGES/7835.bugfix
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided, backport-3.9

#7836 Disallow arbitrary sequence types in version (#7835)
  CHANGES/7835.bugfix
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided

#7824 Use timestamp instead of datetime to achieve faster cookie expiration in CookieJar
  CHANGES/7824.feature
  aiohttp/cookiejar.py
  aiohttp/helpers.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.9

#7837 Use timestamp instead of datetime to achieve faster cookie expiration…
  CHANGES/7824.feature
  aiohttp/cookiejar.py
  aiohttp/helpers.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#7840 Release v3.9.0rc0
  aiohttp/__init__.py
Labels: bot:chronographer:skip, backport-3.9

#7843 Release v3.9.0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#7847 Bump to 3.9.0.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#7850 Fix import under PyPy 3.8/3.9 on Windows
  CHANGES/7848.bugfix
  aiohttp/cookiejar.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#7852 Add requirement files to sdist
  MANIFEST.in
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7863 remove tests/__init__.py
  tests/__init__.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7869 Fix ClientResponse.close releasing the connection instead of closing
  CHANGES/7869.bugfix
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#7874 Fix ClientResponse.close releasing the connection instead of closing (#7869)
  CHANGES/7869.bugfix
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#7873 Fix ClientResponse.close releasing the connection instead of closing (#7869)
  CHANGES/7869.bugfix
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#7773 Fix usage of proxy.py in test_proxy_functional
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7877 Fix usage of proxy.py in test_proxy_functional (#7773)
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#7876 Fix usage of proxy.py in test_proxy_functional (#7773)
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#7865 Restore async concurrency safety to websocket compressor
  CHANGES/7865.bugfix
  aiohttp/compression_utils.py
  aiohttp/http_websocket.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#7883 Update dependabot.yml
  .github/dependabot.yml
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7884 Update dependabot.yml
  .github/dependabot.yml
Labels: bot:chronographer:skip

#7888 Update dependabot.yml
  .github/dependabot.yml
Labels: bot:chronographer:skip

#7890 Restore async concurrency safety to websocket compressor (#7865)
  CHANGES/7865.bugfix
  aiohttp/compression_utils.py
  aiohttp/http_websocket.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided

#7886 Update dependabot.yml
  .github/dependabot.yml
Labels: bot:chronographer:skip, backport:skip

#7889 Restore async concurrency safety to websocket compressor (#7865)
  CHANGES/7865.bugfix
  aiohttp/compression_utils.py
  aiohttp/http_websocket.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided

#7895 Message is not upgraded if Upgrade header is missing
  CHANGES/7895.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#7897 Message is not upgraded if Upgrade header is missing (#7895)
  CHANGES/7895.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7898 Message is not upgraded if Upgrade header is missing (#7895)
  CHANGES/7895.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7896 Fix some flaky tests
  tests/test_web_server.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7902 Fix flaky websocket test
  tests/test_client_ws_functional.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7903 Fix flaky websocket test (#7902)
  tests/test_client_ws_functional.py
Labels: bot:chronographer:skip

#7904 Fix flaky websocket test (#7902)
  tests/test_client_ws_functional.py
Labels: bot:chronographer:skip

#7907 Fix regression with connection upgrade (#7879)
  CHANGES/7879.bugfix
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#7908 Fix regression with connection upgrade (#7879)
  CHANGES/7879.bugfix
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#7829 Index resources in the UrlDispatcher to avoid linear search for most cases
  CHANGES/7829.misc
  aiohttp/web_urldispatcher.py
  docs/web_reference.rst
  tests/test_urldispatch.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10

#7808 Restore requirements-txt-fixer in pre-commit
  .pre-commit-config.yaml
  Makefile
  requirements/runtime-deps.in
  requirements/sync-direct-runtime-deps.py
  requirements/test.in
  setup.cfg
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7920 [PR #7808/213d1b2 backport][3.9] Restore requirements-txt-fixer in pre-commit
  .pre-commit-config.yaml
  Makefile
  requirements/runtime-deps.in
  requirements/sync-direct-runtime-deps.py
  requirements/test.in
  setup.cfg
Labels: bot:chronographer:skip

#7921 [PR #7808/213d1b2 backport][3.10] Restore requirements-txt-fixer in pre-commit
  .pre-commit-config.yaml
  Makefile
  requirements/runtime-deps.in
  requirements/sync-direct-runtime-deps.py
  requirements/test.in
  setup.cfg
Labels: bot:chronographer:skip

#7818 Separate timeout errors (#7801)
  CHANGES/7801.feature
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_proto.py
  docs/client_reference.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10
