Repository aio-libs/aiohttp, pull requests merged in 2023-01, with the labels that each got.

#7128 Add documentation for handler cancellation behaviour
  CHANGES/7056.feature
  docs/conf.py
  docs/spelling_wordlist.txt
  docs/web_advanced.rst
  docs/web_quickstart.rst
  docs/web_reference.rst
Labels: bot:chronographer:skip, backport-3.9

#7160 Patchback/backports/3.9/743c21f4f683e11ecef588a0955b433a3b3102e9/pr 7128
  CHANGES/7056.feature
  docs/conf.py
  docs/spelling_wordlist.txt
  docs/web_advanced.rst
  docs/web_quickstart.rst
  docs/web_reference.rst
Labels: bot:chronographer:provided, bot:chronographer:skip

#7153 remove import aliases
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/http.py
  aiohttp/web.py
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.9

#7175 Drop Python 3.6
  README.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/payload.py
  aiohttp/pytest_plugin.py
  aiohttp/web.py
  docs/index.rst
  setup.cfg
  setup.py
  tests/autobahn/test_autobahn.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_helpers.py
  tests/test_proxy.py
  tests/test_proxy_functional.py
  tests/test_pytest_plugin.py
  tests/test_run_app.py
  tests/test_web_app.py
  tests/test_web_log.py
  tests/test_web_runner.py
  tox.ini
Labels: bot:chronographer:skip
