Repository aio-libs/aiohttp, pull requests merged in 2023-10, with the labels that each got.

#7644 Fixed 7616: EmptyStreamReader.iter_chunks() never ends
  CHANGES/7616.bugfix
  aiohttp/streams.py
  tests/test_streams.py
Labels: bot:chronographer:provided, backport-3.9

#7661 Update Python parser for RFCs 9110/9112
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:skip, backport-3.8

#7663 Allow lax response parsing on Py parser
  CHANGES/7663.feature
  Makefile
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7665 Allow lax response parsing on Py parser (#7663)
  CHANGES/7663.feature
  Makefile
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7651 Fix BadStatusLine message
  CHANGES/7651.bugfix
  aiohttp/_http_parser.pyx
  aiohttp/http_exceptions.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7664 Allow lax response parsing on Py parser (#7663)
  CHANGES/7663.feature
  Makefile
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7676 Update FUNDING.yml
  .github/FUNDING.yml
Labels: bot:chronographer:skip

#7684 Make setup.cfg packages explicit
  setup.cfg
Labels: bot:chronographer:skip, backport-3.9

#7680 Fix #7306 - Set ClientWebSocketResponse.close_code correctly in concurrent closing scenario
  CHANGES/7306.bugfix
  aiohttp/client_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided, backport-3.9

#7690 [PR #7684/30850ba backport][3.9] Fix #7306 - Set ClientWebSocketResponse.close_code correctly in concu…
  CHANGES/7306.bugfix
  aiohttp/client_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided

#7658 Implement WebSocketResponse.get_extra_info method to avoid using private member
  CHANGES/7078.feature
  CONTRIBUTORS.txt
  aiohttp/web_ws.py
  docs/client_reference.rst
  docs/web_reference.rst
  tests/test_web_websocket.py
Labels: bot:chronographer:provided, backport-3.9

#7689 feature: allow link argument to be set to None/empty in HTTP 451 exception
  CHANGES/7689.feature
  CONTRIBUTORS.txt
  aiohttp/web_exceptions.py
  docs/web_exceptions.rst
  tests/test_web_exceptions.py
Labels: bot:chronographer:provided, backport-3.9

#7704 [backport] feature: allow link argument to be set to None/empty in HTTP 451 exception
  CHANGES/7689.feature
  CONTRIBUTORS.txt
  aiohttp/web_exceptions.py
  docs/conf.py
  docs/web_quickstart.rst
  tests/test_web_exceptions.py
Labels: bot:chronographer:provided

#7713 Add check to validate absolute URIs
  CHANGES/7712.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.9

#7702 Update README.rst
  README.rst
Labels: bot:chronographer:skip, backport-3.9

#7716 Fix unhandled exception for invalid Unicode in Python HTTP parser
  CHANGES/7715.bugfix
  aiohttp/http_exceptions.py
  aiohttp/http_parser.py
  tests/test_http_exceptions.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.9

#7719 Stop accepting `\x80-\xff` in header names; stop accepting `\n` as separating whitespace in status-lines
  CHANGES/7719.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7656 replace freezegun with time_machine
  requirements/constraints.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/test_cookiejar.py
Labels: bot:chronographer:skip, backport-3.9

#7730 Backport 493f06797654c383242f0e8007f6e06b818a1fbc to 3.9
  CHANGES/7719.bugfix
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7736 Backport a7bc5e9eeae7c5c90898411962e9a74bf10a9cef to 3.9
  requirements/constraints.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/test_cookiejar.py
Labels: bot:chronographer:skip

#7733 Fix, update, and improve client exceptions documentation
  CHANGES/7733.doc
  docs/client_reference.rst
Labels: documentation, bot:chronographer:provided, backport-3.9

#7729 Reenable uvloop on Python 3.12
  requirements/base.in
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.9

#7749 Enable testing merge queues @ GitHub Actions CI/CD
  .github/workflows/ci-cd.yml
Labels: infra, bot:chronographer:skip, backport-3.8, backport-3.9

#7677 Fix warning displayed by default
  CHANGES/7677.bugfix
  aiohttp/web.py
  aiohttp/web_app.py
  aiohttp/web_exceptions.py
Labels: bot:chronographer:provided, backport-3.9

#7752 Fix warning displayed by default (#7677)
  CHANGES/7677.bugfix
  aiohttp/web.py
  aiohttp/web_app.py
  aiohttp/web_exceptions.py
Labels: bot:chronographer:provided

#7753 Make regex range more explicit
  aiohttp/helpers.py
Labels: bot:chronographer:skip, backport-3.9

#7758 Remove jquery from websockets example
  examples/websocket.html
Labels: bot:chronographer:skip, backport-3.9

#7761 Stop binding to all network interfaces in tests
  tests/test_run_app.py
Labels: bot:chronographer:skip, backport-3.9

#7755 Fix py http parser not treating 204/304/1xx as an empty body
  CHANGES/7755.bugfix
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.9

#7768 Fix py http parser not treating 204/304/1xx as an empty body (#7755)
  CHANGES/7755.bugfix
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7774 Fix CONNECT always being treated as having an empty body (#7772)
  CHANGES/7772.bugfix
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided
