Repository aio-libs/aiohttp, pull requests merged in 2023-07, with the labels that each got.

#7336 Drop Python 3.7
  .github/workflows/ci.yml
  CHANGES/7336.removal
  Makefile
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/test_utils.py
  aiohttp/web.py
  aiohttp/web_response.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  aiohttp/worker.py
  docs/client_advanced.rst
  docs/testing.rst
  docs/third_party.rst
  requirements/base.txt
  setup.cfg
  setup.py
  tests/conftest.py
  tests/test_client_session.py
  tests/test_cookiejar.py
  tests/test_loop.py
  tests/test_multipart.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:provided, backport-3.9

#7338 Drop Python 3.7 (#7336)
  .codecov.yml
  .github/workflows/ci.yml
  CHANGES/7336.removal
  Makefile
  aiohttp/client.py
  aiohttp/hdrs.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/payload.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/typedefs.py
  aiohttp/web.py
  aiohttp/web_fileresponse.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  aiohttp/web_ws.py
  aiohttp/worker.py
  docs/client_advanced.rst
  docs/contributing.rst
  docs/testing.rst
  docs/third_party.rst
  requirements/base.txt
  setup.cfg
  setup.py
  tests/conftest.py
  tests/test_client_session.py
  tests/test_cookiejar.py
  tests/test_loop.py
  tests/test_multipart.py
  tests/test_proxy_functional.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#7339 Fix typing of ssl parameter (#7335)
  CHANGES/7335.misc
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
Labels: bot:chronographer:provided

#7334 Expand SSLContext documentation with additional examples
  CHANGES/7334.doc
  docs/client_advanced.rst
Labels: bot:chronographer:provided, backport-3.9

#7178 [3.8] Make the 3.10 related xfails non-strict
  tests/test_client_request.py
  tests/test_streams.py
  tests/test_web_app.py
Labels: bot:chronographer:skip

#7345 Upgrade chat links and badges to Matrix
  README.rst
  setup.cfg
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#7348 🐛 Fix RST in changelog template before links
  CHANGES/.TEMPLATE.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#7346  Bump vendored llhttp to v8.1.1
  .gitmodules
  CHANGES/7346.feature
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7343 Mention encoding in `yarl.URL`
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#7333 Fix TLS transport is `None` error
  CHANGES/3355.bugfix
  aiohttp/connector.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7359  Set up secretless publishing to PyPI
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#7365 Turn RawResponseMessage into a NamedTuple
  CHANGES/7365.feature
  aiohttp/http_parser.py
Labels: bot:chronographer:provided, backport-3.9

#7370 fix: Spelling error fixed
  aiohttp/payload.py
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#7373 Drop azure mention
  docs/index.rst
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#7380 Improve error messages from C parser (#7366)
  CHANGES/7366.feature
  aiohttp/_http_parser.pyx
  aiohttp/http_exceptions.py
  tests/test_http_exceptions.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7378 Fix PermissionError when loading .netrc (#7237)
  CHANGES/7237.bugfix
  CONTRIBUTORS.txt
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7394 Fix PermissionError when loading .netrc (#7237) (#7378)
  CHANGES/7237.bugfix
  CONTRIBUTORS.txt
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#7395 Fix PermissionError when loading .netrc (#7237) (#7378)
  CHANGES/7237.bugfix
  CONTRIBUTORS.txt
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#7383 Replace sync `open()` calls within async functions with `aiofiles.open()` in code examples
  tools/bench-asyncio-write.py
Labels: bot:chronographer:skip, backport-3.9

#7400 Add experimental 3.12 tests
  .github/workflows/ci-cd.yml
  requirements/base.txt
  requirements/constraints.txt
  requirements/cython.txt
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.9

#7401 Add experimental 3.12 tests (#7400)
  .github/workflows/ci-cd.yml
  requirements/base.txt
  requirements/constraints.txt
  requirements/cython.txt
  requirements/lint.txt
  requirements/test.txt
  tests/test_client_request.py
  tests/test_streams.py
  tests/test_web_app.py
Labels: bot:chronographer:skip

#7439 Remove sphinxcontrib-asyncio
  docs/abc.rst
  docs/client_reference.rst
  docs/conf.py
  docs/multipart_reference.rst
  docs/streams.rst
  docs/testing.rst
  docs/web_reference.rst
  requirements/constraints.txt
  requirements/doc.txt
Labels: bot:chronographer:skip, backport-3.9

#7440 Remove sphinxcontrib-asyncio (#7439)
  docs/abc.rst
  docs/client_reference.rst
  docs/conf.py
  docs/multipart_reference.rst
  docs/streams.rst
  docs/testing.rst
  docs/web_reference.rst
  requirements/constraints.txt
  requirements/doc.txt
Labels: bot:chronographer:skip

#7448 Base url docs
  CHANGES/6647.doc
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.9

#7449 Bump dependencies
  requirements/constraints.txt
Labels: bot:chronographer:skip, backport-3.9

#7441 Tidy up toctree
  docs/client.rst
  docs/client_reference.rst
  docs/tracing_reference.rst
  docs/utilities.rst
  docs/web.rst
  docs/web_reference.rst
Labels: bot:chronographer:skip, backport-3.9

#7452 Tidy up toctree (#7441)
  docs/client.rst
  docs/client_reference.rst
  docs/tracing_reference.rst
  docs/utilities.rst
  docs/web.rst
  docs/web_reference.rst
Labels: bot:chronographer:skip
