Repository aio-libs/aiohttp, pull requests merged in 2023-05, with the labels that each got.

#7269 Update client_quickstart.rst
  docs/client_quickstart.rst
Labels: bot:chronographer:skip, backport-3.9

#7260 Update update_query calls to work with latest yarl
  CHANGES/7259.bugfix
  aiohttp/client.py
  requirements/base.txt
  requirements/constraints.txt
Labels: bot:chronographer:provided, backport-3.9

#7272 Fix Read The Docs config
  .readthedocs.yml
Labels: bot:chronographer:skip, backport-3.9

#7281 Remove tokio support
  .mypy.ini
  CHANGES/7281.removal
  aiohttp/pytest_plugin.py
  aiohttp/worker.py
  tests/test_run_app.py
  tests/test_worker.py
Labels: bot:chronographer:provided, backport-3.9

#7282 Remove tokio support (#7281)
  .mypy.ini
  CHANGES/7281.removal
  aiohttp/pytest_plugin.py
  aiohttp/worker.py
  tests/test_run_app.py
  tests/test_worker.py
Labels: bot:chronographer:provided

#6555 Start rechecking types on tests
  .mypy.ini
  aiohttp/http_websocket.py
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  aiohttp/worker.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/lint.txt
  tests/test_web_app.py
  tests/test_web_exceptions.py
  tests/test_web_request_handler.py
  tests/test_web_urldispatcher.py
  tests/test_worker.py
Labels: bot:chronographer:skip, backport-3.9

#7285 Start rechecking types on tests (#6555)
  .mypy.ini
  aiohttp/http_websocket.py
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  aiohttp/worker.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/lint.txt
  tests/test_web_app.py
  tests/test_web_exceptions.py
  tests/test_web_request_handler.py
  tests/test_web_urldispatcher.py
  tests/test_worker.py
Labels: bot:chronographer:skip

#6594 Export HTTPMove
  CHANGES/6594.feature
  aiohttp/web.py
Labels: bot:chronographer:provided, backport-3.9

#7288 Export HTTPMove (#6594)
  CHANGES/6594.feature
  aiohttp/web.py
  aiohttp/web_exceptions.py
  aiohttp/web_middlewares.py
Labels: bot:chronographer:provided

#5854 Allow timeout to work when reading with nowait
  CHANGES/5854.bugfix
  aiohttp/helpers.py
  aiohttp/streams.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.9

#7292 Allow timeout to work when reading with nowait (#5854)
  CHANGES/5854.bugfix
  aiohttp/helpers.py
  aiohttp/streams.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#5934 Add flake8-requirements
  .pre-commit-config.yaml
  CHANGES/5934.misc
  setup.cfg
  tests/__init__.py
  tests/conftest.py
  tests/test_circular_imports.py
  tests/test_connector.py
  tests/test_run_app.py
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.9

#7293 Add flake8-requirements (#5934)
  .pre-commit-config.yaml
  CHANGES/5934.misc
  setup.cfg
  tests/__init__.py
  tests/conftest.py
  tests/test_circular_imports.py
  tests/test_connector.py
  tests/test_run_app.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided

#7284 Minor refactor of setting Content-Length in body
  aiohttp/web_response.py
  docs/web_reference.rst
  tests/test_web_response.py
Labels: bot:chronographer:skip, backport-3.9

#7107 Remove deprecated parts of AioHTTPTestCase
  CHANGES/7107.removal
  aiohttp/test_utils.py
  docs/testing.rst
  tests/test_loop.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided, backport:skip

#7296 Make AioHTTPTestCase.get_application() abstract
  aiohttp/test_utils.py
  tests/test_test_utils.py
Labels: bot:chronographer:skip, backport:skip

#6879 Update third_party.rst
  docs/third_party.rst
Labels: bot:chronographer:skip

#7298 Fix SSLContext being unknown
  aiohttp/client.py
Labels: bot:chronographer:skip, backport-3.9

#7302 Make max 32-bit timestamp aware
  CHANGES/7302.bugfix
  aiohttp/cookiejar.py
Labels: bot:chronographer:provided, backport-3.9
