Repository aio-libs/aiohttp, pull requests merged in 2023-09, with the labels that each got.

#7577 CookieJar - return 'best-match' and not LIFO
  CHANGES/7577.bugfix
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7586 Remove chardet/charset-normalizer.
  .mypy.ini
  CHANGES/7561.feature
  CONTRIBUTORS.txt
  README.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  docs/_snippets/cchardet-unmaintained-admonition.rst
  docs/client_advanced.rst
  docs/client_reference.rst
  docs/glossary.rst
  docs/index.rst
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/test_client_response.py
Labels: bot:chronographer:provided

#7587 CookieJar - return 'best-match' and not LIFO (#7577)
  CHANGES/7577.bugfix
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#7588 CookieJar - return 'best-match' and not LIFO (#7577)
  CHANGES/7577.bugfix
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#7589 Remove chardet/charset-normalizer.
  CHANGES/7561.feature
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_reqrep.py
  docs/client_advanced.rst
  docs/client_reference.rst
  docs/index.rst
  setup.cfg
  tests/test_client_response.py
Labels: bot:chronographer:provided

#7364 Strip trailing dot from FQDNs in Host and TLS
  CHANGES/3636.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  tests/conftest.py
  tests/test_client_request.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.9

#7612 Resolve last 3.12 issues
  setup.cfg
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.9

#7611 Support brotlicffi alternatively to brotli
  .mypy.ini
  CHANGES/7611.feature
  aiohttp/compression_utils.py
  docs/client_quickstart.rst
  docs/glossary.rst
  docs/index.rst
  docs/spelling_wordlist.txt
  requirements/runtime-deps.in
  setup.cfg
  tests/test_http_parser.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.9

#7620 [3.9] Support brotlicffi alternatively to brotli (#7611)
  .mypy.ini
  CHANGES/7611.feature
  aiohttp/compression_utils.py
  docs/client_quickstart.rst
  docs/glossary.rst
  docs/index.rst
  docs/spelling_wordlist.txt
  requirements/runtime-deps.in
  setup.cfg
  tests/test_http_parser.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#7623 Fix llhttp caching in tests
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.9

#7622 Add a test case for 7599
  tests/test_client_functional.py
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.9

#7601 Strip trailing dot from FQDNs in Host and TLS context
  CHANGES/3636.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  tests/conftest.py
  tests/test_client_request.py
  tests/test_connector.py
Labels: bot:chronographer:provided
