Repository aio-libs/aiohttp, pull requests merged in 2023-02, with the labels that each got.

#7190 Adjust type annotations making print arg optional in web.run_app()
  .pre-commit-config.yaml
  CHANGES/3690.misc
  CONTRIBUTORS.txt
  aiohttp/web.py
Labels: bot:chronographer:provided

#7180 Fix ConnectionResetError not being raised when the transport is closed
  CHANGES/7180.bugfix
  CONTRIBUTORS.txt
  aiohttp/base_protocol.py
  aiohttp/http_writer.py
  tests/test_base_protocol.py
  tests/test_client_proto.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7198 Fix ConnectionResetError not being raised when the transport is close…
  CHANGES/7180.bugfix
  CONTRIBUTORS.txt
  aiohttp/base_protocol.py
  aiohttp/http_writer.py
  tests/test_base_protocol.py
  tests/test_client_proto.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided

#7201 Drop unused mypy-extensions
  requirements/constraints.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.9

#7200 [3.8] Fix CI (#7143)
  .github/workflows/ci.yml
  .mypy.ini
  aiohttp/helpers.py
  tests/test_client_request.py
  tests/test_streams.py
  tests/test_web_app.py
Labels: bot:chronographer:skip

#7191 Make tests pass after year 2039
  CHANGES/7191.misc
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.9

#7199 Fix ConnectionResetError not being raised when the transport is close…
  CHANGES/7180.bugfix
  aiohttp/base_protocol.py
  aiohttp/http_writer.py
  tests/test_base_protocol.py
  tests/test_client_proto.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided

#7188 Add a graceful shutdown period to allow tasks to complete.
  CHANGES/7188.feature
  aiohttp/test_utils.py
  aiohttp/web_fileresponse.py
  aiohttp/web_runner.py
  docs/web_advanced.rst
  docs/web_reference.rst
  tests/test_run_app.py
Labels: bot:chronographer:provided, backport-3.9

#7150 client: fix upload timeouts with sock_read set
  CHANGES/7149.bugfix
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
  tests/test_client_proto.py
Labels: bot:chronographer:provided

#7205 Add a graceful shutdown period to allow tasks to complete. (#7188)
  CHANGES/7188.feature
  aiohttp/test_utils.py
  aiohttp/web_fileresponse.py
  aiohttp/web_runner.py
  docs/web_advanced.rst
  docs/web_reference.rst
  tests/test_run_app.py
Labels: bot:chronographer:provided

#7206 client: fix upload timeouts with sock_read set (#7150)
  CHANGES/7149.bugfix
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
  tests/test_client_proto.py
Labels: bot:chronographer:provided

#7211 Backport cleanup_changes.py
  tools/cleanup_changes.py
Labels: bot:chronographer:skip

#7213 Increase `base_protocol` coverage
  CHANGES/7213.misc
  aiohttp/__init__.py
  docs/contributing.rst
  tests/test_base_protocol.py
Labels: bot:chronographer:provided

#7219 Remove unused loop in CookieJar
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:skip, backport-3.9

#7221 Test if CookieJar pickle format breaks
  tests/test_cookiejar.py
Labels: bot:chronographer:skip, backport-3.9

#7227 Test if CookieJar pickle format breaks (#7221)
  tests/test_cookiejar.py
Labels: bot:chronographer:skip
