Repository aio-libs/aiohttp, pull requests merged in 2023-12, with the labels that each got.

#7924 Add pychess.org to powered_by.rst
  docs/powered_by.rst
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7930 Use .coveragerc for TYPE_CHECKING conditions
  .coveragerc
  aiohttp/__init__.py
  aiohttp/abc.py
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/typedefs.py
  aiohttp/web_app.py
  aiohttp/web_fileresponse.py
  aiohttp/web_middlewares.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7927 Pin proxy.py to 2.4.4rc4 for testing
  requirements/constraints.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
Labels: bot:chronographer:skip

#7936 Patchback 3.10 #7818
  CHANGES/7801.feature
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_proto.py
  docs/client_reference.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#7937 Revert time-machine back to freezegun
  requirements/constraints.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/test_cookiejar.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7942 added server_hostname param to ws_connect method
  CHANGES/7941.feature
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.10

#7961 Add reminder to use 'fixes' in PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7978 Fix websocket connection leak
  CHANGES/7978.bugfix
  aiohttp/web_ws.py
  docs/web_reference.rst
  tests/test_web_websocket.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#7980 Fix websocket connection leak (#7978)
  CHANGES/7978.bugfix
  aiohttp/web_ws.py
  docs/web_reference.rst
  tests/test_web_websocket.py
Labels: bot:chronographer:provided

#7979 Fix websocket connection leak (#7978)
  CHANGES/7978.bugfix
  aiohttp/web_ws.py
  docs/web_reference.rst
  tests/test_web_websocket.py
Labels: bot:chronographer:provided
