Repository aio-libs/aiohttp, pull requests merged in 2023-03, with the labels that each got.

#7223 refactor: Extract zlib-related logic into a single module
  aiohttp/client_reqrep.py
  aiohttp/compression_utils.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  aiohttp/multipart.py
  aiohttp/web_response.py
  tests/test_http_parser.py
Labels: bot:chronographer:skip, backport-3.9

#7131 Support using netrc for non-proxy HTTP credentials
  CHANGES/7131.feature
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  docs/client_reference.rst
  docs/glossary.rst
  tests/conftest.py
  tests/test_client_request.py
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.9

#7244 Fix: Websocket client handshake with inexact Connection header
  CONTRIBUTORS.txt
  aiohttp/client.py
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.9
