Repository aio-libs/aiohttp, pull requests merged in 2023-04, with the labels that each got.

#7249 Support using netrc for non-proxy HTTP credentials
  CHANGES/7131.feature
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  docs/client_reference.rst
  docs/glossary.rst
  tests/conftest.py
  tests/test_client_request.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#7250 refactor: Extract zlib-related logic into a single module (#7223)
  aiohttp/client_reqrep.py
  aiohttp/compression_utils.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  aiohttp/multipart.py
  aiohttp/web_response.py
  tests/test_http_parser.py
Labels: bot:chronographer:skip

#7235 Update documentation: complete client docs for honoring proxy env vars
  CHANGES/7325.doc
  docs/client_advanced.rst
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.9

#7240 Reduce access log overhead when logging is disabled
  CHANGES/7240.feature
  aiohttp/web_log.py
  tests/test_web_log.py
Labels: bot:chronographer:provided, backport-3.9

#6559 Support setting response header size limits
  CHANGES/2304.feature
  aiohttp/client.py
  aiohttp/client_proto.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.9

#7264 Patchback/backports/3.9/ecd9c72697ca1529e7cae4693775612987a2a6d2/pr 6559
  CHANGES/2304.feature
  aiohttp/client.py
  aiohttp/client_proto.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#7266 hint WebSocketWriter methods pong/ping/close to allow bytes or str
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip, backport-3.9
