Repository aio-libs/aiohttp, pull requests merged in 2023-08, with the labels that each got.

#7469 Regenerate pip-tools managed lockfiles
  requirements/base.txt
  requirements/constraints.txt
  requirements/cython.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
  requirements/lint.txt
  requirements/multidict.txt
  requirements/runtime-deps.txt
  requirements/test.txt
  requirements/typing-extensions.txt
Labels: bot:chronographer:skip

#7454 Ignore new deprecation message from setuptools.
  setup.cfg
  tests/test_circular_imports.py
Labels: bot:chronographer:skip, backport-3.8, backport-3.9

#7480 Fix error pointer on linebreaks
  CHANGES/7468.bugfix
  aiohttp/_http_parser.pyx
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7484 Increase stacklevel for UserWarning about AppKey usage
  CONTRIBUTORS.txt
  aiohttp/web_app.py
  tests/test_web_app.py
Labels: bot:chronographer:skip, backport-3.9

#7488 Increase stacklevel for DeprecationWarning about subclassing Application
  aiohttp/web_app.py
Labels: bot:chronographer:skip, backport-3.9

#7490 Use lenient headers for response parser
  .github/workflows/ci-cd.yml
  CHANGES/7490.feature
  aiohttp/_http_parser.pyx
  docs/index.rst
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7491 Use lenient headers for response parser (#7490)
  .github/workflows/ci-cd.yml
  CHANGES/7490.feature
  Makefile
  aiohttp/_http_parser.pyx
  docs/index.rst
  setup.cfg
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7492 Use lenient headers for response parser (#7490)
  CHANGES/7490.feature
  aiohttp/_http_parser.pyx
  docs/index.rst
  setup.cfg
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#7503 Skip uvloop install on Python 3.12
  requirements/base.in
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#7505 Ignore dateutil DeprecationWarning [3.12]
  setup.cfg
Labels: bot:chronographer:skip

#7507 Skip uvloop install on Python 3.12 (#7503)
  requirements/base.in
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#7518 Fix GunicornWebWorker max_requests_jitter not work
  CHANGES/7518.bugfix
  aiohttp/worker.py
  tests/test_worker.py
Labels: bot:chronographer:provided, backport-3.8, backport-3.9

#7536 Remove pydantic pin
  requirements/broken-projects.in
Labels: bot:chronographer:skip

#7540 Delay codecov
  .codecov.yml
Labels: bot:chronographer:skip

#7541 Support passing a custom server name parameter on HTTPS connection
  CHANGES/7114.feature
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.9

#7543 Support passing a custom server name parameter on HTTPS connection
  CHANGES/7114.feature
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#7549 Remove deprecated child watcher
  aiohttp/test_utils.py
Labels: bot:chronographer:skip, backport-3.9

#7554 [PR #5835 backport][3.9] Fix(doc): ClientResponse.release
  CHANGES/5836.doc
  docs/client_reference.rst
Labels: bot:chronographer:provided

#7557 [Backport][3.9] Make access log use local time with timezone
  CHANGES/3853.feature
  aiohttp/web_log.py
  tests/test_web_log.py
Labels: bot:chronographer:provided

#7556 Only install async-timeout for Python < 3.11
  CHANGES/7502.feature
  aiohttp/client_ws.py
  aiohttp/helpers.py
  aiohttp/web_ws.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/test_client_ws_functional.py
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.9

#7558 [Backport][3.9] Only install async-timeout for Python < 3.11 (#7556)
  CHANGES/7502.feature
  aiohttp/client_ws.py
  aiohttp/helpers.py
  aiohttp/web_ws.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/test_client_ws_functional.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#7561 Remove chardet/charset-normalizer. Add fallback_charset_resolver ClientSession parameter.
  .mypy.ini
  CHANGES/7561.feature
  CONTRIBUTORS.txt
  README.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  docs/_snippets/cchardet-unmaintained-admonition.rst
  docs/client_advanced.rst
  docs/client_reference.rst
  docs/glossary.rst
  docs/index.rst
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/test_client_response.py
Labels: bot:chronographer:provided, backport-3.9
