Repository aio-libs/aiohttp, pull requests merged in 2024-10, with the labels that each got.

#9363 Fix issue 6652: Raise `aiohttp.ServerFingerprintMismatch` exception o…
  CHANGES/6652.bugfix
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#9359 replace blockdiag with graphviz in docs
  .readthedocs.yml
  CHANGES/9359.contrib.rst
  docs/conf.py
  docs/tracing_reference.rst
  requirements/broken-projects.in
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.in
  requirements/doc.txt
  requirements/test.in
Labels: documentation, bot:chronographer:provided, backport-3.11

#9371 Reduce indent in connector tests
  tests/test_connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9373 [PR #9371/c25099c backport][3.10] Reduce indent in connector tests
  tests/test_connector.py
Labels: bot:chronographer:skip

#9374 [PR #9371/c25099c backport][3.11] Reduce indent in connector tests
  tests/test_connector.py
Labels: bot:chronographer:skip

#9372 Only prepare proxy headers for a request if a proxy is set
  aiohttp/client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9368 Avoid using the proxy headers in the ConnectionKey if no proxy is in use
  CHANGES/9368.bugfix.rst
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9367 Speed up handling auth in urls
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9366 Small speed up to update_headers
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9375 [PR #9359/a9ac5e2 backport][3.11] replace blockdiag with graphviz in docs
  .readthedocs.yml
  CHANGES/9359.contrib.rst
  docs/conf.py
  docs/tracing_reference.rst
  requirements/broken-projects.in
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.in
  requirements/doc.txt
  requirements/test.in
Labels: bot:chronographer:provided

#9377 [PR #9372/0416d28 backport][3.11] Only prepare proxy headers for a request if a proxy is set
  aiohttp/client.py
Labels: bot:chronographer:skip

#9376 [PR #9372/0416d28 backport][3.10] Only prepare proxy headers for a request if a proxy is set
  aiohttp/client.py
Labels: bot:chronographer:skip

#9384 [PR #9365/d684195b backport][3.11] Speed up the ConnectionKey
  CHANGES/9365.breaking.rst
  aiohttp/client_reqrep.py
  aiohttp/connector.py
Labels: bot:chronographer:provided

#9385 Fix missing text in #9368 changelog message
  CHANGES/9368.bugfix.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9383 [PR #9366/43deadb2 backport][3.10] Small speed up to update_headers
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#9386 Small speed up to starting client requests
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9331 [PR #9207/970c5d9 backport][3.11] add proxy and proxy_auth variables to ClientSession.__init__
  CHANGES/9207.feature.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  docs/client_advanced.rst
  tests/test_client_session.py
Labels: bot:chronographer:provided

#7368 Fixed failure to try next host after single-host connection timeout
  CHANGES/7342.breaking.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/connector.py
  docs/client_quickstart.rst
  docs/client_reference.rst
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9390 [PR #7368/8a8913b backport][3.10] Fixed failure to try next host after single-host connection timeout
  CHANGES/7342.breaking.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/connector.py
  docs/client_quickstart.rst
  docs/client_reference.rst
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#9391 [PR #7368/8a8913b backport][3.11] Fixed failure to try next host after single-host connection timeout
  CHANGES/7342.breaking.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/connector.py
  docs/client_quickstart.rst
  docs/client_reference.rst
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#9398 Widen `trace_request_ctx` type
  CHANGES/9397.bugfix.rst
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9405 Only create the connection closed exception once
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9407 Add __slots__ to stream classes
  CHANGES/9407.misc.rst
  aiohttp/streams.py
Labels: bot:chronographer:provided, backport-3.11

#9406 Add __slots__ to timer helpers
  CHANGES/9406.misc.rst
  aiohttp/helpers.py
  pyproject.toml
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9409 [PR #9405/b96b01b backport][3.11] Only create the connection closed exception once
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#9411 [PR #9406/24b0e6f backport][3.10] Add __slots__ to timer helpers
  CHANGES/9406.misc.rst
  aiohttp/helpers.py
  pyproject.toml
Labels: bot:chronographer:provided

#9410 [PR #9405/b96b01b backport][3.10] Only create the connection closed exception once
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#9412 [PR #9406/24b0e6f backport][3.11] Add __slots__ to timer helpers
  CHANGES/9406.misc.rst
  aiohttp/helpers.py
  pyproject.toml
Labels: bot:chronographer:provided

#9416 Do not merge
  CHANGES.rst
  CHANGES/7342.breaking.rst
  CHANGES/9342.misc.rst
  CHANGES/9368.bugfix.rst
  CHANGES/9397.bugfix.rst
  CHANGES/9406.misc.rst
Labels: backport:skip

#9417 [3.11] Fix duplicate cancelling check in TimerContext due to merge conflict resolution error
  aiohttp/helpers.py
Labels: bot:chronographer:skip, backport:skip

#9396 Disabling retry_persistent_connection in Tests
  CHANGES/9141.misc.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/test_utils.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided, backport-3.11

#9418 Add xfail test for #9336
  tests/test_client_session.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9423 Patchback/backports/3.11/6d8562d8420b3e464877b941e04663fdac29a54c/pr 9396
  CHANGES/9141.misc.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/test_utils.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided

#9394 Migrate to using propcache for property caching
  .github/ISSUE_TEMPLATE/bug_report.yml
  .gitignore
  CHANGES/9394.packaging.rst
  aiohttp/_helpers.pyi
  aiohttp/_helpers.pyx
  aiohttp/helpers.py
  docs/conf.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  setup.cfg
  setup.py
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.11

#9434 [PR #9394/e9edd04 backport][3.11] Migrate to using propcache for property caching
  .gitignore
  CHANGES/9394.packaging.rst
  aiohttp/_helpers.pyi
  aiohttp/_helpers.pyx
  aiohttp/helpers.py
  docs/conf.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  setup.cfg
  setup.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#9448 Improve performance of fetching the content-length for web responses
  aiohttp/helpers.py
  aiohttp/web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9451 Fix AsyncResolver swallowing the error message
  CHANGES/9451.bugfix.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9452 [PR #9451/216e082 backport][3.10] Fix AsyncResolver swallowing the error message
  CHANGES/9451.bugfix.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided

#9453 [PR #9451/216e082 backport][3.11] Fix AsyncResolver swallowing the error message
  CHANGES/9451.bugfix.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided

#9455 [3.11] Fix AsyncResolver query fallback swallowing the error message
  CHANGES/9455.bugfix.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.10

#9454 Simplify DNS throttle implementation
  CHANGES/9454.misc.rst
  aiohttp/connector.py
  aiohttp/locks.py
  tests/test_connector.py
  tests/test_locks.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9457 [PR #9454/b20908e backport][3.10] Simplify DNS throttle implementation
  CHANGES/9454.misc.rst
  aiohttp/connector.py
  aiohttp/locks.py
  tests/test_connector.py
  tests/test_locks.py
Labels: bot:chronographer:provided

#8456 Add ClientConnectorDNSError for differentiating DNS errors from others
  CHANGES/8455.feature.rst
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9458 [PR #9454/b20908e backport][3.11] Simplify DNS throttle implementation
  CHANGES/9454.misc.rst
  aiohttp/connector.py
  aiohttp/locks.py
  tests/test_connector.py
  tests/test_locks.py
Labels: bot:chronographer:provided

#9459 [PR #8456/b09d7cc backport][3.10] Add ClientConnectorDNSError for differentiating DNS errors from others
  CHANGES/8455.feature.rst
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9460 [PR #8456/b09d7cc backport][3.11] Add ClientConnectorDNSError for differentiating DNS errors from others
  CHANGES/8455.feature.rst
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9463 Do not merge
  CHANGES.rst
  CHANGES/8455.feature.rst
  CHANGES/9451.bugfix.rst
  CHANGES/9454.misc.rst
Labels: backport:skip

#9467 Small performance improvement to handling redirects
  aiohttp/client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9466 Improve performance of default auth
  CHANGES/9466.feature.rst
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.11

#9465 Small cleanups to pending changelog messages
  CHANGES/9079.misc.rst
Labels: bot:chronographer:skip, backport-3.11

#9468 [PR #9466/03851d1 backport][3.11] Improve performance of default auth
  CHANGES/9466.feature.rst
  aiohttp/client.py
Labels: bot:chronographer:provided

#9470 Avoid calling update_cookies when there are no cookies
  CHANGES/9470.misc.rst
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9477 Speed up matching the host header when updating client headers
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9476 [PR #9312/7d1056b backport][3.11] Replace aioredis with valkey in examples
  .github/codeql.yml
  examples/background_tasks.py
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.in
  requirements/lint.txt
Labels: bot:chronographer:skip

#9485 Avoid passing client writer to response when already finished
  CHANGES/9485.misc.rst
  aiohttp/client_reqrep.py
  tests/test_client_request.py
  tests/test_client_response.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9499 Improve performance of creating the ConnectionKey
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.11

#9498 Improve performance of WebSocketReader
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9502 [PR #9498/13dc020 backport][3.11] Improve performance of WebSocketReader
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip

#9501 [PR #9498/13dc020 backport][3.10] Improve performance of WebSocketReader
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip

#9523 Test typing final round
  tests/conftest.py
  tests/test_client_connection.py
  tests/test_client_fingerprint.py
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_client_ws.py
  tests/test_loop.py
  tests/test_payload.py
  tests/test_pytest_plugin.py
  tests/test_resolver.py
  tests/test_run_app.py
  tests/test_web_app.py
  tests/test_web_cli.py
  tests/test_web_sendfile.py
  tests/test_websocket_handshake.py
Labels: bot:chronographer:skip, backport:skip

#9534 Add codspeed benchmarks
  .github/workflows/ci-cd.yml
  .mypy.ini
  requirements/lint.in
  requirements/lint.txt
  requirements/test.in
  requirements/test.txt
  tests/test_benchmarks_client_request.py
  tests/test_benchmarks_cookiejar.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9537 [PR #9534/5a79c0f3 backport][3.10] Add codspeed benchmarks
  .github/workflows/ci-cd.yml
  .mypy.ini
  requirements/lint.in
  requirements/lint.txt
  requirements/test.in
  requirements/test.txt
  tests/test_benchmarks_client_request.py
  tests/test_benchmarks_cookiejar.py
Labels: bot:chronographer:skip

#9538 Add WebSocket read and send benchmarks for the http writer
  .mypy.ini
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#7319 Refactor WSMessage to use tagged unions
  CHANGES/7319.breaking.rst
  CHANGES/7319.feature.rst
  HISTORY.rst
  aiohttp/client_ws.py
  aiohttp/http_websocket.py
  aiohttp/web_ws.py
  docs/spelling_wordlist.txt
  docs/websocket_utilities.rst
  examples/client_ws.py
  examples/server_simple.py
  examples/web_ws.py
  tests/autobahn/client/client.py
  tests/autobahn/server/server.py
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
  tests/test_websocket_parser.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided, backport:skip

#9542 Separate `aiohttp.http_websocket` into multiple files
  CHANGES/9542.packaging.rst
  Makefile
  aiohttp/_websocket/__init__.py
  aiohttp/_websocket/helpers.py
  aiohttp/_websocket/mask.pyx
  aiohttp/_websocket/models.py
  aiohttp/_websocket/reader.py
  aiohttp/_websocket/writer.py
  aiohttp/http_websocket.py
  setup.py
  tests/test_websocket_parser.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided, backport-3.11

#9545 Separate `aiohttp.http_websocket` into multiple files (#9542)
  CHANGES/9542.packaging.rst
  Makefile
  aiohttp/_websocket/__init__.py
  aiohttp/_websocket/helpers.py
  aiohttp/_websocket/mask.pyx
  aiohttp/_websocket/models.py
  aiohttp/_websocket/reader.py
  aiohttp/_websocket/writer.py
  aiohttp/http_websocket.py
  setup.py
  tests/test_websocket_parser.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided

#9543 Add a PXD only Cython extension for the WebSocket reader to improve performance
  CHANGES/9543.feature.rst
  Makefile
  aiohttp/_websocket/mask.pxd
  aiohttp/_websocket/mask.pyx
  aiohttp/_websocket/reader.py
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_c.py
  aiohttp/_websocket/reader_py.py
  setup.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided, backport-3.11

#9548 [PR #9543/6ae2f05 backport][3.11] Add a PXD only Cython extension for the WebSocket reader to improve performance
  CHANGES/9543.feature.rst
  Makefile
  aiohttp/_websocket/mask.pxd
  aiohttp/_websocket/mask.pyx
  aiohttp/_websocket/reader.py
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_c.py
  aiohttp/_websocket/reader_py.py
  setup.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#9549 Simplify WebSocket writer
  aiohttp/_websocket/writer.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9550 [PR #9549/be5fed2 backport][3.10] Simplify WebSocket writer
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip

#9551 [PR #9549/be5fed2 backport][3.11] Simplify WebSocket writer
  aiohttp/_websocket/writer.py
Labels: bot:chronographer:skip

#9552 Add `aiohttp._websocket` to `packages` in `setup.cfg`
  CHANGES/9552.packaging.rst
  setup.cfg
Labels: bot:chronographer:provided, backport-3.11

#9554 Optimize WebSocketReader for 2 byte length case
  CHANGES/9554.feature.rst
  aiohttp/_websocket/helpers.py
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
Labels: bot:chronographer:provided, backport-3.11

#9556 Fix Cython `WebSocketReader` byte signedness
  CHANGES/9556.feature.rst
  aiohttp/_websocket/reader_c.pxd
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided, backport-3.11

#9557 [PR #9556/df0c461 backport][3.11] Fix Cython `WebSocketReader` byte signedness
  CHANGES/9556.feature.rst
  aiohttp/_websocket/reader_c.pxd
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#9559 Add benchmarks for sending masked WebSocket messages
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9558 Fix refactoring error from moving WebSocket mask
  CHANGES/9558.feature.rst
  aiohttp/_websocket/helpers.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided, backport-3.11

#9566 Refactor WebSocketWriter to remove high level protocol functions
  aiohttp/_websocket/writer.py
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:skip, backport-3.11

#9443 Fix handling of redirects with authentication
  CHANGES/9436.bugfix.rst
  aiohttp/client.py
  docs/client_advanced.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9570 [PR #9443/06b2398 backport][3.10] Fix handling of redirects with authentication
  CHANGES/9436.bugfix.rst
  aiohttp/client.py
  docs/client_advanced.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9571 [PR #9443/06b2398 backport][3.11] Fix handling of redirects with authentication
  CHANGES/9436.bugfix.rst
  aiohttp/client.py
  docs/client_advanced.rst
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9530 Allow URLs with paths that end with `/` as base_url in ClientSession
  CHANGES/9530.feature.rst
  aiohttp/client.py
  docs/client_reference.rst
  tests/test_client_session.py
Labels: bot:chronographer:provided, backport-3.11

#9569 [PR #9566/22f0831 backport][3.11] Refactor WebSocketWriter to remove high level protocol functions
  aiohttp/_websocket/writer.py
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:skip

#9572 Add support for adjusting the server WebSocket writer limit
  CHANGES/9572.feature.rst
  aiohttp/web_ws.py
  docs/web_reference.rst
  tests/test_web_websocket.py
Labels: bot:chronographer:provided, backport-3.11

#9573 [PR #9572/e36c5f0 backport][3.11] Add support for adjusting the server WebSocket writer limit
  CHANGES/9572.feature.rst
  aiohttp/web_ws.py
  docs/web_reference.rst
  tests/test_web_websocket.py
Labels: bot:chronographer:provided

#9575 Switch to using `URL.host_port_subcomponent` in `yarl` for the client host header
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.11

#9577 Cleanup changelog messages for 3.11
  CHANGES/3945.breaking.rst
  CHANGES/6652.bugfix
  CHANGES/6652.bugfix.rst
  CHANGES/8612.feature.rst
  CHANGES/8966.feature.rst
  CHANGES/9207.feature.rst
Labels: bot:chronographer:provided, backport-3.11

#9580 Release 3.11.0b0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9583 [PR #9530/f3a3f60 backport][3.11] Allow URLs with paths that end with / as base_url in ClientSession
  CHANGES/9530.feature.rst
  aiohttp/client.py
  docs/client_reference.rst
  tests/test_client_session.py
Labels: bot:chronographer:provided

#9497 Add missing docs for timeout parameter in WebSocketResponse.__init__()
  docs/web_reference.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9588 Merge HISTORY into CHANGES (#9581)
  CHANGES.rst
  HISTORY.rst
  docs/changes.rst
Labels: bot:chronographer:skip

#9589 [PR #7942/0b71e1c backport][3.11] added server_hostname param to ws_connect method
  CHANGES/7941.feature
  aiohttp/client.py
Labels: bot:chronographer:provided

#9585 Add client request creation benchmarks for headers and cookies
  tests/test_benchmarks_client_request.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9593 Add test coverage for perserving the coded cookie value
  tests/test_client_request.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9595 Upgrade codspeed to 3.0.0
  .mypy.ini
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/test.txt
  tests/test_benchmarks_client_request.py
  tests/test_benchmarks_cookiejar.py
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport-3.11
