Repository aio-libs/aiohttp, pull requests merged in 2024-09, with the labels that each got.

#8965 Deprecate obsolete timeout in ClientSession.ws_connect() (#3946)
  CHANGES/3945.deprecation.rst
  CHANGES/8612.feature.rst
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_ws.py
  docs/client_reference.rst
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided

#7168 Fix `test_utils.make_mocked_request` behaviour for empty payload
  CHANGES/7167.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/test_utils.py
  tests/test_test_utils.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8908 Fix CancelledError stopping other cleanup contexts completing
  CHANGES/8908.bugfix.rst
  aiohttp/web_app.py
  docs/web_advanced.rst
  tests/test_web_app.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8951 Avoid logging exception from run_app() that is also raised
  CHANGES/6807.bugfix.rst
  aiohttp/web.py
  tests/test_run_app.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8966 Fix auth reset logic during redirects to different origin when _base_url set
  CHANGES/8966.feature.rst
  aiohttp/client.py
  docs/client_reference.rst
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport-3.11

#8972 Fix CancelledError stopping other cleanup contexts completing (#8908)
  CHANGES/8908.bugfix.rst
  aiohttp/web_app.py
  docs/web_advanced.rst
  tests/test_web_app.py
Labels: bot:chronographer:skip

#8973 Fix CancelledError stopping other cleanup contexts completing (#8908)
  CHANGES/8908.bugfix.rst
  aiohttp/web_app.py
  docs/web_advanced.rst
  tests/test_web_app.py
Labels: bot:chronographer:skip

#8974 Avoid logging exception from run_app() that is also raised (#8951)
  CHANGES/6807.bugfix.rst
  aiohttp/web.py
  tests/test_run_app.py
Labels: bot:chronographer:skip

#8975 Avoid logging exception from run_app() that is also raised (#8951)
  CHANGES/6807.bugfix.rst
  aiohttp/web.py
  tests/test_run_app.py
Labels: bot:chronographer:skip

#8933 Small cleanups to the websocket frame sender
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8967 Fix resolve_host "Task was destroyed but it is pending" errors
  CHANGES/8967.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8968 List specific timeouts for each exception
  CHANGES/8968.doc.rst
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8980 Fix resolve_host "Task was destroyed but it is pending" errors (#8967)
  CHANGES/8967.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:skip

#8987 Move ContentDisposition in reference docs
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8991 Update ClientSession reference
  CHANGES/8991.doc.rst
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8990 Fix changing scheme/host in Response.clone() for absolute URLs
  CHANGES/8990.bugfix.rst
  aiohttp/web_request.py
  tests/test_web_request.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9002 Fix cancelled payload send leading to hung connection (#8992)
  CHANGES/8992.bugfix.rst
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9003 Fix cancelled payload send leading to hung connection (#8992)
  CHANGES/8992.bugfix.rst
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9004 Fix test_client_session_timeout_zero to not use internet connection
  CHANGES/9004.packaging.rst
  tests/conftest.py
  tests/test_client_session.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9006 Add flake8-no-implicit-concat (#7731)
  .pre-commit-config.yaml
  CHANGES/7731.misc.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/formdata.py
  aiohttp/helpers.py
  aiohttp/http_websocket.py
  aiohttp/multipart.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/web.py
  aiohttp/web_app.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  setup.cfg
  tests/test_client_exceptions.py
  tests/test_client_functional.py
  tests/test_client_proto.py
  tests/test_helpers.py
  tests/test_http_exceptions.py
  tests/test_http_parser.py
  tests/test_http_writer.py
  tests/test_multipart.py
  tests/test_multipart_helpers.py
  tests/test_urldispatch.py
  tests/test_web_cli.py
  tests/test_web_functional.py
  tests/test_web_request.py
  tests/test_web_websocket_functional.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#9007 Fix test_client_session_timeout_zero to not use internet connection (#9004)
  CHANGES/9004.packaging.rst
  tests/conftest.py
  tests/test_client_session.py
Labels: bot:chronographer:provided

#9008 Fix test_client_session_timeout_zero to not use internet connection (#9004)
  CHANGES/9004.packaging.rst
  tests/conftest.py
  tests/test_client_session.py
Labels: bot:chronographer:provided

#8998 Fix resource reuse with regex paths
  CHANGES/8998.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9029 Fix SSLContext creation in the TCPConnector with multiple loops
  aiohttp/connector.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9031 Avoid tracing overhead in http_writer when there are no traces
  CHANGES/9031.misc.rst
  aiohttp/client_reqrep.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9032 Fix Link-Local IPv6 Flags in the Resolver
  CHANGES/9032.bugfix.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9044 Add missing changelog entry for #9029
  CHANGES/9029.bugfix.rst
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9043 [PR #9029/466448c backport][3.11] Fix SSLContext creation in the TCPConnector with multiple loops
  aiohttp/connector.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:skip

#9048 [PR #9032/c693a816 backport][3.10] Fix Link-Local IPv6 Flags in the Resolver
  CHANGES/9032.bugfix.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided

#9042 [PR #9029/466448c backport][3.10] Fix SSLContext creation in the TCPConnector with multiple loops
  aiohttp/connector.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:skip

#9054 Sync reify Cython implementation with yarl
  CHANGES/9054.misc.rst
  aiohttp/_helpers.pyx
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9053 Explain the importance of reproducers
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9055 Add xfail test for issue #5180
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9065 Add coverage for combining an existing query string with params
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9066 [PR #9065/b6196e7 backport][3.10] Add coverage for combining an existing query string with params
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#9067 [PR #9065/b6196e7 backport][3.11] Add coverage for combining an existing query string with params
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#9034 Drop async-timeout from list of dependencies
  README.rst
  docs/index.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9069 [3.11] Drop async-timeout from dependencies
  README.rst
  docs/index.rst
Labels: bot:chronographer:skip, backport-3.10

#9072 Bump yarl to 1.11.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9074 [PR #9072/7fb1631 backport][3.11] Bump yarl to 1.11.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#9068 Use URL.extend_query to add params in `ClientRequest`
  CHANGES/9068.misc.rst
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9071 Add tests for websocket close
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9073 [PR #9072/7fb1631 backport][3.10] Bump yarl to 1.11.0
  aiohttp/web_urldispatcher.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#9078 [PR #9068/841d00e backport][3.11] Use URL.extend_query to add params in `ClientRequest`
  CHANGES/9068.misc.rst
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9077 [PR #9068/841d00e backport][3.10] Use URL.extend_query to add params in `ClientRequest`
  CHANGES/9068.misc.rst
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#8564 Use Query typedef from yarl for params
  CHANGES/8564.feature.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/typedefs.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9079 Bump yarl requirement to >=1.11.0
  CHANGES/9079.misc.rst
  requirements/runtime-deps.in
  setup.cfg
Labels: bot:chronographer:provided, backport-3.11

#9082 [PR #9079/7404afc backport][3.11] Bump yarl requirement to >=1.11.0
  CHANGES/9079.misc.rst
  requirements/runtime-deps.in
  setup.cfg
Labels: bot:chronographer:provided

#9083 Remove unused backwards compatibility code for old yarl versions
  aiohttp/client_reqrep.py
  aiohttp/typedefs.py
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport-3.11

#9085 [PR #9083/a6dd415 backport][3.11] Remove unused backwards compatibility code for old yarl versions
  aiohttp/client_reqrep.py
  aiohttp/typedefs.py
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#9095 Reduce overhead to check if a host is an IP Address
  CHANGES/9095.misc.rst
  aiohttp/helpers.py
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9110 Avoid compressing empty body (#9108)
  CHANGES/9108.bugfix.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10

#9098 Remove extra ``MultiDictProxy`` wrapper from ``BaseRequest.query``
  aiohttp/web_request.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#6257 Add `strategy` argument to `StreamResponse.enable_compression()` method
  CHANGES/6257.feature
  CONTRIBUTORS.txt
  aiohttp/abc.py
  aiohttp/web_response.py
  docs/web_reference.rst
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.11

#9114 Add `strategy` argument to `StreamResponse.enable_compression()` meth…
  CHANGES/6257.feature
  CONTRIBUTORS.txt
  aiohttp/abc.py
  aiohttp/web_response.py
  docs/web_reference.rst
  tests/test_web_response.py
Labels: bot:chronographer:provided

#9120 Add repr test
  tests/test_streams.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#7043 Add clarification about `GracefulExit` when using `handle_signals=True`
  CHANGES/4414.doc
  docs/web_reference.rst
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9121 Add repr() test
  tests/test_streams.py
Labels: bot:chronographer:skip, backport-3.10

#9124 Implement binding to IPv6 addresses in the pytest server fixture
  CHANGES/4650.bugfix
  aiohttp/test_utils.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided, backport-3.10

#9136 Bump idna to 3.6
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9140 Fix keepalive race condition
  CHANGES/9140.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9142 Fix keepalive race condition (#9140)
  CHANGES/9140.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#9143 Fix keepalive race condition (#9140)
  CHANGES/9140.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#9158 Cache construction of middleware handlers
  CHANGES/9158.misc.rst
  aiohttp/web_app.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9166 [PR #9158/bf022b3 backport][3.11] Cache construction of middleware handlers
  CHANGES/9158.misc.rst
  aiohttp/web_app.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided

#9182 [PR #9160 backport][3.11] Fix badly encoded charset crashing instead of falling back to detector
  CHANGES/9160.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  tests/test_client_response.py
Labels: bot:chronographer:provided

#9181 [PR #9160 backport][3.10] Fix badly encoded charset crashing instead of falling back to detector
  CHANGES/9160.bugfix
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  tests/test_client_response.py
Labels: bot:chronographer:provided

#9170 Move reversing slice of middleware apps into the cache
  CHANGES/9170.misc.rst
  aiohttp/web_app.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9173 Avoid calling response prepare hook if its empty
  CHANGES/9173.misc.rst
  aiohttp/web_request.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9186 [PR #9170/eacf2e0 backport][3.10] Move reversing slice of middleware apps into the cache
  CHANGES/9170.misc.rst
  aiohttp/web_app.py
Labels: bot:chronographer:provided

#9174 Add a cache to must_be_empty_body
  CHANGES/9174.misc.rst
  aiohttp/helpers.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9172 Improve performance of starting web requests when content length is not set
  CHANGES/9172.misc.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9137 Add and use ClientConnectionResetError
  CHANGES/9137.bugfix.rst
  aiohttp/__init__.py
  aiohttp/base_protocol.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  docs/client_reference.rst
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9194 Add and use ClientConnectionResetError (#9137)
  CHANGES/9137.bugfix.rst
  aiohttp/__init__.py
  aiohttp/base_protocol.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  docs/client_reference.rst
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided

#9195 Add and use ClientConnectionResetError (#9137)
  CHANGES/9137.bugfix.rst
  aiohttp/__init__.py
  aiohttp/base_protocol.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/http_websocket.py
  aiohttp/http_writer.py
  docs/client_reference.rst
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided

#9187 [PR #9170/eacf2e0 backport][3.11] Move reversing slice of middleware apps into the cache
  CHANGES/9170.misc.rst
  aiohttp/web_app.py
Labels: bot:chronographer:provided

#9167 Disallow newlines in reason
  CHANGES/9167.bugfix.rst
  aiohttp/web_exceptions.py
  aiohttp/web_response.py
  tests/test_web_exceptions.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9198 Disallow newlines in reason (#9167)
  CHANGES/9167.bugfix.rst
  aiohttp/web_response.py
  tests/test_web_exceptions.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#9199 Disallow newlines in reason (#9167)
  CHANGES/9167.bugfix.rst
  aiohttp/web_response.py
  tests/test_web_exceptions.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#9052 Fix lost details on HttpProcessingError
  CHANGES/9052.bugfix.rst
  aiohttp/client_proto.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9205 Fix lost details on HttpProcessingError (#9052)
  CHANGES/9052.bugfix.rst
  aiohttp/client_proto.py
Labels: bot:chronographer:provided

#9206 Fix lost details on HttpProcessingError (#9052)
  CHANGES/9052.bugfix.rst
  aiohttp/client_proto.py
Labels: bot:chronographer:provided

#9203 Implement heapq for cookie expire times
  CHANGES/9203.misc.rst
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9168 Avoid creating handler waiter until shutdown
  CHANGES/9168.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9208 [PR #9203/6e70c0a backport][3.10] Implement heapq for cookie expire times
  CHANGES/9203.misc.rst
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#9209 [PR #9203/6e70c0a backport][3.11] Implement heapq for cookie expire times
  CHANGES/9203.misc.rst
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#9175 Speed up finding the reason if its unset
  CHANGES/9175.misc.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9214 [PR #9175/756fae80 backport][3.10] Speed up finding the reason if its unset
  CHANGES/9175.misc.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#9215 Test typing round 5
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  aiohttp/web_app.py
  aiohttp/web_log.py
  requirements/constraints.txt
  requirements/dev.txt
  requirements/test.in
  requirements/test.txt
  tests/test_test_utils.py
  tests/test_web_functional.py
  tests/test_web_log.py
  tests/test_web_middleware.py
  tests/test_web_request.py
  tests/test_web_response.py
Labels: bot:chronographer:skip, backport:skip

#9217 Backport some changes from #9215
  aiohttp/pytest_plugin.py
Labels: bot:chronographer:skip, backport-3.10

#9216 Small cleanup to should_close in client_proto
  aiohttp/client_proto.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9169 Speed up starting compression
  CHANGES/9169.misc.rst
  aiohttp/web_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9064 Fix sendfile test fixture
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9219 [PR #9216/3644101 backport][3.10] Small cleanup to should_close in client_proto
  aiohttp/client_proto.py
Labels: bot:chronographer:skip

#9220 [PR #9216/3644101 backport][3.11] Small cleanup to should_close in client_proto
  aiohttp/client_proto.py
Labels: bot:chronographer:skip

#9225 [PR #9064/7b11e23 backport][3.11] Fix sendfile test fixture
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:skip

#9224 [PR #9064/7b11e23 backport][3.10] Fix sendfile test fixture
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:skip

#9221 Small cleanups to cookiejar
  aiohttp/cookiejar.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8983 Add more info to add_static() warning
  docs/web_reference.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9033 Don't listen on TCP when only path is passed
  CHANGES/9033.misc.rst
  aiohttp/web.py
  docs/web_quickstart.rst
  tests/test_web_cli.py
Labels: bot:chronographer:provided, backport-3.11

#9109 Remove None as a compress value
  CHANGES/9109.breaking.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided, backport:skip

#9018 Reject data after close message
  CHANGES/9018.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9063 Fix If-None-Match not using weak comparison
  CHANGES/9063.bugfix.rst
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9232 [PR #9200/42930b0 backport][3.11] Improve middleware performance
  CHANGES/9200.breaking.rst
  aiohttp/web_middlewares.py
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:provided

#9231 [PR #9200/42930b0 backport][3.10] Improve middleware performance
  CHANGES/9200.breaking.rst
  aiohttp/web_middlewares.py
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:provided

#9233 [PR #9033/d0e60d5 backport][3.11] Don't listen on TCP when only path is passed
  CHANGES/9033.misc.rst
  aiohttp/web.py
  docs/web_quickstart.rst
  tests/test_web_cli.py
Labels: bot:chronographer:provided

#9235 [PR #9018/63813fe backport][3.10] Reject data after close message
  CHANGES/9018.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#9236 [PR #9018/63813fe backport][3.11] Reject data after close message
  CHANGES/9018.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#9204 Significantly speed up filter_cookies
  CHANGES/9204.misc.rst
  aiohttp/cookiejar.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8977 Add Generic for TestClient.app
  CHANGES/8977.bugfix.rst
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  tests/test_client_functional.py
  tests/test_test_utils.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided, backport-3.11

#9234 Remove unnecessary string operations in update_content_encoding
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9242 Remove duplicate checks in the StreamWriter
  aiohttp/http_writer.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9240 Small cleanups to Application._handle
  aiohttp/web_app.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9246 [PR #9234/0246f2d backport][3.11] Remove unnecessary string operations in update_content_encoding
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#9247 [PR #9234/0246f2d backport][3.10] Remove unnecessary string operations in update_content_encoding
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#9245 Add Generic for TestClient.app (#8977)
  CHANGES/8977.bugfix.rst
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  tests/test_client_functional.py
  tests/test_test_utils.py
Labels: bot:chronographer:provided

#9241 Small speed up to starting web requests
  CHANGES/9241.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9250 [PR #9240/9604461 backport][3.10] Small cleanups to Application._handle
  aiohttp/web_app.py
Labels: bot:chronographer:skip

#9251 [PR #9240/9604461 backport][3.11] Small cleanups to Application._handle
  aiohttp/web_app.py
Labels: bot:chronographer:skip

#9253 [PR #9241/7e0ef07 backport][3.11] Small speed up to starting web requests
  CHANGES/9241.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided

#9252 [PR #9241/7e0ef07 backport][3.10] Small speed up to starting web requests
  CHANGES/9241.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided

#9239 Stop raise_for_status() releasing when in a context
  CHANGES/9239.bugfix.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9254 Disallow .json()/.text() outside of context
  CHANGES/9254.breaking.rst
  aiohttp/client_reqrep.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport:skip

#9030 Fix cancellations being swallowed
  CHANGES/9030.bugfix.rst
  aiohttp/client_reqrep.py
  aiohttp/web_protocol.py
  tests/test_client_request.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9255 Stop raise_for_status() releasing when in a context (#9239)
  CHANGES/9239.bugfix.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9256 Stop raise_for_status() releasing when in a context (#9239)
  CHANGES/9239.bugfix.rst
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#9257 Fix cancellations being swallowed (#9030)
  CHANGES/9030.bugfix.rst
  aiohttp/client_reqrep.py
  aiohttp/web_protocol.py
  tests/test_client_request.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#9258 Fix cancellations being swallowed (#9030)
  CHANGES/9030.bugfix.rst
  aiohttp/client_reqrep.py
  aiohttp/web_protocol.py
  tests/test_client_request.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#9261 Cleanup changelog messages
  CHANGES/4650.bugfix
  CHANGES/8845.bugfix.rst
  CHANGES/9031.misc.rst
  CHANGES/9204.misc.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9260 Release 3.10.6rc0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9267 Fix double unquoting in url dispatcher
  CHANGES/9267.breaking.rst
  CHANGES/9267.bugfix.rst
  aiohttp/web_urldispatcher.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/test_urldispatch.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9269 [PR #9267/947b9c4 backport][3.10] Fix double unquoting in url dispatcher
  CHANGES/9267.breaking.rst
  CHANGES/9267.bugfix.rst
  aiohttp/web_urldispatcher.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/test_urldispatch.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#9270 [PR #9267/947b9c4 backport][3.11] Fix double unquoting in url dispatcher
  CHANGES/9267.breaking.rst
  CHANGES/9267.bugfix.rst
  aiohttp/web_urldispatcher.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/test_urldispatch.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#9271 Release 3.10.6rc1
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9273 Release 3.10.6rc2
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9276 Bump uvloop
  .github/workflows/ci-cd.yml
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8748 Add Python 3.13 classifier
  CHANGES/8748.feature.rst
  setup.cfg
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9279 [3.10] Bump pydantic and deps for python 3.13 compat
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#9282 [3.10] Bump typing-extensions to 4.12.2
  requirements/constraints.txt
  requirements/cython.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#9278 Bump uvloop (#9276)
  .github/workflows/ci-cd.yml
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#9284 Bump aiohttp-theme
  .readthedocs.yml
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9289 [PR #9083/a6dd415 backport][3.10] Remove unused backwards compatibility code for old yarl versions
  aiohttp/client_reqrep.py
  aiohttp/typedefs.py
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#9285 Increase default keepalive_timeout server-side.
  CHANGES/9285.misc.rst
  aiohttp/web_protocol.py
  docs/web_reference.rst
Labels: bot:chronographer:provided, backport-3.11

#9293 Increase default keepalive_timeout server-side. (#9285)
  CHANGES/9285.misc.rst
  aiohttp/web_protocol.py
  docs/web_reference.rst
Labels: bot:chronographer:provided

#9226 Test typing round 6
  aiohttp/http_websocket.py
  aiohttp/web_ws.py
  tests/test_web_runner.py
  tests/test_web_sendfile_functional.py
  tests/test_web_server.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:skip, backport:skip

#9294 Backport type fix from #9226
  aiohttp/web_ws.py
Labels: bot:chronographer:skip, backport-3.11

#9292 Reject non-str values in form data
  CHANGES/9292.breaking.rst
  aiohttp/formdata.py
  tests/test_client_session.py
  tests/test_formdata.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport:skip

#9302 Bump yarl to 1.13.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9304 [PR #9302/0b8be7f6 backport][3.10] Bump yarl to 1.13.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#9305 Increase minimum yarl requirement to 1.13.0
  CHANGES/9305.breaking.rst
  requirements/runtime-deps.in
  setup.cfg
Labels: bot:chronographer:provided, backport-3.11
