Repository aio-libs/aiohttp, pull requests merged in 2024-12, with the labels that each got.

#10078 Bump yarl to 1.18.3
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10076 Fix request count check for BadHttpMethod
  CHANGES/10055.bugfix.rst
  CHANGES/10076.bugfix.rst
  aiohttp/web_protocol.py
  aiohttp/web_server.py
  tests/test_web_server.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10079 [PR #10078/0d6a83e backport][3.11] Bump yarl to 1.18.3
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#10080 [PR #10078/0d6a83e backport][3.12] Bump yarl to 1.18.3
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#10073 Improve performance of parsing headers
  CHANGES/10073.misc.rst
  aiohttp/_http_parser.pyx
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10087 Increment version to 3.11.10.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10086 DO NOT MERGE
  CHANGES.rst
  CHANGES/10055.bugfix.rst
  CHANGES/10073.misc.rst
  CHANGES/10076.bugfix.rst
Labels: backport:skip

#10088 Avoid calling len on the same data in the stream reader twice
  aiohttp/streams.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10074 Support absolute url to override base url
  CHANGES/10074.feature.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  docs/client_reference.rst
  tests/test_client_session.py
Labels: bot:chronographer:provided, backport-3.12

#10095 Add a benchmark for web.FileResponse
  tests/test_benchmarks_web_fileresponse.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10102 Fix deprecated calls to `guess_type` for paths with Python 3.13
  CHANGES/10102.bugfix.rst
  aiohttp/payload.py
  aiohttp/web_fileresponse.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10101 Fix race in `FileResponse` if file is replaced during `prepare`
  CHANGES/10101.bugfix.rst
  aiohttp/web_fileresponse.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10107 Use internal `self._headers` var in `FileResponse`
  aiohttp/web_fileresponse.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10114 Add 304 benchmark for FileResponse
  tests/test_benchmarks_web_fileresponse.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10113 Restore 304 performance after fixing `FileResponse` replace race
  CHANGES/10113.bugfix.rst
  aiohttp/web_fileresponse.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10122 Typing improvements for file responses
  aiohttp/web_fileresponse.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10123 [PR #10122/703ce61 backport][3.11] Typing improvements for file responses
  aiohttp/web_fileresponse.py
Labels: bot:chronographer:skip

#10124 [PR #10122/703ce61 backport][3.12] Typing improvements for file responses
  aiohttp/web_fileresponse.py
Labels: bot:chronographer:skip

#10125 Disable zero copy writes in the ``StreamWriter``
  CHANGES/10125.bugfix.rst
  aiohttp/http_writer.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10130 Increment version to 3.11.11.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10129 DO NOT MERGE
  CHANGES.rst
  CHANGES/10101.bugfix.rst
  CHANGES/10102.bugfix.rst
  CHANGES/10113.bugfix.rst
  CHANGES/10125.bugfix.rst
Labels: backport:skip

#10131 Bump Python version for benchmarks to 3.13
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10138 Bump sphinx to 8.1.3 along with required dependencies
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10099 Fix type of SSLContext for some static type checkers
  CHANGES/10099.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/web.py
  aiohttp/web_runner.py
  aiohttp/worker.py
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10144 Fix type of SSLContext for some static type checkers (#10099)
  CHANGES/10099.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/web.py
  aiohttp/web_runner.py
  aiohttp/worker.py
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided

#10145 Fix type of SSLContext for some static type checkers (#10099)
  CHANGES/10099.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/web.py
  aiohttp/web_runner.py
  aiohttp/worker.py
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided

#10150 Add host parameter to aiohttp_server fixture (#10120) (#10121)
  CHANGES/10120.feature.rst
  aiohttp/pytest_plugin.py
Labels: bot:chronographer:provided

#10154 Update StreamResponse.write annotation for strict-bytes
  CHANGES/10154.bugfix.rst
  aiohttp/abc.py
  aiohttp/http_writer.py
  aiohttp/web_response.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10146 Raise `TypeError` when setting `StreamResponse.last_modified` to an unsupported type
  CHANGES/10146.misc.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.12

#10156 Add ALPN extension to client SSL Context
  CHANGES/10156.feature.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10151 Fix infinite callback loop when time is not moving forward
  CHANGES/10149.misc.rst
  aiohttp/web_protocol.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10093 Use `quote_cookie` setting from ClientSession's cookiejar in `tmp_cookie_jar`
  CHANGES/10093.bugfix.rst
  aiohttp/abc.py
  aiohttp/client.py
  aiohttp/cookiejar.py
  tests/test_client_session.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10175 [PR #10093/7b5d54a backport][3.11] Use `quote_cookie` setting from ClientSession's cookiejar in `tmp_cookie_jar`
  CHANGES/10093.bugfix.rst
  aiohttp/abc.py
  aiohttp/client.py
  aiohttp/cookiejar.py
  tests/test_client_session.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#10176 [PR #10093/7b5d54a backport][3.12] Use `quote_cookie` setting from ClientSession's cookiejar in `tmp_cookie_jar`
  CHANGES/10093.bugfix.rst
  aiohttp/abc.py
  aiohttp/client.py
  aiohttp/cookiejar.py
  tests/test_client_session.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#10172 Ensure Response is True even when map is empty
  CHANGES/10119.bugfix.rst
  aiohttp/web_response.py
  tests/test_web_request.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.12

#10179 [PR #10171/5185f93 backport][3.11] Stream unpauses protocol before releasing connection
  CHANGES/10169.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/streams.py
  tests/test_flowcontrol_streams.py
Labels: bot:chronographer:provided

#10180 [PR #10171/5185f93 backport][3.12] Stream unpauses protocol before releasing connection
  CHANGES/10169.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/streams.py
  tests/test_flowcontrol_streams.py
Labels: bot:chronographer:provided

#10182 Do not merge
  CHANGES.rst
  CHANGES/10093.bugfix.rst
  CHANGES/10099.bugfix.rst
  CHANGES/10149.misc.rst
  CHANGES/10154.bugfix.rst
  CHANGES/10156.feature.rst
  CHANGES/10169.bugfix.rst
Labels: backport:skip

#10183 Increment version to 3.11.12.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10188 Move dependabot to 3.12 branch
  .github/dependabot.yml
Labels: bot:chronographer:skip, backport-3.12

#10192 Bump Dependabot updates to Python 3.10
  requirements/base.txt
  requirements/constraints.txt
  requirements/cython.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
  requirements/lint.txt
  requirements/multidict.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.12

#10270 fix: include carriage return in multipartform.decode()
  CHANGES/10270.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/multipart.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10283 Clarify purpose of parameters `allow_redirects`, `max_redirects` for `ClientSession.request` (and related functions)
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.11, backport-3.12
