Repository aio-libs/aiohttp, pull requests merged in 2024-03, with the labels that each got.

#8197 fix base_url param documentation
  CHANGES/8197.doc
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8252 Fix handling of unsupported upgrades with the pure python http parser
  CHANGES/8252.bugfix.rst
  aiohttp/http_parser.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8256 Ensure websocket transport is closed when client does not close it (#8200)
  CHANGES/8200.bugfix.rst
  aiohttp/web_ws.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#8259 Flag python 3.11/12 support
  .github/workflows/ci-cd.yml
  setup.cfg
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8257 Ensure websocket transport is closed when client does not close it (#8200)
  CHANGES/8200.bugfix.rst
  aiohttp/web_ws.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#8251 Leave websocket transport open if receive times out or is cancelled
  CHANGES/8251.bugfix.rst
  aiohttp/web_ws.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8260 Adjust import timings test for python 3.12
  tests/test_imports.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8267 Add note about tasks that should be cancelled on shutdown
  CHANGES/8267.doc.rst
  docs/web_advanced.rst
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8271 Fix race condition with request handlers on shutdown
  CHANGES/8271.bugfix.rst
  aiohttp/web_runner.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10
