Repository aio-libs/aiohttp, pull requests merged in 2024-08, with the labels that each got.

#8546 Fix WebSocket server heartbeat timeout logic
  CHANGES/8540.bugfix.rst
  aiohttp/client_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided, backport-3.10

#8558 Add followup changelog message for #5278
  CHANGES/8555.breaking.rst
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8566 Fix url dispatcher index when variable is preceded by a fixed string after a slash
  CHANGES/8566.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8573 [PR #8546/a561fa99 backport][3.10] Fix WebSocket server heartbeat timeout logic
  CHANGES/8540.bugfix.rst
  aiohttp/client_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided

#8574 [PR #8546/a561fa99 backport][3.11] Fix WebSocket server heartbeat timeout logic (#8546)
  CHANGES/8540.bugfix.rst
  aiohttp/client_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided

#8583 Add additional clarification for creating objects that require a running event loop
  CHANGES/8555.breaking.rst
  CHANGES/8583.breaking.rst
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8584 Fix dependabot configuration for 3.11
  .github/dependabot.yml
Labels: bot:chronographer:skip, backport:skip

#8594 Close stale issues without info
  .github/workflows/stale.yml
Labels: bot:chronographer:skip, backport-3.11

#8596 Remove old backwards-compatibility stub
  CHANGES/8596.breaking.rst
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/multipart.py
  tests/test_client_session.py
  tests/test_multipart.py
  tests/test_web_functional.py
  tests/test_web_sendfile_functional.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport:skip

#8598 Release 3.10.1 (attempt 2)
  CHANGES.rst
Labels: bot:chronographer:skip

#8601 DO NOT MERGE
  CHANGES.rst
Labels: bot:chronographer:skip, backport:skip

#8619 Fix monkey patches for pathlib changes in Python 3.13
  CHANGES/8551.contrib.rst
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8612 Export ClientWSTimeout to top-level namespace
  CHANGES/8612.feature.rst
  aiohttp/__init__.py
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8611 Fix handler waiting on shutdown
  CHANGES/8611.bugfix.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8597 Fix reading of body when ignoring an upgrade request
  CHANGES/8597.bugfix.rst
  aiohttp/_http_parser.pyx
  tests/test_http_parser.py
  tests/test_web_server.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8620 Test typing round 2
  .coveragerc
  .github/workflows/ci-cd.yml
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/typedefs.py
  requirements/lint.in
  requirements/lint.txt
  tests/conftest.py
  tests/test_client_exceptions.py
  tests/test_client_functional.py
  tests/test_client_proto.py
  tests/test_client_request.py
  tests/test_client_response.py
  tests/test_client_session.py
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_connector.py
  tests/test_cookiejar.py
Labels: bot:chronographer:skip, backport:skip

#8634 Backport #8620 as improvements to various type annotations
  .coveragerc
  .github/workflows/ci-cd.yml
  CHANGES/8634.misc.rst
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/typedefs.py
  aiohttp/web_request.py
  requirements/lint.in
  requirements/lint.txt
Labels: bot:chronographer:provided, backport-3.10

#8632 Fix connecting to npipe://, tcp://, and unix:// urls
  CHANGES/8632.bugfix.rst
  aiohttp/client.py
  aiohttp/connector.py
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8638 [PR #8632/b2691f2 backport][3.11] Fix connecting to npipe://, tcp://, and unix:// urls
  CHANGES/8632.bugfix.rst
  aiohttp/client.py
  aiohttp/connector.py
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#8637 [PR #8632/b2691f2 backport][3.10] Fix connecting to npipe://, tcp://, and unix:// urls
  CHANGES/8632.bugfix.rst
  aiohttp/client.py
  aiohttp/connector.py
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#8608 Fix timer handle churn in websocket heartbeat
  CHANGES/8608.misc.rst
  aiohttp/client_ws.py
  aiohttp/helpers.py
  aiohttp/web_ws.py
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8639 [PR #8608/c4acabc backport][3.10] Fix timer handle churn in websocket heartbeat
  CHANGES/8608.misc.rst
  aiohttp/client_ws.py
  aiohttp/helpers.py
  aiohttp/web_ws.py
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#8640 [PR #8608/c4acabc backport][3.11] Fix timer handle churn in websocket heartbeat
  CHANGES/8608.misc.rst
  aiohttp/client_ws.py
  aiohttp/helpers.py
  aiohttp/web_ws.py
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#8641 Fix WebSocket ping tasks being prematurely garbage collected
  CHANGES/8641.bugfix.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8646 [PR #8641/0a88bab backport][3.10] Fix WebSocket ping tasks being prematurely garbage collected
  CHANGES/8641.bugfix.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided

#8642 Fix response to circular symlinks with Python v3.13
  CHANGES/8565.bugfix.rst
  aiohttp/web_fileresponse.py
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8636 Remove Request.wait_for_disconnection() method
  CHANGES/8636.breaking.rst
  aiohttp/web_request.py
  docs/web_reference.rst
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8650 [PR #8636/51d872e backport][3.10] Remove Request.wait_for_disconnection() method
  CHANGES/8636.breaking.rst
  aiohttp/web_request.py
  docs/web_reference.rst
Labels: bot:chronographer:provided

#8651 [PR #8636/51d872e backport][3.11] Remove Request.wait_for_disconnection() method
  CHANGES/8636.breaking.rst
  aiohttp/web_request.py
  docs/web_reference.rst
Labels: bot:chronographer:provided

#8652 Do not follow symlinks for compressed file variants
  CHANGES/8652.bugfix.rst
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8656 DO NOT MERGE
  CHANGES.rst
  CHANGES/8540.bugfix.rst
  CHANGES/8551.contrib.rst
  CHANGES/8555.breaking.rst
  CHANGES/8565.bugfix.rst
  CHANGES/8566.bugfix.rst
  CHANGES/8583.breaking.rst
  CHANGES/8597.bugfix.rst
  CHANGES/8608.misc.rst
  CHANGES/8611.bugfix.rst
  CHANGES/8632.bugfix.rst
  CHANGES/8636.breaking.rst
  CHANGES/8641.bugfix.rst
  CHANGES/8652.bugfix.rst
Labels: backport:skip

#8657 Fix multipart reading with split boundary
  CHANGES/8653.bugfix.rst
  aiohttp/multipart.py
  tests/test_multipart.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8660 Improve performance of WebSockets when there is no timeout
  CHANGES/8660.misc.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8661 Improve performance of starting request handlers with Python 3.12+
  CHANGES/8661.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8663 [PR #8660/14d5295 backport][3.10] Improve performance of WebSockets when there is no timeout
  CHANGES/8660.misc.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
Labels: bot:chronographer:provided

#8664 [PR #8660/14d5295 backport][3.11] Improve performance of WebSockets when there is no timeout
  CHANGES/8660.misc.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
Labels: bot:chronographer:provided

#8665 [PR #8661/4d604ea backport][3.10] Improve performance of starting request handlers with Python 3.12+
  CHANGES/8661.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided

#8666 [PR #8661/4d604ea backport][3.11] Improve performance of starting request handlers with Python 3.12+
  CHANGES/8661.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided

#8667 Improve performance of generating random WebSocket mask
  CHANGES/8667.misc.rst
  aiohttp/http_websocket.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8662 Improve performance of keepalive rescheduling
  CHANGES/8662.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8672 Fix TCPConnector doing blocking I/O in the event loop to create the SSLContext
  CHANGES/8672.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8673 [PR #8672/c3219bf backport][3.10] Fix TCPConnector doing blocking I/O in the event loop to create the SSLContext
  CHANGES/8672.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#8674 [PR #8672/c3219bf backport][3.11] Fix TCPConnector doing blocking I/O in the event loop to create the SSLContext
  CHANGES/8672.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#8676 Fix type ignore in SSLContext creation connector test
  tests/test_connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8677 [PR #8676/2915102 backport][3.10] Fix type ignore in SSLContext creation connector test
  tests/test_connector.py
Labels: bot:chronographer:skip

#8678 [PR #8676/2915102 backport][3.11] Fix type ignore in SSLContext creation connector test
  tests/test_connector.py
Labels: bot:chronographer:skip

#8679 DO NOT MERGE
  CHANGES.rst
  CHANGES/8653.bugfix.rst
  CHANGES/8660.misc.rst
  CHANGES/8661.misc.rst
  CHANGES/8662.misc.rst
  CHANGES/8667.misc.rst
  CHANGES/8672.bugfix.rst
Labels: backport:skip

#8680 Fix close race that prevented the close code from reaching the client
  CHANGES/8680.bugfix.rst
  aiohttp/web_ws.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8687 [PR #8680/4f41d05 backport][3.11] Fix close race that prevented the close code from reaching the client
  CHANGES/8680.bugfix.rst
  aiohttp/web_ws.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#8686 [PR #8680/4f41d05 backport][3.10] Fix close race that prevented the close code from reaching the client
  CHANGES/8680.bugfix.rst
  aiohttp/web_ws.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#8688 Fix decoding base64 chunk for BodyPartReader (#3867)
  CHANGES/3867.bugfix.rst
  aiohttp/multipart.py
  tests/test_multipart.py
Labels: bot:chronographer:provided

#8689 Fix decoding base64 chunk for BodyPartReader (#3867)
  CHANGES/3867.bugfix.rst
  aiohttp/multipart.py
  tests/test_multipart.py
Labels: bot:chronographer:provided

#8693 Fix missing logic in quickstart example
  docs/web_quickstart.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8714 Minor improvements to testing docs
  docs/testing.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8701 Test typing round 3
  aiohttp/helpers.py
  aiohttp/http_exceptions.py
  aiohttp/multipart.py
  requirements/lint.in
  requirements/lint.txt
  tests/test_flowcontrol_streams.py
  tests/test_formdata.py
  tests/test_helpers.py
  tests/test_http_exceptions.py
  tests/test_http_parser.py
  tests/test_http_writer.py
  tests/test_multipart.py
  tests/test_proxy.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip, backport:skip

#8718 Missed type fix
  aiohttp/multipart.py
  tests/test_multipart.py
Labels: bot:chronographer:skip, backport:skip

#8720 Fix Python parser when chunk separators align
  CHANGES/8720.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8722 Fix Python parser when chunk separators align (#8720)
  CHANGES/8720.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8721 Fix Python parser when chunk separators align (#8720)
  CHANGES/8720.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8681 Improve performance of starting request handlers with Python 3.12+
  CHANGES/8681.misc.rst
  aiohttp/web_protocol.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8682 Reduce WebSocket frame parser complexity
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8685 Fix exceptions from WebSocket ping task not being consumed
  CHANGES/8685.bugfix.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8732 Release 3.10.4 (Attempt 2)
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#8733 DO NOT MERGE
  CHANGES.rst
  CHANGES/8680.bugfix.rst
  CHANGES/8681.misc.rst
  CHANGES/8685.bugfix.rst
  CHANGES/8700.doc.rst
  CHANGES/8720.bugfix.rst
Labels: backport:skip

#8740 [3.10] Bump pypa/cibuildwheel to v2.20.0
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#8736 Improve performance of WebSocketReader
  CHANGES/8736.misc.rst
  aiohttp/http_websocket.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8742 Fix status not being set when ClientResponse.json raises ContentTypeError
  CHANGES/8742.bugfix.rst
  aiohttp/client_reqrep.py
  tests/test_client_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8743 [PR #8736/1b88af2 backport][3.10] Improve performance of WebSocketReader
  CHANGES/8736.misc.rst
  aiohttp/http_websocket.py
Labels: bot:chronographer:provided

#8747 Make MESSAGE_TYPES_WITH_CONTENT a frozenset for the WebSocketReader
  CHANGES/8747.misc.rst
  aiohttp/http_websocket.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8749 Bump cffi to 1.17.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8752 [PR #8749/5e30b49 backport][3.10] Bump cffi to 1.17.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#8753 [PR #8749/5e30b49 backport][3.11] Bump cffi to 1.17.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/lint.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#8755 Update indirect dependencies with Dependabot
  .github/dependabot.yml
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8763 DO NOT MERGE
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
Labels: backport:skip

#8776 Use more precise headers type
  CHANGES/8768.bugfix.rst
  aiohttp/client_exceptions.py
  tests/test_client_exceptions.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8798 Maybe fix some flaky tests
  tests/test_proxy.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8797 Drop Python 3.8
  .github/workflows/ci-cd.yml
  .github/workflows/update-pre-commit.yml
  CHANGES/8797.breaking.rst
  Makefile
  aiohttp/cookiejar.py
  aiohttp/resolver.py
  aiohttp/web_fileresponse.py
  setup.cfg
  setup.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.11

#8799 Drop Python 3.8 (#8797)
  .codecov.yml
  .github/workflows/ci-cd.yml
  CHANGES/8797.breaking.rst
  Makefile
  aiohttp/cookiejar.py
  aiohttp/resolver.py
  aiohttp/web_fileresponse.py
  setup.cfg
  setup.py
  tests/test_resolver.py
Labels: bot:chronographer:provided

#8734 Test typing round 4
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/pytest_plugin.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/tracing.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/web_urldispatcher.py
  tests/test_client_functional.py
  tests/test_route_def.py
  tests/test_run_app.py
  tests/test_streams.py
  tests/test_test_utils.py
  tests/test_tracing.py
  tests/test_urldispatch.py
  tests/test_websocket_parser.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:skip, backport:skip

#8800 Upload junit to codecov
  .github/workflows/ci-cd.yml
  setup.cfg
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8823 Fix Python parser chunked handling with multiple Transfer-Encoding values
  CHANGES/8823.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8843 Fix Python parser chunked handling with multiple Transfer-Encoding values
  CHANGES/8823.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8844 Fix Python parser chunked handling with multiple Transfer-Encoding values
  CHANGES/8823.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8804 docs: minor grammar fix in client_reference.rst
  .github/workflows/ci-cd.yml
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8846 Format status lines with f-strings
  aiohttp/client_reqrep.py
  aiohttp/web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8858 No default Content-Type when no content
  CHANGES/8858.bugfix.rst
  aiohttp/helpers.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  tests/test_client_functional.py
  tests/test_web_functional.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8845 Return 500 error when handler has wrong return type
  CHANGES/8845.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_functional.py
  tests/test_web_request.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#5344 Fix StreamResponse.prepared not returning True after EOF is sent
  CHANGES/5343.bugfix
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8891 Return 500 error when handler has wrong return type (#8845)
  CHANGES/8845.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#8892 Return 500 error when handler has wrong return type (#8845)
  CHANGES/8845.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#8874 Update testing utility examples
  docs/testing.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8876 Fix server disconnect when error after 100-continue
  CHANGES/8876.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8899 Fix server disconnect when error after 100-continue (#8876)
  CHANGES/8876.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#8900 Fix server disconnect when error after 100-continue (#8876)
  CHANGES/8876.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#8878 Ensure error is raised when reading from closed client response.
  CHANGES/8878.bugfix.rst
  aiohttp/streams.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8895 Cache the hash generation of the ConnectionKey
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10

#8902 Ensure error is raised when reading from closed client response. (#8878)
  CHANGES/8878.bugfix.rst
  aiohttp/streams.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#8901 Ensure error is raised when reading from closed client response. (#8878)
  CHANGES/8878.bugfix.rst
  aiohttp/streams.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#8875 Fix unclosed transport warning
  CHANGES/8875.bugfix.rst
  aiohttp/web_protocol.py
  setup.cfg
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8909 Drop legacy yarl compatibility
  CHANGES/8909.breaking.rst
  aiohttp/web_urldispatcher.py
  requirements/runtime-deps.in
  setup.cfg
Labels: bot:chronographer:provided, backport:skip

#6495 Support credentials in URL with empty user, http://:password@host (#6494)
  CHANGES/6494.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  tests/test_client_request.py
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8926 Support credentials in URL with empty user (#6494) (#6495)
  CHANGES/6494.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  tests/test_client_request.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#8927 Support credentials in URL with empty user (#6494) (#6495)
  CHANGES/6494.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  tests/test_client_request.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#8930 Fix limit docs
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8929 Fix Site.name with empty host
  CHANGES/8929.bugfix.rst
  aiohttp/web_runner.py
  tests/test_web_runner.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#6485 Fix Response.text when body is Payload
  CHANGES/6485.bugfix.rst
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/web_response.py
  tests/test_payload.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8920 Re-enable keep-alive on proxies
  CHANGES/8920.misc.rst
  aiohttp/client_proto.py
  aiohttp/connector.py
Labels: bot:chronographer:provided, backport-3.11

#8937 Fix Response.text when body is Payload (#6485)
  CHANGES/6485.bugfix.rst
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/payload_streamer.py
  aiohttp/web_response.py
  tests/test_payload.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#8938 Fix Response.text when body is Payload (#6485)
  CHANGES/6485.bugfix.rst
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/payload_streamer.py
  aiohttp/web_response.py
  tests/test_payload.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#6747 Upload tarfile file-like objects as data attributes
  CHANGES/6732.bugfix
  CONTRIBUTORS.txt
  aiohttp/payload.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8940 Fix tarfile file-like objects used as data (#6747)
  CHANGES/6732.bugfix
  CONTRIBUTORS.txt
  aiohttp/payload.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#8941 Fix tarfile file-like objects used as data (#6747)
  CHANGES/6732.bugfix
  CONTRIBUTORS.txt
  aiohttp/payload.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#8936 Test coverage of TextIOWrapper
  tests/test_formdata.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#8948 Make n argument clearer
  docs/streams.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#7731 Add flake8-no-implicit-concat
  .pre-commit-config.yaml
  CHANGES/7731.misc.rst
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  aiohttp/cookiejar.py
  aiohttp/formdata.py
  aiohttp/helpers.py
  aiohttp/http_websocket.py
  aiohttp/multipart.py
  aiohttp/streams.py
  aiohttp/test_utils.py
  aiohttp/web.py
  aiohttp/web_app.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/web_urldispatcher.py
  setup.cfg
  tests/test_client_exceptions.py
  tests/test_client_functional.py
  tests/test_client_proto.py
  tests/test_helpers.py
  tests/test_http_exceptions.py
  tests/test_http_parser.py
  tests/test_http_writer.py
  tests/test_multipart.py
  tests/test_multipart_helpers.py
  tests/test_urldispatch.py
  tests/test_web_cli.py
  tests/test_web_exceptions.py
  tests/test_web_functional.py
  tests/test_web_request.py
  tests/test_web_websocket_functional.py
  tests/test_websocket_parser.py
Labels: enhancement, infra, bot:chronographer:provided, backport-3.11

#8953 Add clarification about auth parameter in ClientSession
  CHANGES/6764.doc.rst
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8956 Add parameters to del_cookie()
  CHANGES/8956.feature.rst
  aiohttp/helpers.py
Labels: bot:chronographer:provided, backport-3.11

#8959 Add parameters to del_cookie() (#8956)
  CHANGES/8956.feature.rst
  aiohttp/web_response.py
Labels: bot:chronographer:provided

#8898 Fix router matching pre-encoded URLs
  CHANGES/8898.bugfix.rst
  aiohttp/web_urldispatcher.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
  tests/test_urldispatch.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8947 Add aiohttp.tracing.TraceRequestHeadersSentParams into the top level file.
  CHANGES/8947.misc.rst
  aiohttp/__init__.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#8960 Fix router matching pre-encoded URLs (#8898)
  CHANGES/8898.bugfix.rst
  aiohttp/web_urldispatcher.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
  tests/test_urldispatch.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#8961 Fix router matching pre-encoded URLs (#8898)
  CHANGES/8898.bugfix.rst
  aiohttp/web_urldispatcher.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
  tests/test_urldispatch.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#8963 Add aiohttp.tracing.TraceRequestHeadersSentParams into the top level … (3.11)
  CHANGES/8947.misc.rst
  aiohttp/__init__.py
Labels: bot:chronographer:provided

#8964 Add aiohttp.tracing.TraceRequestHeadersSentParams into the top level … (3.10)
  CHANGES/8947.misc.rst
  aiohttp/__init__.py
Labels: bot:chronographer:provided

#8957 Remove version from set_cookie()
  CHANGES/8957.breaking.rst
  aiohttp/helpers.py
  docs/web_reference.rst
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport:skip
