Repository aio-libs/aiohttp, pull requests merged in 2024-04, with the labels that each got.

#8286 docs: remove repetitive word in comment
  docs/testing.rst
Labels: documentation, bot:chronographer:skip, backport-3.9, backport-3.10

#8283 Fix blocking I/O in the event loop while processing files in a post request
  CHANGES/8283.bugfix.rst
  aiohttp/test_utils.py
  aiohttp/web_request.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8295 Fix AsyncResolver to match ThreadedResolver behavior (#8270)
  CHANGES/8270.bugfix.rst
  aiohttp/abc.py
  aiohttp/connector.py
  aiohttp/resolver.py
  docs/abc.rst
  docs/conf.py
  examples/fake_server.py
  requirements/runtime-deps.in
  setup.cfg
  tests/test_resolver.py
Labels: bot:chronographer:provided

#8300 Revert #3492
  CHANGES/2302.feature
  aiohttp/multipart.py
  tests/test_multipart.py
Labels: bot:chronographer:skip

#8280 Fix handling of multipart/form-data
  CHANGES/8280.bugfix.rst
  CHANGES/8280.deprecation.rst
  aiohttp/formdata.py
  aiohttp/multipart.py
  tests/test_client_functional.py
  tests/test_multipart.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8301 Fix handling of multipart/form-data (#8280)
  CHANGES/8280.bugfix.rst
  CHANGES/8280.deprecation.rst
  aiohttp/formdata.py
  aiohttp/multipart.py
  tests/test_client_functional.py
  tests/test_multipart.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#8302 Fix handling of multipart/form-data (#8280)
  CHANGES/8280.bugfix.rst
  CHANGES/8280.deprecation.rst
  aiohttp/formdata.py
  aiohttp/multipart.py
  tests/test_client_functional.py
  tests/test_multipart.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#8304 Check for backports in CI
  .github/workflows/labels.yml
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8299 Create marker for internal tests
  CHANGES/8299.packaging.rst
  setup.cfg
  tests/test_imports.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8290 Fix for #8253 "Unclosed client session" when initialization fails
  CHANGES/8253.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  tests/test_client_session.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8309 Improve reliability of run_app test
  tests/test_run_app.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8310 Patchback/backports/3.10/5fd29467fb63efdfae1ace280cec36b1f8139567/pr 8290
  CHANGES/8253.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  tests/test_client_session.py
Labels: bot:chronographer:provided

#8317 Escape filenames and paths in HTML when generating index pages
  CHANGES/8317.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8318 Escape filenames and paths in HTML when generating index pages (#8317)
  CHANGES/8317.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#8319 Escape filenames and paths in HTML when generating index pages (#8317)
  CHANGES/8317.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#8320 Fix Python parser to mark responses without length as closing
  CHANGES/8320.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8323 DO NOT MERGE
  CHANGES.rst
  CHANGES/7741.bugfix.rst
  CHANGES/8010.doc
  CHANGES/8089.bugfix.rst
  CHANGES/8099.contrib.rst
  CHANGES/8104.bugfix.rst
  CHANGES/8116.contrib.rst
  CHANGES/8136.contrib.rst
  CHANGES/8146.feature.rst
  CHANGES/8163.bugfix.rst
  CHANGES/8200.bugfix.rst
  CHANGES/8251.bugfix.rst
  CHANGES/8252.bugfix.rst
  CHANGES/8267.doc.rst
  CHANGES/8271.bugfix.rst
  CHANGES/8280.bugfix.rst
  CHANGES/8280.deprecation.rst
  CHANGES/8283.bugfix.rst
  CHANGES/8292.feature.rst
  CHANGES/8299.packaging.rst
  CHANGES/8317.bugfix.rst
  CHANGES/8320.bugfix.rst
  aiohttp/multipart.py
  examples/fake_server.py
  tests/test_client_session.py
  tests/test_resolver.py
Labels: backport:skip

#8324 Add missing changelogs
  CHANGES.rst
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8332 Add set_content_disposition test
  CHANGES/8332.bugfix.rst
  aiohttp/multipart.py
  tests/test_multipart.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8335 Add Content-Disposition automatically
  CHANGES/8335.bugfix.rst
  aiohttp/multipart.py
  tests/test_multipart.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8338 Add some coverage
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_client_ws_functional.py
  tests/test_test_utils.py
  tests/test_web_app.py
  tests/test_web_runner.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8343 DO NOT MERGE
  CHANGES.rst
  CHANGES/8253.bugfix
  CHANGES/8332.bugfix.rst
  CHANGES/8335.bugfix.rst
  docs/contributing-admins.rst
Labels: backport:skip

#8346 :memo: Add nacl_middleware to third_party.rst.
  CHANGES/8346.misc.rst
  docs/third_party.rst
Labels: bot:chronographer:provided, backport-3.10

#8339 Upgrade the deprecated GitHub Actions `set-output` workflow command syntax
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8353 Skip labels for dependabot
  .github/workflows/labels.yml
Labels: bot:chronographer:skip, backport-3.10

#8355 Remove typing-extensions (#8352)
  requirements/base.in
  requirements/cython.in
  requirements/lint.in
  requirements/typing-extensions.in
  requirements/typing-extensions.txt
Labels: bot:chronographer:skip

#8351 Fix dependabot backport target
  .github/dependabot.yml
  docs/contributing-admins.rst
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8362 Use bot type for check
  .github/workflows/labels.yml
Labels: bot:chronographer:skip, backport-3.10

#8364 Improve accuracy of subapp resource types
  CHANGES/8364.misc.rst
  aiohttp/web_app.py
Labels: bot:chronographer:provided, backport-3.10

#8367 Delete size arg from StreamReader.feed_data #7265
  CHANGES/7265.breaking.rst
  CONTRIBUTORS.txt
  aiohttp/_http_parser.pyx
  aiohttp/client_proto.py
  aiohttp/client_ws.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/streams.py
  aiohttp/web_ws.py
  tests/test_client_ws.py
  tests/test_flowcontrol_streams.py
  tests/test_http_parser.py
  tests/test_streams.py
  tests/test_web_websocket.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided, backport:skip

#8096 Remove unused readall from Python parser
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:skip, backport-3.10

#8368 Remove unused readall from Python parser (#8096)
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:skip

#8369 Update Matrix link
  README.rst
  docs/index.rst
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8365 Drop old Mypy ignores
  .mypy.ini
  aiohttp/abc.py
  aiohttp/connector.py
  aiohttp/resolver.py
  examples/fake_server.py
  requirements/lint.in
  requirements/lint.txt
  tests/autobahn/test_autobahn.py
  tests/test_resolver.py
Labels: bot:chronographer:skip, backport-3.10

#8372 Backport 3.9: Add tests, accidentally dropped before (#8088)
  CHANGES/8088.contrib.rst
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8384 Update .pre-commit-config.yaml
  .pre-commit-config.yaml
  aiohttp/client_reqrep.py
  aiohttp/client_ws.py
  aiohttp/compression_utils.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/http_exceptions.py
  aiohttp/tracing.py
  aiohttp/web_app.py
  aiohttp/web_request.py
  aiohttp/web_response.py
  aiohttp/web_routedef.py
  aiohttp/web_server.py
  aiohttp/web_ws.py
  tests/test_circular_imports.py
  tests/test_http_parser.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#8383 Drop old Mypy ignores (#8365)
  .mypy.ini
  aiohttp/abc.py
  aiohttp/connector.py
  aiohttp/resolver.py
  examples/fake_server.py
  requirements/lint.in
  requirements/lint.txt
  tests/autobahn/test_autobahn.py
  tests/test_resolver.py
Labels: bot:chronographer:skip

#8391 Fix flaky tests with unclosed warnings
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip, backport-3.10

#8392 Fix flaky tests with unclosed warnings (#8391)
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip
