Repository aio-libs/aiohttp, pull requests merged in 2024-11, with the labels that each got.

#9600 Avoid starting connection timeout when a connection is already available
  CHANGES/9600.breaking.rst
  aiohttp/client.py
  aiohttp/connector.py
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided, backport-3.11

#9607 [PR #9600/e6187f6 backport][3.11] Avoid starting connection timeout when a connection is already available
  CHANGES/9600.breaking.rst
  aiohttp/client.py
  aiohttp/connector.py
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided

#9604 Add benchmark for serializing headers
  tests/test_benchmarks_http_writer.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9611 Remove unused `_transport` from `Connection`
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9612 Remove unnecessary call to `.keys()` in `BaseConnector._release_waiter`
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9610 Simplify `BaseConnector._available_connections` logic
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9615 Avoid creating a future for the connection placeholder
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport:skip

#9616 Add `__slots__` to `Connection`
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9617 [3.11] Add `__slots__` to `_TransportPlaceholder`
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport-3.10

#9623 Fix available connection calculation
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9625 [PR #9623/898aa28 backport][3.11] Fix available connection calculation
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:skip

#9624 [PR #9623/898aa28 backport][3.10] Fix available connection calculation
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:skip

#9603 Improve performance of _serialize_headers
  CHANGES/9603.misc.rst
  aiohttp/_http_writer.pyx
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9629 Simplify branching in the connector
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9632 Release 3.11.0b1
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip, backport:skip

#9636 Avoid multiple slice calls in the WebSocket reader
  CHANGES/9636.feature.rst
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9635 Add benchmark for sending large WebSocket messages
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9628 Add benchmark for client WebSocket round trip
  tests/test_benchmarks_client_ws.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9651 Add a simple client benchmark
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9655 Bump yarl to 1.17.1
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9657 Release 3.11.0b2
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9658 Add benchmark for sending binary WebSocket messages
  tests/test_benchmarks_client_ws.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9659 Refactor `FlowControlDataQueue` to improve performances
  CHANGES/9659.misc.rst
  aiohttp/streams.py
Labels: bot:chronographer:skip, backport-3.11

#9665 [PR #9659/1bb146a backport][3.11] Refactor `FlowControlDataQueue` to improve performances
  CHANGES/9659.misc.rst
  aiohttp/streams.py
Labels: bot:chronographer:provided

#9667 Simplify ``close`` logic in client ``WebSocketResponse``
  aiohttp/client_ws.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9669 [PR #9667/5b654d57 backport][3.10] Simplify ``close`` logic in client ``WebSocketResponse``
  aiohttp/client_ws.py
Labels: bot:chronographer:skip

#9671 Refactor connection waiters to be cancellation safe
  CHANGES/9670.bugfix.rst
  CHANGES/9671.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9511 Fix exceptions in websocket receive_* methods
  CHANGES/6800.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  docs/client_reference.rst
  docs/web_reference.rst
  tests/test_client_ws_functional.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.11

#9676 [PR #9511/75ae623 backport][3.11] Fix exceptions in websocket receive_* methods
  CHANGES/6800.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  docs/client_reference.rst
  docs/web_reference.rst
  tests/test_client_ws_functional.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#9675 [PR #9671/37d9fe6 backport][3.11] Refactor connection waiters to be cancellation safe
  CHANGES/9670.bugfix.rst
  CHANGES/9671.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#9674 [PR #9671/37d9fe6 backport][3.10] Refactor connection waiters to be cancellation safe
  CHANGES/9670.bugfix.rst
  CHANGES/9671.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#9672 Reuse the oldest keep-alive connection first
  CHANGES/9672.bugfix.rst
  aiohttp/connector.py
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.11

#9678 Remove dead code from ``WebSocketResponse.receive``
  aiohttp/web_ws.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9679 Return early in WebSocket `receive` if there is no processing to do
  CHANGES/9679.misc.rst
  aiohttp/client_ws.py
  aiohttp/http_websocket.py
  aiohttp/web_ws.py
Labels: bot:chronographer:provided, backport-3.11

#9683 [PR #9679/3f2f4a7 backport][3.11] Return early in WebSocket `receive` if there is no processing to do
  CHANGES/9679.misc.rst
  aiohttp/client_ws.py
  aiohttp/http_websocket.py
  aiohttp/web_ws.py
Labels: bot:chronographer:provided

#9680 [PR #9672/afb5ebb backport][3.11] Reuse the oldest keep-alive connection first
  CHANGES/9672.bugfix.rst
  aiohttp/connector.py
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#9684 Release 3.11.0b3
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9508 Discard non-close messages in close timeout window
  CHANGES/9506.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/web_ws.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9688 [PR #9508/274c54e backport][3.11] Discard non-close messages in close timeout window
  CHANGES/9506.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/web_ws.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#9687 [PR #9508/274c54e backport][3.10] Discard non-close messages in close timeout window
  CHANGES/9506.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/web_ws.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#9689 Add benchmark for sending client requests
  tests/test_benchmarks_client_request.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9697 Relax async-timeout version to >=4.0, <6.0 (#9695)
  requirements/runtime-deps.in
  setup.cfg
Labels: bot:chronographer:skip

#9701 [PR #9698/422ba0c backport][3.11] Add flow control tests for WebSocket
  tests/test_websocket_parser.py
Labels: bot:chronographer:skip

#9693 Avoid duplicate `content_length` fetch to prepare web response headers
  aiohttp/web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9700 [PR #9698/422ba0c backport][3.10] Add flow control tests for WebSocket
  tests/test_websocket_parser.py
Labels: bot:chronographer:skip

#9692 Change `RequestInfo` to be a `NamedTuple` to improve performances
  CHANGES/9692.breaking.rst
  aiohttp/client_reqrep.py
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.11

#9686 [3.11] Fix WebSocket reader flow control size calculation for multi-byte data
  CHANGES/9686.bugfix.rst
  aiohttp/_websocket/reader_py.py
  docs/spelling_wordlist.txt
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided, backport-3.10

#9704 Simplify keep-alive logic for HTTP/1.0 in ClientRequest
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9685 Fix WebSocket reader flow control calculations
  CHANGES/9685.breaking.rst
  aiohttp/__init__.py
  aiohttp/_websocket/models.py
  aiohttp/_websocket/reader.py
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_ws.py
  aiohttp/streams.py
  aiohttp/web_ws.py
  tests/test_benchmarks_http_websocket.py
  tests/test_client_ws.py
  tests/test_client_ws_functional.py
  tests/test_flowcontrol_streams.py
  tests/test_web_websocket.py
  tests/test_websocket_data_queue.py
  tests/test_websocket_parser.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided, backport:skip

#9709 [PR #9686/ea1c084 backport][3.10] Fix WebSocket reader flow control size calculation for multi-byte data
  CHANGES/9686.bugfix.rst
  aiohttp/http_websocket.py
  docs/spelling_wordlist.txt
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#9710 Remove redundant `protocol.should_close` check in `Connection._release`
  aiohttp/connector.py
  tests/test_client_connection.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9711 [PR #9710/b40265e backport][3.10] Remove redundant `protocol.should_close` check in `Connection._release`
  aiohttp/connector.py
  tests/test_client_connection.py
Labels: bot:chronographer:skip

#9712 [PR #9710/b40265e backport][3.11] Remove redundant `protocol.should_close` check in `Connection._release`
  aiohttp/connector.py
  tests/test_client_connection.py
Labels: bot:chronographer:skip

#9713 Small cleanups to creating a ClientRequest
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9716 [PR #9713/500a021 backport][3.10] Small cleanups to creating a ClientRequest
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#9717 [PR #9713/500a021 backport][3.11] Small cleanups to creating a ClientRequest
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#9715 [PR #3753/401c256 backport][3.11] Warn on non-URL for `cookie_jar.filter_cookies()` call
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:skip

#9718 Release 3.11.0b4
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9722 Simplify header and method lookups
  CHANGES/9722.misc.rst
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/hdrs.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/web_response.py
  tests/test_helpers.py
Labels: bot:chronographer:skip, backport-3.11

#9723 Fix missing `reader_c.c` file in Makefile `.install-deps`
  Makefile
Labels: bot:chronographer:skip, backport-3.11

#9724 [PR #9722/fbf555c backport][3.11] Simplify header and method lookups
  CHANGES/9722.misc.rst
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/hdrs.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/web_response.py
  tests/test_helpers.py
Labels: bot:chronographer:provided

#9727 gitignore websocket mask and reader_c
  .gitignore
Labels: bot:chronographer:skip, backport-3.11

#9728 Fixes issues with test_web_urldispatcher when it encounters OS AF_UNIX too long
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9734 [PR #9726/c3a9c3e backport][3.10] Make ``enable_cleanup_closed`` a NOOP for Python 3.12.7+ and 3.13.1+
  CHANGES/9726.misc.rst
  aiohttp/connector.py
  docs/client_reference.rst
  tests/conftest.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#9733 🧪💅 Load `pytest-cov` early
  setup.cfg
Labels: infra, bot:chronographer:skip, backport-3.10, backport-3.11

#9735 [PR #9726/c3a9c3e backport][3.11] Make ``enable_cleanup_closed`` a NOOP for Python 3.12.7+ and 3.13.1+
  CHANGES/9726.misc.rst
  aiohttp/connector.py
  docs/client_reference.rst
  tests/conftest.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#9736 Fix typo in enable_cleanup_closed warning message
  CHANGES/9736.misc.rst
  aiohttp/connector.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9741 Fix race getting an unused port when there are multiple test runners
  tests/conftest.py
  tests/test_run_app.py
  tests/test_test_utils.py
  tests/test_web_server.py
  tests/test_worker.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9743 [PR #9741/acc2912 backport][3.10] Fix race getting an unused port when there are multiple test runners
  tests/conftest.py
  tests/test_run_app.py
  tests/test_test_utils.py
  tests/test_web_server.py
  tests/test_worker.py
Labels: bot:chronographer:skip

#9744 [PR #9741/acc2912 backport][3.11] Fix race getting an unused port when there are multiple test runners
  tests/conftest.py
  tests/test_run_app.py
  tests/test_test_utils.py
  tests/test_web_server.py
  tests/test_worker.py
Labels: bot:chronographer:skip

#5431 Re-introduce `pytest-xdist` in supported envs
  .github/workflows/ci-cd.yml
  requirements/constraints.txt
  requirements/test.in
  requirements/test.txt
  setup.cfg
  tests/test_client_request.py
  tests/test_connector.py
  tests/test_imports.py
  tests/test_proxy_functional.py
Labels: infra, bot:chronographer:skip, backport-3.10, backport-3.11

#9745 Speed up preparing headers by avoiding populating cookies when there are no cookies
  aiohttp/web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9748 [PR #9745/0d10447 backport][3.10] Speed up preparing headers by avoiding populating cookies when there are no cookies
  aiohttp/web_response.py
Labels: bot:chronographer:skip

#9750 Make import test run in dev mode only
  tests/test_imports.py
Labels: bot:chronographer:skip, backport:skip

#9747 [PR #5431/751c3c4 backport][3.11] Re-introduce `pytest-xdist` in supported envs
  .github/workflows/ci-cd.yml
  requirements/constraints.txt
  requirements/test.in
  requirements/test.txt
  setup.cfg
  tests/test_client_request.py
  tests/test_connector.py
  tests/test_imports.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#9746 [PR #5431/751c3c4 backport][3.10] Re-introduce `pytest-xdist` in supported envs
  .github/workflows/ci-cd.yml
  requirements/constraints.txt
  requirements/test.in
  requirements/test.txt
  setup.cfg
  tests/test_client_request.py
  tests/test_connector.py
  tests/test_imports.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#9749 [PR #9745/0d10447 backport][3.11] Speed up preparing headers by avoiding populating cookies when there are no cookies
  aiohttp/web_response.py
  tests/test_imports.py
Labels: bot:chronographer:skip

#9751 Add codspeed badge
  README.rst
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9756 Avoid tracking connections per host when there is no limit per host
  CHANGES/9756.misc.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.11

#9758 [PR #9756/44d809f backport][3.11] Avoid tracking connections per host when there is no limit per host
  CHANGES/9756.misc.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#9757 Avoid creating body writer task when there is no body
  CHANGES/9757.misc.rst
  aiohttp/base_protocol.py
  aiohttp/client_reqrep.py
  aiohttp/http_writer.py
  tests/test_base_protocol.py
  tests/test_benchmarks_client_request.py
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.11

#9760 Release 3.11.0b5
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9761 Add benchmarks for a simple POST request
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9762 Refactor payload registry to avoid linear searches for common types
  aiohttp/payload.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9765 Avoid duplicate len calls in StreamReader.feed_data
  aiohttp/streams.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9770 Release 3.11.0rc0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9772 Combine duplicate logic in `Response.write_eof`
  aiohttp/web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9771 Small cleanups to enabling compression in web_response
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9777 Collapse if block nesting in web.Response
  aiohttp/web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9776 [PR #9771/e80d5854 backport][3.10] Small cleanups to enabling compression in web_response
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:skip

#9781 Ensure Cython WebSocket parser can handle frames of 2**23 in size
  CHANGES/9781.feature.rst
  aiohttp/_websocket/reader_c.pxd
Labels: bot:chronographer:provided, backport-3.11

#9784 Add benchmark for reading WebSocket payloads larger than 2**16
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9780 Replace get_event_loop with get_running_loop in the compressor
  aiohttp/compression_utils.py
  tests/test_compression_utils.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9787 Fix flakey test_import_time with Python 3.13
  tests/test_imports.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9786 [PR #9784/2f6ff6d backport][3.11] Add benchmark for reading WebSocket payloads larger than 2**16
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip

#9785 [PR #9784/2f6ff6d backport][3.10] Add benchmark for reading WebSocket payloads larger than 2**16
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip

#9793 [PR #9685/5241897 backport][3.11] Fix WebSocket reader flow control calculations
  CHANGES/9685.breaking.rst
  aiohttp/__init__.py
  aiohttp/_websocket/reader.py
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/client_ws.py
  aiohttp/streams.py
  aiohttp/web_ws.py
  tests/test_benchmarks_http_websocket.py
  tests/test_client_ws_functional.py
  tests/test_flowcontrol_streams.py
  tests/test_http_parser.py
  tests/test_web_websocket.py
  tests/test_websocket_data_queue.py
  tests/test_websocket_parser.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided

#9794 Release 3.11.0rc1
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9796 Avoid calling the drain helper in `WebSocketWriter` if the protocol is not paused
  CHANGES/9796.misc.rst
  aiohttp/_websocket/writer.py
Labels: bot:chronographer:provided, backport-3.11

#9799 Add compressed WebSocketWriter benchmark
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9795 Switch WebSocketWriter to use `removesuffix` to drop compression trailer
  aiohttp/_websocket/writer.py
Labels: bot:chronographer:skip, backport-3.11

#9803 Small performance improvement to drain
  aiohttp/base_protocol.py
  aiohttp/http_writer.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9804 Fix stale docstring in compressed `WebSocketWriter` benchmark
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport:skip

#9800 Fix incorrect typing on `WebSocketResponse._handshake`
  aiohttp/web_ws.py
Labels: bot:chronographer:skip, backport-3.11

#9809 Add `__slots__` to `UrlMappingMatchInfo`
  aiohttp/abc.py
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.11

#9811 [PR #9800/f0e26eb backport][3.11] Fix incorrect typing on `WebSocketResponse._handshake`
  aiohttp/web_ws.py
Labels: bot:chronographer:skip

#9812 Add `__slots__` to `PayloadRegistry`
  aiohttp/payload.py
Labels: bot:chronographer:skip, backport-3.11

#9808 Add missing test coverage for extracting JSON from `WSMessageBinary`
  tests/test_client_ws_functional.py
Labels: bot:chronographer:skip, backport:skip

#9816 Avoid duplicate bool cast in should_close
  aiohttp/client_proto.py
Labels: bot:chronographer:skip, backport-3.11

#9815 Remove unneeded assignment in BaseConnector._release
  aiohttp/connector.py
Labels: bot:chronographer:skip, backport-3.11

#9817 Simplify keep_alive logic in `ClientRequest`
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.11

#9818 Remove connector close workaround for older Python versions
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:skip, backport:skip

#9824 Add benchmark for GET requests with reading a payload
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9822 Improve performance of the access logger when its disabled
  CHANGES/9822.feature.rst
  aiohttp/abc.py
  aiohttp/web_log.py
  aiohttp/web_protocol.py
  docs/abc.rst
  docs/logging.rst
  tests/test_web_log.py
Labels: bot:chronographer:provided, backport-3.11

#9827 Adjust client GET read benchmarks to include chunked and content-length
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9835 Adjust client payload benchmarks to better represent real world cases
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9840 Add benchmark for sending compressed payload with chunks
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9843 Add coverage to ensure `ClientRequest.write_bytes` is called for a chunked empty body
  tests/test_client_request.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9844 Fix compressed get request benchmark payload length
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11

#9839 Implement zero copy writes in `StreamWriter`
  CHANGES/9839.misc.rst
  aiohttp/http_writer.py
  tests/test_client_request.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.11

#9848 Release 3.10.11rc0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9847 [PR #9839/a9a0d84 backport][3.11] Implement zero copy writes in `StreamWriter`
  CHANGES/9839.misc.rst
  aiohttp/http_writer.py
  tests/test_client_request.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided

#9849 Release 3.11.0rc2
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#9852 Fix system routes polluting the middleware cache
  CHANGES/9852.bugfix.rst
  aiohttp/web_app.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided, backport-3.10, backport-3.11

#9855 [PR #9852/249855a backport][3.10] Fix system routes polluting the middleware cache
  CHANGES/9852.bugfix.rst
  aiohttp/web_app.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided

#9853 [PR #9851/541d86d backport][3.10] Fix incorrect parsing of chunk extensions with the pure Python parser
  CHANGES/9851.bugfix.rst
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#9856 [PR #9852/249855a backport][3.11] Fix system routes polluting the middleware cache
  CHANGES/9852.bugfix.rst
  aiohttp/web_app.py
  tests/test_web_middleware.py
Labels: bot:chronographer:provided

#9859 Do not merge
  CHANGES.rst
  CHANGES/9436.bugfix.rst
  CHANGES/9470.misc.rst
  CHANGES/9485.misc.rst
  CHANGES/9506.bugfix.rst
  CHANGES/9600.breaking.rst
  CHANGES/9603.misc.rst
  CHANGES/9670.bugfix.rst
  CHANGES/9671.bugfix.rst
  CHANGES/9726.misc.rst
  CHANGES/9736.misc.rst
  CHANGES/9851.bugfix.rst
  CHANGES/9852.bugfix.rst
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided, backport:skip

#9865 Update dependabot config for 3.12
  .github/dependabot.yml
Labels: bot:chronographer:skip

#9873 Make creating `RequestInfo` backwards compatible with 3.10
  CHANGES/9873.bugfix.rst
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided, backport-3.11

#9877 DO NOT MERGE
  CHANGES.rst
  CHANGES/9873.bugfix.rst
Labels: backport:skip

#9879 Increment version to 3.11.2.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip, backport:skip

#9883 Fix improperly closed WebSocket connections generating a backtrace
  CHANGES/9883.bugfix.rst
  aiohttp/_websocket/reader_py.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided, backport-3.11

#9884 [PR #9883/a118114 backport][3.11] Fix improperly closed WebSocket connections generating a backtrace
  CHANGES/9883.bugfix.rst
  aiohttp/_websocket/reader_py.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided

#9887 [PR #9883/a118114 backport][3.12] Fix improperly closed WebSocket connections generating a backtrace
  CHANGES/9883.bugfix.rst
  aiohttp/_websocket/reader_py.py
  tests/test_client_ws_functional.py
Labels: bot:chronographer:provided

#9885 Add benchmarks for web middleware
  tests/test_benchmarks_web_middleware.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9893 DO NOT MERGE
  CHANGES.rst
  CHANGES/9883.bugfix.rst
Labels: backport:skip

#9900 Add benchmark for a route that supports multiple methods
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9899 Refactor Resource.resolve to avoid linear search of methods
  CHANGES/9899.misc.rst
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#9908 [PR #9899/2249f2d backport][3.11] Refactor Resource.resolve to avoid linear search of methods
  CHANGES/9899.misc.rst
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:provided

#9909 [PR #9899/2249f2d backport][3.12] Refactor Resource.resolve to avoid linear search of methods
  CHANGES/9899.misc.rst
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:provided

#9911 Only construct the `allowed_methods` `set` once for a `StaticResource`
  aiohttp/web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#9910 Add benchmarks for the URL dispatcher
  tests/test_benchmarks_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9918 Remove __author__ from __dir__
  CHANGES/9918.bugfix.rst
  aiohttp/__init__.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#9921 Freeze app for url dispatcher benchmarks
  tests/test_benchmarks_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9925 Add benchmarks for github url resolving emulation
  tests/github-urls.json
  tests/test_benchmarks_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9929 Add couple benchmarks for dynamic routes
  tests/test_benchmarks_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9935 Add benchmark for routing sub_applications
  tests/test_benchmarks_web_urldispatcher.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9940 Add benchmarks for creating web responses
  tests/test_benchmarks_web_response.py
Labels: bot:chronographer:skip, backport-3.10, backport-3.11, backport-3.12

#9944 Use SPDX license expression
  setup.cfg
Labels: bot:chronographer:skip, backport-3.11, backport-3.12
