Repository aio-libs/aiohttp, pull requests merged in 2024-01, with the labels that each got.

#7954 Implement happy eyeballs (RFC 8305)
  CHANGES/7954.feature
  aiohttp/connector.py
  docs/client_reference.rst
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/conftest.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.10

#8005 Implement happy eyeballs (RFC 8305) (#7954)
  CHANGES/7954.feature
  aiohttp/connector.py
  docs/client_reference.rst
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  requirements/test.txt
  setup.cfg
  tests/conftest.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#8012 Fix FileResponse doing blocking I/O in the event loop
  CHANGES/8012.bugfix
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8014 Fix double compress when compression enabled and compressed file exists
  CHANGES/8014.bugfix
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8017 Fix double compress when compression enabled and compressed file exists (#8014)
  CHANGES/8014.bugfix
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#8018 Fix double compress when compression enabled and compressed file exists (#8014)
  CHANGES/8014.bugfix
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#8022 Add runtime type check for `ClientSession` `timeout` param
  CHANGES/8021.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  tests/test_client_session.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8027 Backport to 3.9: Add runtime type check for `ClientSession` `timeout` param (#8022)
  CHANGES/8021.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  tests/test_client_session.py
Labels: bot:chronographer:provided

#8026 Backport to 3.10: Add runtime type check for `ClientSession` `timeout` param (#8022)
  CHANGES/8021.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  tests/test_client_session.py
Labels: bot:chronographer:provided

#8033 Small cleanups to WebSocketWriter
  aiohttp/http_websocket.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#7363 Retry connection
  CHANGES/7297.feature
  aiohttp/client.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10

#8010 Fix the Towncrier philosophy link
  CHANGES/8010.doc
  CHANGES/README.rst
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8038 Retry connection (#7363)
  CHANGES/7297.feature
  aiohttp/client.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#7698 Tightening the runtime type check for ssl
  CHANGES/7698.feature
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  tests/test_client_exceptions.py
  tests/test_client_request.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8042 Tightening the runtime type check for ssl (#7698)
  CHANGES/7698.feature
  aiohttp/client.py
  aiohttp/client_exceptions.py
  aiohttp/client_reqrep.py
  aiohttp/connector.py
  tests/test_client_exceptions.py
  tests/test_client_fingerprint.py
  tests/test_client_request.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.9

#7944 Implement filter_cookies() with domain-matching and path-matching
  CHANGES/7583.feature
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.10

#7995 Fix examples of `fallback_charset_resolver` function in client_advanced documentation
  CHANGES/7995.doc
  docs/client_advanced.rst
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8046 Implement filter_cookies() with domain-matching and path-matching
  CHANGES/7583.feature
  CONTRIBUTORS.txt
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#7784 Fix duplicate cookie expiration calls in the CookieJar implementation
  CHANGES/7784.bugfix
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.10

#8047 Fix duplicate cookie expiration calls in the CookieJar implementation (#7784)
  CHANGES/7784.bugfix
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#8048 Remove deprecated support for ssl=None
  CHANGES/8048.removal
  aiohttp/client.py
  aiohttp/client_reqrep.py
Labels: bot:chronographer:provided, backport:skip

#8049 Set cause for ClientPayloadError
  aiohttp/client_proto.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8066 💅📝 Restructure the changelog for clarity
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-cd.yml
  .pre-commit-config.yaml
  CHANGES/.TEMPLATE.rst
  CHANGES/.gitignore
  CHANGES/2835.breaking.rst
  CHANGES/2977.breaking.rst
  CHANGES/3463.breaking.rst
  CHANGES/3538.breaking.rst
  CHANGES/3539.breaking.rst
  CHANGES/3542.breaking.rst
  CHANGES/3547.breaking.rst
  CHANGES/3548.breaking.rst
  CHANGES/3580.breaking.rst
  CHANGES/3890.breaking.rst
  CHANGES/3901.breaking.rst
  CHANGES/3929.breaking.rst
  CHANGES/3931.breaking.rst
  CHANGES/3932.breaking.rst
  CHANGES/3933.breaking.rst
  CHANGES/3934.breaking.rst
  CHANGES/3935.breaking.rst
  CHANGES/3939.breaking.rst
  CHANGES/3940.breaking.rst
  CHANGES/3942.breaking.rst
  CHANGES/3945.breaking.rst
  CHANGES/3948.breaking.rst
  CHANGES/5278.breaking.rst
  CHANGES/5284.breaking.rst
  CHANGES/7107.breaking.rst
  CHANGES/8048.breaking.rst
  CHANGES/8066.contrib.rst
  CHANGES/8066.packaging.rst
  CHANGES/README.rst
  docs/spelling_wordlist.txt
  pyproject.toml
  tools/check_changes.py
  tools/cleanup_changes.py
Labels: enhancement, documentation, infra, bot:chronographer:provided, backport-3.9, backport-3.10

#8067 [PR #8066/cba34699 backport][3.10] 💅📝 Restructure the changelog for clarity
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-cd.yml
  .pre-commit-config.yaml
  CHANGES/.TEMPLATE.rst
  CHANGES/.gitignore
  CHANGES/8066.contrib.rst
  CHANGES/8066.packaging.rst
  CHANGES/README.rst
  docs/spelling_wordlist.txt
  pyproject.toml
  tools/check_changes.py
  tools/cleanup_changes.py
Labels: enhancement, documentation, infra, bot:chronographer:provided

#8068 [PR #8066/cba34699 backport][3.9] 💅📝 Restructure the changelog for clarity
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-cd.yml
  .pre-commit-config.yaml
  CHANGES/.TEMPLATE.rst
  CHANGES/.gitignore
  CHANGES/8066.contrib.rst
  CHANGES/8066.packaging.rst
  CHANGES/README.rst
  docs/spelling_wordlist.txt
  pyproject.toml
  tools/check_changes.py
  tools/cleanup_changes.py
Labels: enhancement, documentation, infra, bot:chronographer:provided

#8069 📝 Only show changelog draft for non-releases
  CHANGES/8067.doc.rst
  docs/changes.rst
  docs/conf.py
Labels: documentation, infra, bot:chronographer:provided, backport-3.9, backport-3.10

#7916 Add more information to contributing page
  CHANGES/7916.doc
  CHANGES/README.rst
  docs/_static/img/contributing-cov-comment.svg
  docs/_static/img/contributing-cov-header.svg
  docs/_static/img/contributing-cov-miss.svg
  docs/_static/img/contributing-cov-partial.svg
  docs/contributing.rst
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8074 Improve validation in HTTP parser
  CHANGES/8074.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8077 Improve validation in HTTP parser (#8074)
  CHANGES/8074.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8078 Improve validation in HTTP parser (#8074)
  CHANGES/8074.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/http_parser.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8075 [PR #3955/8960063e backport][3.10] Replace all tmpdir fixtures with tmp_path (#3551)
  CHANGES/3551.misc
  CONTRIBUTORS.txt
  tests/test_client_request.py
  tests/test_proxy_functional.py
  tests/test_web_functional.py
  tests/test_web_sendfile_functional.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#8076 [PR #3955/8960063e backport][3.9] Replace all tmpdir fixtures with tmp_path (#3551)
  CHANGES/3551.misc
  CONTRIBUTORS.txt
  tests/test_client_request.py
  tests/test_proxy_functional.py
  tests/test_web_functional.py
  tests/test_web_sendfile_functional.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#8079 Validate static paths
  CHANGES/8079.bugfix.rst
  aiohttp/web_urldispatcher.py
  docs/web_advanced.rst
  docs/web_reference.rst
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8083 [PR #3957/79fe2045 backport][3.10] Improve test suite handling of paths, temp files
  CHANGES/3957.misc
  tests/test_client_request.py
  tests/test_cookiejar.py
  tests/test_helpers.py
  tests/test_multipart.py
  tests/test_proxy_functional.py
  tests/test_urldispatch.py
  tests/test_web_sendfile_functional.py
  tests/test_web_urldispatcher.py
  tools/check_changes.py
Labels: bot:chronographer:provided

#8084 [PR #3957/79fe2045 backport][3.9] Improve test suite handling of paths, temp files
  CHANGES/3957.misc
  tests/test_client_request.py
  tests/test_cookiejar.py
  tests/test_helpers.py
  tests/test_multipart.py
  tests/test_proxy_functional.py
  tests/test_urldispatch.py
  tests/test_web_sendfile_functional.py
  tests/test_web_urldispatcher.py
  tools/check_changes.py
Labels: bot:chronographer:provided

#8098 Fix backwards compatibility with ssl
  CHANGES/8097.bugfix.rst
  CHANGES/8098.bugfix.rst
  aiohttp/client_reqrep.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.9

#8099 📝💅 Ask PR submitters about the complexities
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGES/8099.contrib.rst
Labels: meta, bot:chronographer:provided

#8107 Partially revert "Add more information to contributing page (#7916)"
  CHANGES/README.rst
  docs/contributing.rst
Labels: documentation, meta, bot:chronographer:skip, backport-3.9, backport-3.10

#8110 Re-add a PR preparation intro from PR #7916
  docs/contributing.rst
Labels: documentation, meta, bot:chronographer:skip, backport-3.9, backport-3.10

#8113 📝 Make the changelog examples elaborate
  CHANGES/README.rst
Labels: documentation, bot:chronographer:skip, backport-3.9, backport-3.10
