Repository aio-libs/aiohttp, pull requests merged in 2024-07, with the labels that each got.

#8463 Add full request typing signatures for session HTTP methods
  CHANGES/8463.misc.rst
  aiohttp/client.py
Labels: bot:chronographer:provided, backport-3.10

#8473 add: asgi library to third party list
  docs/third_party.rst
Labels: bot:chronographer:skip, backport-3.10

#8490 [3.10] Document `web.FileResponse`
  CHANGES/3958.doc
  docs/web_reference.rst
Labels: bot:chronographer:provided

#8491 Simplify static path checks and resolve strictly
  CHANGES/8491.misc.rst
  aiohttp/web_urldispatcher.py
  tests/test_urldispatch.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided, backport-3.10

#8492 [3.10] Simplify static path checks and resolve strictly (#8491)
  CHANGES/8491.misc.rst
  aiohttp/web_urldispatcher.py
  tests/test_urldispatch.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#8485 Fix response headers for compressed file requests
  CHANGES/4462.bugfix.rst
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided, backport-3.10

#8497 [3.10] Fix response headers for compressed file requests (#8485)
  CHANGES/4462.bugfix.rst
  aiohttp/web_fileresponse.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#8499 Fix broken link
  aiohttp/connector.py
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.10

#8501 Use identity checks for all WSMsgType type compares
  CHANGES/8501.misc.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
Labels: bot:chronographer:provided, backport-3.10

#8498 Avoid creating a future on every websocket receive
  CHANGES/8498.misc.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.10

#8503 [PR #8498/7bf6ee1 backport][3.10] Avoid creating a future on every websocket receive
  CHANGES/8498.misc.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided

#8445 Fixes read_timeout on WS connection not respecting ws_connect's timeouts
  CHANGES/8444.bugfix
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_proto.py
  tests/test_client_ws.py
Labels: bot:chronographer:provided, backport-3.10

#8482 Fix incorrect rejection of ws:// and wss:// urls
  CHANGES/8481.bugfix.rst
  aiohttp/client.py
  tests/conftest.py
  tests/test_client_session.py
  tests/test_client_ws.py
Labels: bot:chronographer:provided, backport-3.10

#8504 Add a Request.wait_for_disconnection() method (#4200)
  CHANGES/2492.feature
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  docs/web_reference.rst
Labels: bot:chronographer:provided

#8511 [PR #8482/62173be backport][3.10] Fix incorrect rejection of ws:// and wss:// urls
  CHANGES/8481.bugfix.rst
  aiohttp/client.py
  tests/conftest.py
  tests/test_client_session.py
  tests/test_client_ws.py
Labels: bot:chronographer:provided

#8512 [PR #5278/0f0c3759 backport][3.10] Drop Python 3.6 support
  aiohttp/abc.py
  aiohttp/client.py
  aiohttp/connector.py
  aiohttp/helpers.py
  aiohttp/pytest_plugin.py
  aiohttp/resolver.py
  aiohttp/web_server.py
  tests/test_client_functional.py
  tests/test_connector.py
  tests/test_helpers.py
Labels: bot:chronographer:skip

#8515 Update sphinxcontrib-towncrier entry point @ conf
  docs/conf.py
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8513 Small cleanup to wss/ws fix
  CHANGES/6722.feature
  CHANGES/8481.bugfix.rst
  CHANGES/8481.feature.rst
  CHANGES/8482.feature.rst
  tests/test_client_session.py
Labels: bot:chronographer:skip, backport-3.10

#8507 Remove blocking IO for static resources and refactor exception handling
  CHANGES/8507.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10

#8510 Avoid scheduling the writer if it can finish synchronously
  CHANGES/8510.misc.rst
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided, backport-3.10

#8521 [PR #8507/c9d09f11 backport][3.10] Remove blocking IO for static resources and refactor exception handling
  CHANGES/8507.bugfix.rst
  aiohttp/web_urldispatcher.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided

#8522 Restore AsyncResolver to be the default resolver
  CHANGES/8522.misc.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.10

#8520 [PR #8510/38fc33b1 backport][3.10] Avoid scheduling the writer if it can finish synchronously
  CHANGES/8510.misc.rst
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided

#8341 [PR #8338/dc457842 backport][3.10] Add some coverage
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_client_ws_functional.py
  tests/test_test_utils.py
  tests/test_web_app.py
  tests/test_web_runner.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:skip

#8495 Shutdown logic: Only wait on handlers
  aiohttp/web.py
  aiohttp/web_protocol.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  tests/test_run_app.py
  tests/test_web_request_handler.py
Labels: bot:chronographer:skip, backport-3.10

#8532 [3.10] Downgrade upload/download artifact to v3 to fix CI
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#8533 Release 3.10.0b1
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#8535 Small speed up to cookiejar filter_cookies
  CHANGES/8535.misc.rst
  aiohttp/cookiejar.py
Labels: bot:chronographer:provided, backport-3.10

#8538 Handle 403 and 404 issues in FileResponse class
  CHANGES/8182.bugfix.rst
  aiohttp/web_fileresponse.py
  aiohttp/web_urldispatcher.py
  tests/test_web_sendfile.py
  tests/test_web_sendfile_functional.py
  tests/test_web_urldispatcher.py
Labels: bot:chronographer:provided, backport-3.10

#8541 Cleanup for #8495
  CHANGES/8495.breaking.rst
  docs/web_advanced.rst
  tests/test_run_app.py
Labels: bot:chronographer:provided, backport-3.10

#8550 Release 3.10.0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#8552 Release 3.10.0 (attempt 2)
  CHANGES.rst
Labels: bot:chronographer:provided, bot:chronographer:skip

#8553 DO NOT MERGE
  CHANGES.rst
  CHANGES/2492.feature
  CHANGES/2507.feature.rst
  CHANGES/3315.feature.rst
  CHANGES/4462.bugfix.rst
  CHANGES/6722.feature
  CHANGES/7297.feature
  CHANGES/7583.feature
  CHANGES/7784.bugfix
  CHANGES/7801.feature
  CHANGES/7829.misc
  CHANGES/7954.feature
  CHANGES/8062.feature.rst
  CHANGES/8088.contrib.rst
  CHANGES/8182.bugfix.rst
  CHANGES/8270.bugfix.rst
  CHANGES/8346.misc.rst
  CHANGES/8364.misc.rst
  CHANGES/8403.doc.rst
  CHANGES/8444.bugfix
  CHANGES/8463.misc.rst
  CHANGES/8481.feature.rst
  CHANGES/8482.feature.rst
  CHANGES/8491.misc.rst
  CHANGES/8495.breaking.rst
  CHANGES/8498.misc.rst
  CHANGES/8501.misc.rst
  CHANGES/8507.bugfix.rst
  CHANGES/8510.misc.rst
  CHANGES/8522.misc.rst
  CHANGES/8535.misc.rst
  tests/test_connector.py
  tests/test_pytest_plugin.py
Labels: backport:skip

#8554 Bump version number to 3.10.1.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip
