Repository aio-libs/aiohttp, pull requests merged in 2024-02, with the labels that each got.

#8127 Treat Accept-Encoding header as case-insensitive for gzip file check
  CHANGES/8104.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/web_fileresponse.py
  aiohttp/web_response.py
  tests/test_web_sendfile.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8132 Cleanup comment
  aiohttp/web_response.py
Labels: bot:chronographer:skip

#8088 re-enable 4 tests, accidentally dropped
  CHANGES/8088.contrib.rst
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.10

#8141 Backport 3.10: Add tests, accidentally dropped before (#8088)
  CHANGES/8088.contrib.rst
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8143 Add CODECOV_TOKEN
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.9, backport-3.10

#8139 rename a shadowed test and re-enable F811 to catch future cases
  CHANGES/8139.contrib.rst
  setup.cfg
  tests/test_urldispatch.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8148 rename a shadowed test and re-enable F811 to catch future cases (#8139)
  CHANGES/8139.contrib.rst
  setup.cfg
  tests/test_resolver.py
  tests/test_urldispatch.py
Labels: bot:chronographer:provided

#8140 Use NPM clean install and upgrade node to v18
  .github/workflows/ci-cd.yml
  CHANGES/8116.contrib.rst
  Makefile
  vendor/README.rst
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8147 rename a shadowed test and re-enable F811 to catch future cases (#8139)
  CHANGES/8139.contrib.rst
  setup.cfg
  tests/test_resolver.py
  tests/test_urldispatch.py
Labels: bot:chronographer:provided

#6722 Implement granular URL error hierarchy in the HTTP client
  CHANGES/2507.feature.rst
  CHANGES/3315.feature.rst
  CHANGES/6722.feature
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  docs/client_reference.rst
  tests/test_client_exceptions.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.10

#8136 Create hello.txt.gz dynamically and improve related assertions
  .gitattributes
  CHANGES/8136.contrib.rst
  tests/hello.txt.gz
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10

#8156 [3.10] Create hello.txt.gz dynamically and improve related assertions (#8136)
  .gitattributes
  CHANGES/8136.contrib.rst
  tests/hello.txt.gz
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#8157 [3.9] Create hello.txt.gz dynamically and improve related assertions (#8136)
  .gitattributes
  CHANGES/8136.contrib.rst
  tests/hello.txt.gz
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#8158 [PR #6722/fb465e15 backport][3.10] Implement granular URL error hierarchy in the HTTP client
  CHANGES/2507.feature.rst
  CHANGES/3315.feature.rst
  CHANGES/6722.feature
  CONTRIBUTORS.txt
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_exceptions.py
  docs/client_reference.rst
  tests/test_client_exceptions.py
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#8063 Add server capability to check for Brotli compressed static files
  CHANGES/8062.feature.rst
  aiohttp/web_fileresponse.py
  aiohttp/web_response.py
  docs/web_reference.rst
  tests/test_web_sendfile.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided, backport-3.10

#8160 [3.10] Add server capability to check for Brotli compressed static files
  CHANGES/8062.feature.rst
  aiohttp/web_fileresponse.py
  aiohttp/web_response.py
  docs/web_reference.rst
  tests/test_web_sendfile.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#8089 💅 Propagate error causes via asyncio protocols
  CHANGES/8089.bugfix.rst
  aiohttp/_http_parser.pyx
  aiohttp/base_protocol.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/streams.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_ws.py
  tests/test_base_protocol.py
  tests/test_client_request.py
  tests/test_http_parser.py
Labels: enhancement, client, server, bot:chronographer:provided, backport-3.9, backport-3.10

#8162 [PR #8089/dc38630b backport][3.9] 💅 Propagate error causes via asyncio protocols
  CHANGES/8089.bugfix.rst
  aiohttp/_http_parser.pyx
  aiohttp/base_protocol.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/streams.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_ws.py
  tests/test_base_protocol.py
  tests/test_client_request.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8161 [PR #8089/dc38630b backport][3.10] 💅 Propagate error causes via asyncio protocols
  CHANGES/8089.bugfix.rst
  aiohttp/_http_parser.pyx
  aiohttp/base_protocol.py
  aiohttp/client_proto.py
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/http_websocket.py
  aiohttp/streams.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
  aiohttp/web_ws.py
  tests/test_base_protocol.py
  tests/test_client_request.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided

#8163 Avoid creating a task to do DNS resolution if there is no throttle
  CHANGES/8163.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.9, backport-3.10
