Repository aio-libs/aiohttp, pull requests merged in 2025-06, with the labels that each got.

#11109 [PR #11106/cfb9931 backport][3.13] Fix cookies with duplicate names being lost when updating cookie jar
  CHANGES/11105.bugfix.rst
  CHANGES/11106.bugfix.rst
  CHANGES/4486.bugfix.rst
  aiohttp/abc.py
  aiohttp/client.py
  aiohttp/client_reqrep.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_response.py
  tests/test_client_session.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided

#11107 Avoid creating closed futures that will never be awaited
  CHANGES/11107.misc.rst
  aiohttp/client_proto.py
  aiohttp/connector.py
  tests/test_client_proto.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11110 [PR #11107/21d640d backport][3.12] Avoid creating closed futures that will never be awaited
  CHANGES/11107.misc.rst
  aiohttp/client_proto.py
  aiohttp/connector.py
  tests/test_client_proto.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#11114 Downgrade connector close error to debug
  CHANGES/11114.misc.rst
  aiohttp/connector.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11112 Fix cookie parsing issues
  CHANGES/11112.bugfix.rst
  CHANGES/2683.bugfix.rst
  CHANGES/5397.bugfix.rst
  CHANGES/7993.bugfix.rst
  aiohttp/_cookie_helpers.py
  aiohttp/abc.py
  aiohttp/client_reqrep.py
  aiohttp/cookiejar.py
  aiohttp/web_request.py
  tests/test_client_functional.py
  tests/test_client_request.py
  tests/test_cookie_helpers.py
  tests/test_cookiejar.py
  tests/test_web_request.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11118 PR #11112/8edec63 backport][3.13] Fix cookie parsing issues
  CHANGES/11112.bugfix.rst
  CHANGES/2683.bugfix.rst
  CHANGES/5397.bugfix.rst
  CHANGES/7993.bugfix.rst
  aiohttp/_cookie_helpers.py
  aiohttp/abc.py
  aiohttp/client_reqrep.py
  aiohttp/cookiejar.py
  aiohttp/web_request.py
  docs/spelling_wordlist.txt
  pyproject.toml
  tests/test_client_functional.py
  tests/test_client_request.py
  tests/test_cookie_helpers.py
  tests/test_cookiejar.py
  tests/test_web_request.py
Labels: bot:chronographer:provided

#11117 PR #11112/8edec63 backport][3.12] Fix cookie parsing issues
  CHANGES/11112.bugfix.rst
  CHANGES/2683.bugfix.rst
  CHANGES/5397.bugfix.rst
  CHANGES/7993.bugfix.rst
  aiohttp/_cookie_helpers.py
  aiohttp/abc.py
  aiohttp/client_reqrep.py
  aiohttp/cookiejar.py
  aiohttp/web_request.py
  docs/spelling_wordlist.txt
  pyproject.toml
  tests/test_client_functional.py
  tests/test_client_request.py
  tests/test_cookie_helpers.py
  tests/test_cookiejar.py
  tests/test_web_request.py
Labels: bot:chronographer:provided

#11121 DO NOT MERGE
  CHANGES.rst
  CHANGES/11105.bugfix.rst
  CHANGES/11106.bugfix.rst
  CHANGES/11107.misc.rst
  CHANGES/11112.bugfix.rst
  CHANGES/11114.misc.rst
  CHANGES/2683.bugfix.rst
  CHANGES/4486.bugfix.rst
  CHANGES/5397.bugfix.rst
  CHANGES/7993.bugfix.rst
Labels: bot:chronographer:skip, backport:skip

#11129 Add preemptive authentication support to DigestAuthMiddleware
  CHANGES/11128.feature.rst
  CHANGES/11129.feature.rst
  aiohttp/client_middleware_digest_auth.py
  docs/client_reference.rst
  tests/test_client_middleware_digest_auth.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11140 DO NOT MERGE
  CHANGES.rst
  CHANGES/11128.feature.rst
  CHANGES/11129.feature.rst
Labels: backport:skip

#11146 Increment version to 3.12.10.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#11150 fix: leak of aiodns.DNSResolver when ClientSession is closed
  CHANGES/11150.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  aiohttp/resolver.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11151 [PR #11150/996ad00 backport][3.13] fix: leak of aiodns.DNSResolver when ClientSession is closed
  CHANGES/11150.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  aiohttp/resolver.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#11152 [PR #11150/996ad00 backport][3.12] fix: leak of aiodns.DNSResolver when ClientSession is closed
  CHANGES/11150.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  aiohttp/resolver.py
  tests/test_connector.py
Labels: bot:chronographer:provided

#11154 DO NOT MERGE
  CHANGES.rst
  CHANGES/11150.bugfix.rst
Labels: backport:skip

#11156 [PR #11148/86a9a38 backport][3.13] Abort ssl connections on close when ssl_shutdown_timeout is 0
  CHANGES/11148.deprecation.rst
  CHANGES/11148.feature.rst
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_proto.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#11155 [PR #11148/86a9a38 backport][3.12] Abort ssl connections on close when ssl_shutdown_timeout is 0
  CHANGES/11148.deprecation.rst
  CHANGES/11148.feature.rst
  aiohttp/client.py
  aiohttp/client_proto.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_proto.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#11158 DO NOT MERGE
  CHANGES.rst
  CHANGES/11148.deprecation.rst
  CHANGES/11148.feature.rst
Labels: backport:skip

#11159 Increment version to 3.12.12.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#11178 Fix cookie header parser ignoring reserved names
  CHANGES/11178.bugfix.rst
  aiohttp/_cookie_helpers.py
  aiohttp/abc.py
  aiohttp/client_reqrep.py
  aiohttp/web_request.py
  tests/test_cookie_helpers.py
  tests/test_web_request.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11185 DO NOT MERGE
  CHANGES.rst
  CHANGES/11173.bugfix.rst
  CHANGES/11178.bugfix.rst
Labels: backport:skip

#11193 Pin CI Python version to 3.13.3
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.12, backport-3.13

#11215 DO NOT MERGE
  CHANGES.rst
Labels: bot:chronographer:skip, backport:skip

#11161 Add support for ZSTD compression
  .pre-commit-config.yaml
  CHANGES/11161.feature.rst
  CONTRIBUTORS.txt
  aiohttp/_http_parser.pyx
  aiohttp/client_reqrep.py
  aiohttp/compression_utils.py
  aiohttp/http_parser.py
  docs/client_quickstart.rst
  docs/spelling_wordlist.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/runtime-deps.in
  requirements/runtime-deps.txt
  setup.cfg
  tests/test_client_request.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.13

#11247 Cherry-pick some pytest-asyncio fixes
  tests/conftest.py
  tests/isolated/check_for_client_response_leak.py
  tests/isolated/check_for_request_leak.py
  tests/test_cookiejar.py
  tests/test_proxy.py
Labels: bot:chronographer:skip, backport-3.13

#11243 Ignore empty parts when parsing Content-Disposition header
  CHANGES/11243.bugfix
  aiohttp/multipart.py
  tests/test_client_response.py
Labels: bot:chronographer:provided, backport-3.13
