Repository aio-libs/aiohttp, pull requests merged in 2025-07, with the labels that each got.

#11279 Bump aiosignal from 1.3.2 to 1.4.0 (#11267)
  aiohttp/tracing.py
  aiohttp/web_app.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#11280 Bump the minimum supported version of aiosignal to 1.4
  CHANGES/11280.misc.rst
  requirements/runtime-deps.in
  setup.cfg
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11269 Add trailer parsing logic
  CHANGES/11269.feature.rst
  aiohttp/http_parser.py
  aiohttp/multipart.py
  tests/test_http_parser.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11288 Remove PARSE_MAYBE_TRAILERS
  aiohttp/http_parser.py
Labels: bot:chronographer:skip, backport:skip

#11289 Fix ClientSession.close() hanging with HTTPS proxy connections
  CHANGES/11273.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11299 DO NOT MERGE
  CHANGES.rst
  CHANGES/11234.doc.rst
  CHANGES/11269.feature.rst
  CHANGES/11270.bugfix.rst
  CHANGES/11273.bugfix.rst
  CHANGES/11280.misc.rst
  tests/test_client_functional.py
  tests/test_http_parser.py
Labels: backport:skip

#11271 Update a regex in test_aiohttp_request_coroutine for Python 3.14
  CHANGES/11271.contrib.rst
  CONTRIBUTORS.txt
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11336 Fix backwards compatibility for .write_bytes()
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.12

#11335 small speedup by avoiding redundant `IOBasePayload.size` calls
  aiohttp/multipart.py
  aiohttp/web_response.py
Labels: bot:chronographer:skip, backport-3.12, backport-3.13

#11347 Update web_advanced docs
  CHANGES/11347.doc.rst
  docs/web_advanced.rst
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11358 Increment version to 3.12.16.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip
