Repository aio-libs/aiohttp, pull requests merged in 2025-05, with the labels that each got.

#10823 Remove constraint that prevented aiodns from being installed on Windows
  CHANGES/10823.packaging.rst
  requirements/runtime-deps.in
  setup.cfg
Labels: bot:chronographer:provided, backport-3.12

#10797 Build armv7l manylinux wheels
  .github/workflows/ci-cd.yml
  CHANGES/10797.feature.rst
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10798 Fix error messages to be idiomatically correct English
  .github/PULL_REQUEST_TEMPLATE.md
  aiohttp/_http_parser.pyx
  aiohttp/http_exceptions.py
  aiohttp/http_parser.py
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.12

#10848 Add benchmark requests without session and alternating clients
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10868 Fix unclosed resources in proxy xfail tests
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10869 [PR #10868/323bdcf backport][3.11] Fix unclosed resources in proxy xfail tests
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#10870 [PR #10868/323bdcf backport][3.12] Fix unclosed resources in proxy xfail tests
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#10851 remove use of deprecated policy API from tests
  CHANGES/10851.bugfix.rst
  CHANGES/10851.contrib.rst
  aiohttp/pytest_plugin.py
  tests/conftest.py
  tests/test_connector.py
  tests/test_loop.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:provided, backport-3.12

#10871 [PR #10851/e5d1240 backport][3.12] remove use of deprecated policy API from tests
  CHANGES/10851.bugfix.rst
  CHANGES/10851.contrib.rst
  aiohttp/pytest_plugin.py
  tests/conftest.py
  tests/test_connector.py
  tests/test_loop.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:provided

#10877 [3.12] Update to Cython 3.1.1
  CHANGES/10877.packaging.rst
  aiohttp/_websocket/reader_py.py
  requirements/constraints.txt
  requirements/cython.in
  requirements/cython.txt
Labels: bot:chronographer:provided, backport-3.11

#10878 [PR #10877/6ea542e backport][3.11] Update to Cython 3.1.1
  CHANGES/10877.packaging.rst
  aiohttp/_websocket/reader_py.py
  requirements/constraints.txt
  requirements/cython.in
  requirements/cython.txt
Labels: bot:chronographer:provided

#9732 Add Client Middleware Support
  CHANGES/9732.feature.rst
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_middlewares.py
  aiohttp/client_reqrep.py
  docs/client_advanced.rst
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_middleware.py
Labels: bot:chronographer:provided, backport-3.12

#10879 [PR #9732/1e911ea backport][3.12] Add Client Middleware Support
  CHANGES/9732.feature.rst
  aiohttp/__init__.py
  aiohttp/client.py
  aiohttp/client_middlewares.py
  aiohttp/client_reqrep.py
  docs/client_advanced.rst
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_middleware.py
Labels: bot:chronographer:provided

#10881 Remove License from setup.cfg
  CHANGES/10662.packaging.rst
  CONTRIBUTORS.txt
  setup.cfg
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10880 Add invalid content type test docs
  docs/client_reference.rst
  tests/test_web_response.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10884 Fix flakey middleware connection reuse test
  tests/test_client_middleware.py
Labels: bot:chronographer:skip, backport-3.12

#10888 Fix some unclosed socket warnings when tests fail
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport:skip

#10895 [PR #10891/802152a backport][3.11] Fix flakey signal handling tests
  tests/test_web_runner.py
Labels: bot:chronographer:skip

#10896 [PR #10891/802152a backport][3.12] Fix flakey signal handling tests
  tests/test_web_runner.py
Labels: bot:chronographer:skip

#10898 Cleanup tests to ensure connector cleanup and resource management
  tests/test_connector.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10899 [PR #10898/a4be2cb backport][3.11] Cleanup tests to ensure connector cleanup and resource management
  tests/test_connector.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#10900 [PR #10898/a4be2cb backport][3.12] Cleanup tests to ensure connector cleanup and resource management
  tests/test_connector.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip

#10902 Middleware cleanups
  CHANGES/10902.feature.rst
  aiohttp/client.py
  aiohttp/client_middlewares.py
  docs/client_advanced.rst
  docs/client_reference.rst
  tests/test_client_middleware.py
Labels: bot:chronographer:provided, backport-3.12

#10897 Fix DNS resolver object churn for multiple sessions
  CHANGES/10847.feature.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.12

#10906 [PR #10897/4624fed backport][3.12] Fix DNS resolver object churn for multiple sessions
  CHANGES/10847.feature.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided

#10907 Fix flakey test_uvloop_secure_https_proxy test
  tests/test_proxy_functional.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10910 Remove mocked coro
  CHANGES/9212.packaging.rst
  CONTRIBUTORS.txt
  aiohttp/test_utils.py
  docs/testing.rst
  tests/test_client_request.py
  tests/test_client_response.py
  tests/test_client_session.py
  tests/test_client_ws.py
  tests/test_connector.py
  tests/test_http_writer.py
  tests/test_proxy.py
  tests/test_run_app.py
  tests/test_tracing.py
  tests/test_web_app.py
  tests/test_web_functional.py
  tests/test_web_request_handler.py
  tests/test_web_response.py
  tests/test_web_sendfile.py
  tests/test_web_websocket.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10911 Release 3.12.0b0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10913 Mark the removal of make_mocked_coro as a breaking change
  CHANGES/9212.breaking.rst
Labels: bot:chronographer:provided, backport:skip

#10912 [PR #10910/36a2567 backport][3.11] Remove mocked coro from tests
  CONTRIBUTORS.txt
  tests/test_client_request.py
  tests/test_client_response.py
  tests/test_client_session.py
  tests/test_client_ws.py
  tests/test_connector.py
  tests/test_http_writer.py
  tests/test_multipart.py
  tests/test_proxy.py
  tests/test_run_app.py
  tests/test_tracing.py
  tests/test_web_app.py
  tests/test_web_functional.py
  tests/test_web_request_handler.py
  tests/test_web_response.py
  tests/test_web_sendfile.py
  tests/test_web_websocket.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided, bot:chronographer:skip

#10914 [PR #10910/36a2567 backport][3.12] Remove mocked coro from tests
  CONTRIBUTORS.txt
  tests/test_client_request.py
  tests/test_client_response.py
  tests/test_client_session.py
  tests/test_client_ws.py
  tests/test_connector.py
  tests/test_http_writer.py
  tests/test_multipart.py
  tests/test_proxy.py
  tests/test_run_app.py
  tests/test_tracing.py
  tests/test_web_app.py
  tests/test_web_functional.py
  tests/test_web_request_handler.py
  tests/test_web_response.py
  tests/test_web_sendfile.py
  tests/test_web_websocket.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:skip

#10923 Fix weakref garbage collection race condition in DNS resolver manager
  CHANGES/10923.feature.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.12

#10760 Support using system llhttp library
  CHANGES/10759.packaging.rst
  aiohttp/_cparser.pxd
  docs/glossary.rst
  docs/spelling_wordlist.txt
  pyproject.toml
  requirements/test.in
  setup.py
Labels: bot:chronographer:provided, backport-3.12

#10922 Add Winloop to test suite if User is using Windows
  CHANGES/10922.contrib.rst
  CONTRIBUTORS.txt
  docs/spelling_wordlist.txt
  requirements/base.in
  requirements/base.txt
  tests/conftest.py
Labels: bot:chronographer:provided, backport-3.12

#10915 Fix connection reuse for file-like data payloads
  CHANGES/10325.bugfix.rst
  CHANGES/10915.bugfix.rst
  aiohttp/client_reqrep.py
  aiohttp/payload.py
  tests/conftest.py
  tests/test_client_functional.py
  tests/test_client_request.py
  tests/test_payload.py
Labels: bot:chronographer:provided, backport-3.12

#10931 [PR #10915/545783b backport][3.12] Fix connection reuse for file-like data payloads
  CHANGES/10325.bugfix.rst
  CHANGES/10915.bugfix.rst
  aiohttp/client_reqrep.py
  aiohttp/payload.py
  tests/conftest.py
  tests/test_client_functional.py
  tests/test_client_request.py
  tests/test_payload.py
Labels: bot:chronographer:provided

#10933 Fix flakey client functional keep alive tests
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10936 [PR #10933/597161d backport][3.11] Fix flakey client functional keep alive tests
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#10937 [PR #10933/597161d backport][3.12] Fix flakey client functional keep alive tests
  tests/test_client_functional.py
Labels: bot:chronographer:skip

#10938 Fix flakey test_content_length_limit_with_multiple_reads test
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport-3.12

#10941 Use anext in AsyncIterablePayload on Python 3.10+
  CHANGES/10941.bugfix.rst
  aiohttp/payload.py
Labels: bot:chronographer:provided, backport-3.12

#10943 Small improvements to payload cleanup fixture
  CHANGES/10943.bugfix.rst
  tests/conftest.py
Labels: bot:chronographer:provided, backport-3.12

#10946 Ensure AsyncResolver.close() can be called multiple times
  CHANGES/10946.feature.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.12

#10948 Release 3.12.0b2
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10949 Improve connection reuse test coverage
  tests/test_client_functional.py
  tests/test_web_functional.py
Labels: bot:chronographer:skip, backport-3.12

#10950 [PR #10949/06e3b36 backport][3.12] Improve connection reuse test coverage
  tests/test_client_functional.py
  tests/test_web_functional.py
Labels: bot:chronographer:skip

#10951 [3.12] Fix AsyncResolver not using the loop argument
  CHANGES/10951.bugfix.rst
  aiohttp/resolver.py
  tests/test_resolver.py
Labels: bot:chronographer:provided, backport-3.11

#10952 Remove manual release call in middleware
  CHANGES/10952.feature.rst
  aiohttp/client_middleware_digest_auth.py
  tests/test_client_middleware.py
Labels: bot:chronographer:provided, backport-3.12

#10955 Release 3.12.0b3
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10956 Fix some missing connector closes in tests
  tests/test_client_middleware.py
  tests/test_proxy_functional.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10958 [PR #10956/5dcb36a4 backport][3.11] Fix some missing connector closes in tests
  tests/test_proxy_functional.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:skip

#10959 Change ClientSession middlewares default to be an empty tuple
  CHANGES/10959.feature.rst
  aiohttp/client.py
  docs/client_reference.rst
Labels: bot:chronographer:provided, backport-3.12

#10962 add example of setting network interface in custom socket creation
  CHANGES/10962.feature.rst
  docs/client_advanced.rst
Labels: documentation, bot:chronographer:provided, backport-3.12

#10961 fix example in socket_factory docs
  CHANGES/10961.feature.rst
  docs/client_advanced.rst
Labels: documentation, bot:chronographer:provided, backport-3.12

#10974 Fix double compression issue when enable_compression() is called on pre-encoded responses
  CHANGES/10968.bugfix.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.12

#10977 Fix flakey test_aiohttp_request_ctx_manager_close_sess_on_error test
  tests/test_client_functional.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10970 Add warning about consuming the payload in middleware
  CHANGES/2914.doc.rst
  docs/web_advanced.rst
Labels: documentation, bot:chronographer:provided, backport-3.11, backport-3.12

#10971 Fix `WebSocketResponse.prepared` not correctly reflect the WebSocket's prepared state
  CHANGES/6009.bugfix.rst
  aiohttp/web_ws.py
  tests/test_web_websocket.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10981 Fix flakey test_client_middleware_retry_reuses_connection test
  tests/test_client_middleware.py
Labels: bot:chronographer:skip, backport-3.12

#10984 [PR #10970/bb5fc59 backport][3.12] Add warning about consuming the payload in middleware
  CHANGES/2914.doc.rst
  docs/web_advanced.rst
Labels: bot:chronographer:provided

#10991 Optimize small HTTP requests/responses by coalescing headers and body into a single packet
  CHANGES/10991.feature.rst
  aiohttp/abc.py
  aiohttp/client_reqrep.py
  aiohttp/http_writer.py
  aiohttp/web_response.py
  docs/spelling_wordlist.txt
  tests/test_client_functional.py
  tests/test_http_writer.py
  tests/test_web_response.py
  tests/test_web_sendfile.py
  tests/test_web_server.py
Labels: bot:chronographer:provided, backport-3.12

#10992 [PR #10991/452458a backport][3.12] Optimize small HTTP requests/responses by coalescing headers and body into a single packet
  CHANGES/10991.feature.rst
  aiohttp/abc.py
  aiohttp/client_reqrep.py
  aiohttp/http_writer.py
  aiohttp/web_response.py
  docs/spelling_wordlist.txt
  tests/test_client_functional.py
  tests/test_http_writer.py
  tests/test_web_response.py
  tests/test_web_sendfile.py
  tests/test_web_server.py
Labels: bot:chronographer:provided

#10993 Release 3.12.0rc1
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10978 Cookbook changes
  .mypy.ini
  docs/client_advanced.rst
  docs/client_middleware_cookbook.rst
  docs/client_reference.rst
  docs/code/client_middleware_cookbook.py
  docs/conf.py
  docs/spelling_wordlist.txt
  setup.cfg
Labels: bot:chronographer:skip, backport-3.12

#10995 [PR #10978/df30c55 backport][3.12] Cookbook changes
  .mypy.ini
  docs/client_advanced.rst
  docs/client_middleware_cookbook.rst
  docs/client_reference.rst
  docs/code/client_middleware_cookbook.py
  docs/conf.py
  docs/spelling_wordlist.txt
  setup.cfg
Labels: bot:chronographer:skip

#10997 DO NOT MERGE
  CHANGES.rst
  CHANGES/10074.feature.rst
  CHANGES/10119.bugfix.rst
  CHANGES/10120.feature.rst
  CHANGES/10146.misc.rst
  CHANGES/10325.bugfix.rst
  CHANGES/10433.feature.rst
  CHANGES/10474.feature.rst
  CHANGES/10520.feature.rst
  CHANGES/10662.packaging.rst
  CHANGES/10725.feature.rst
  CHANGES/10759.packaging.rst
  CHANGES/10761.contrib.rst
  CHANGES/10797.feature.rst
  CHANGES/10823.packaging.rst
  CHANGES/10847.feature.rst
  CHANGES/10851.bugfix.rst
  CHANGES/10851.contrib.rst
  CHANGES/10902.feature.rst
  CHANGES/10915.bugfix.rst
  CHANGES/10922.contrib.rst
  CHANGES/10923.feature.rst
  CHANGES/10941.bugfix.rst
  CHANGES/10943.bugfix.rst
  CHANGES/10945.feature.rst
  CHANGES/10946.feature.rst
  CHANGES/10952.feature.rst
  CHANGES/10959.feature.rst
  CHANGES/10961.feature.rst
  CHANGES/10962.feature.rst
  CHANGES/10968.bugfix.rst
  CHANGES/10968.feature.rst
  CHANGES/10972.feature.rst
  CHANGES/10988.bugfix.rst
  CHANGES/10991.feature.rst
  CHANGES/2213.feature.rst
  CHANGES/2914.doc.rst
  CHANGES/6009.bugfix.rst
  CHANGES/9705.contrib.rst
  CHANGES/9732.feature.rst
  CHANGES/9798.feature.rst
  CHANGES/9870.misc.rst
Labels: backport:skip

#10998 Increment version to 3.12.0.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#11013 Readjust baseline for ClientRequest benchmarks
  tests/test_benchmarks_client_request.py
Labels: bot:chronographer:skip, backport-3.12, backport-3.13

#11019 [PR #11017/1c01726 backport][3.13] Support Reusable Request Bodies and Improve Payload Handling
  CHANGES/11017.feature.rst
  CHANGES/5530.feature.rst
  CHANGES/5577.feature.rst
  CHANGES/9201.feature.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_middleware_digest_auth.py
  aiohttp/client_reqrep.py
  aiohttp/formdata.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/web_response.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_middleware.py
  tests/test_client_middleware_digest_auth.py
  tests/test_client_request.py
  tests/test_client_session.py
  tests/test_formdata.py
  tests/test_multipart.py
  tests/test_payload.py
Labels: bot:chronographer:provided

#11018 [PR #11017/1c01726 backport][3.12] Support Reusable Request Bodies and Improve Payload Handling
  CHANGES/11017.feature.rst
  CHANGES/5530.feature.rst
  CHANGES/5577.feature.rst
  CHANGES/9201.feature.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  aiohttp/client_middleware_digest_auth.py
  aiohttp/client_reqrep.py
  aiohttp/formdata.py
  aiohttp/multipart.py
  aiohttp/payload.py
  aiohttp/web_response.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_middleware.py
  tests/test_client_middleware_digest_auth.py
  tests/test_client_request.py
  tests/test_client_session.py
  tests/test_formdata.py
  tests/test_multipart.py
  tests/test_payload.py
Labels: bot:chronographer:provided

#11011 Correct type of ClientRequest.body
  aiohttp/client_middleware_digest_auth.py
  aiohttp/client_reqrep.py
  docs/client_reference.rst
  tests/test_client_middleware_digest_auth.py
  tests/test_client_request.py
Labels: bot:chronographer:skip, backport-3.12, backport-3.13

#11020 Cleanup some type ignores in the client request tests
  tests/test_client_request.py
Labels: bot:chronographer:skip, backport-3.12, backport-3.13

#11025 Move ClientResponse to top of file
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip, backport-3.12, backport-3.13

#11027 [PR #11020/852297c backport][3.13] Cleanup some type ignores in the client request tests
  tests/test_client_request.py
Labels: bot:chronographer:skip

#11028 Move ClientResponse to top of file
  aiohttp/client_reqrep.py
Labels: bot:chronographer:skip

#11030 Release 3.12.1rc0
  CHANGES.rst
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#11032 DO NOT MERGE
  CHANGES.rst
  CHANGES/11017.feature.rst
  CHANGES/5530.feature.rst
  CHANGES/5577.feature.rst
  CHANGES/9201.feature.rst
Labels: backport:skip

#11034 Increment version to 3.12.1.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#11035 Fix Content-Length header regression for requests with None body
  CHANGES/11035.bugfix.rst
  aiohttp/client_reqrep.py
  tests/test_client_request.py
Labels: bot:chronographer:provided, regression, backport-3.12, backport-3.13

#11041 DO NOT MERGE
  CHANGES.rst
  CHANGES/11035.bugfix.rst
Labels: backport:skip

#11042 Increment version to 3.12.3.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#11055 Fix failing lint jobs due to caching
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12, backport-3.13

#11054 Fix CookieJar memory leak in filter_cookies()
  CHANGES/11052.bugfix.rst
  CHANGES/11054.bugfix.rst
  aiohttp/cookiejar.py
  tests/test_cookiejar.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12, backport-3.13

#11064 Remove update of libenchant from linter workflow
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12, backport-3.13

#11070 [PR #11064/876102c backport][3.11] Remove update of libenchant from linter workflow
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#11072 [PR #11064/876102c backport][3.13] Remove update of libenchant from linter workflow
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#11074 [PR #3733/6b0bc4ef backport][3.13] Fix connector not waiting for connections to close
  CHANGES/11074.bugfix.rst
  CHANGES/1925.bugfix.rst
  aiohttp/client_proto.py
  aiohttp/connector.py
  tests/test_client_request.py
  tests/test_client_session.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#11075 DO NOT MERGE
  CHANGES.rst
  CHANGES/11052.bugfix.rst
  CHANGES/11054.bugfix.rst
Labels: bot:chronographer:skip, backport:skip

#11080 Increment version to 3.12.5.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip, backport:skip

#11079 DO NOT MERGE
  CHANGES.rst
Labels: bot:chronographer:skip, backport:skip

#11081 Revert cache key change for linter
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12, backport-3.13

#11085 Replace expensive isinstance checks with faster alternatives
  CHANGES/11085.misc.rst
  aiohttp/client_reqrep.py
  aiohttp/cookiejar.py
  aiohttp/multipart.py
  aiohttp/payload.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11088 Remove ABC names for isinstance checks
  CHANGES/11088.misc.rst
  aiohttp/client_reqrep.py
  aiohttp/cookiejar.py
  aiohttp/multipart.py
  aiohttp/payload.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11094 Fix SSL shutdown timeout for streaming connections
  CHANGES/11091.feature.rst
  CHANGES/11094.feature.rst
  aiohttp/client.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.12, backport-3.13

#11095 [PR #11094/50bb06b backport][3.12] Fix SSL shutdown timeout for streaming connections
  CHANGES/11091.feature.rst
  CHANGES/11094.feature.rst
  aiohttp/client.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#11096 [PR #11094/50bb06b backport][3.13] Fix SSL shutdown timeout for streaming connections
  CHANGES/11091.feature.rst
  CHANGES/11094.feature.rst
  aiohttp/client.py
  aiohttp/connector.py
  docs/client_reference.rst
  tests/test_client_functional.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided

#11099 Increment version to 3.12.7.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip
