Repository aio-libs/aiohttp, pull requests merged in 2025-04, with the labels that each got.

#10656 Revert: Close the socket if there's a failure in start_connection() #10464
  CHANGES/10464.bugfix.rst
  CHANGES/10617.bugfix.rst
  CHANGES/10656.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10663 Replace deprecated `asyncio.iscoroutinefunction` with its counterpart…
  CHANGES/10634.bugfix.rst
  aiohttp/pytest_plugin.py
  aiohttp/web_urldispatcher.py
  aiohttp/worker.py
Labels: bot:chronographer:provided

#10672 Fix headers being mutated if passed to web.Response as a CIMultiDict
  CHANGES/10672.bugfix.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10675 Remove useless nonlocal statements in tests
  tests/test_client_ws_functional.py
  tests/test_helpers.py
  tests/test_web_server.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10673 [PR #10672/35c979b backport][3.11] Fix headers being mutated if passed to web.Response as a CIMultiDict
  CHANGES/10672.bugfix.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#10677 [PR #10675/048ef4c backport][3.11] Remove useless nonlocal statements in tests
  tests/test_client_ws_functional.py
  tests/test_helpers.py
  tests/test_web_server.py
Labels: bot:chronographer:skip

#10674 [PR #10672/35c979b backport][3.12] Fix headers being mutated if passed to web.Response as a CIMultiDict
  CHANGES/10672.bugfix.rst
  aiohttp/web_response.py
  tests/test_web_response.py
Labels: bot:chronographer:provided

#10678 [PR #10675/048ef4c backport][3.12] Remove useless nonlocal statements in tests
  tests/test_client_ws_functional.py
  tests/test_helpers.py
  tests/test_web_server.py
Labels: bot:chronographer:skip

#10680 Do not merge
  CHANGES.rst
  CHANGES/10634.bugfix.rst
  CHANGES/10672.bugfix.rst
Labels: bot:chronographer:skip, backport:skip

#10698 Bump yarl to 1.19.0
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: dependencies, bot:chronographer:skip, backport-3.12

#10706 docs/client_reference.rst, attribute name from trace_config to trace_…
  docs/client_reference.rst
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10723 [PR #10700/ceeca6a backport][3.12] Add support for switching the zlib implementation
  CHANGES/9798.feature.rst
  aiohttp/__init__.py
  aiohttp/_websocket/reader_py.py
  aiohttp/_websocket/writer.py
  aiohttp/abc.py
  aiohttp/compression_utils.py
  aiohttp/http_writer.py
  aiohttp/multipart.py
  aiohttp/web_response.py
  docs/client_reference.rst
  docs/conf.py
  docs/spelling_wordlist.txt
  docs/web_reference.rst
  requirements/dev.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/test.in
  requirements/test.txt
  tests/conftest.py
  tests/test_client_functional.py
  tests/test_client_request.py
  tests/test_client_ws_functional.py
  tests/test_compression_utils.py
  tests/test_http_writer.py
  tests/test_multipart.py
  tests/test_web_functional.py
  tests/test_web_response.py
  tests/test_web_sendfile_functional.py
  tests/test_websocket_parser.py
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided

#10721 Update zlib benchmarks for multiple zlib backends
  tests/test_benchmarks_client.py
  tests/test_benchmarks_http_websocket.py
Labels: bot:chronographer:skip, backport-3.12

#10730 Add benchmarks for large binary WebSocket message roundtrips
  tests/test_benchmarks_client_ws.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10714 Only fetch SSLContext and peername once per connection
  CHANGES/10714.misc.rst
  aiohttp/test_utils.py
  aiohttp/web_protocol.py
  aiohttp/web_request.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10736 [3.11] Bump multidict to 6.4.3
  requirements/base.txt
  requirements/constraints.txt
  requirements/cython.txt
  requirements/dev.txt
  requirements/multidict.txt
  requirements/runtime-deps.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#10713 Avoid fetching loop time on each request unless logging is enabled
  CHANGES/10713.misc.rst
  aiohttp/web_protocol.py
  tests/test_web_log.py
  tests/test_web_runner.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10738 [PR #10713/8d74e26 backport][3.11] Avoid fetching loop time on each request unless logging is enabled
  CHANGES/10713.misc.rst
  aiohttp/web_protocol.py
  tests/test_web_app.py
  tests/test_web_log.py
Labels: bot:chronographer:provided

#10739 [PR #10713/8d74e26 backport][3.12] Avoid fetching loop time on each request unless logging is enabled
  CHANGES/10713.misc.rst
  aiohttp/web_protocol.py
  tests/test_web_app.py
  tests/test_web_log.py
Labels: bot:chronographer:provided

#10740 Refactor WebSocket reader to avoid creating lists
  CHANGES/10740.misc.rst
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10746 [PR #10740/0d21d8d backport][3.11] Refactor WebSocket reader to avoid creating lists
  CHANGES/10740.misc.rst
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#10745 [PR #10740/0d21d8d backport][3.12] Refactor WebSocket reader to avoid creating lists
  CHANGES/10740.misc.rst
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#10744 Refactor WebSocket reader to avoid frequent realloc when frames are fragmented
  CHANGES/10744.misc.rst
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10749 Add compressed binary WebSocket roundtrip benchmark
  tests/test_benchmarks_client_ws.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10752 Add a test to the WebSocket parser for sending one byte at a time
  tests/test_websocket_parser.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10757 Do not merge
  CHANGES.rst
  CHANGES/10713.misc.rst
  CHANGES/10714.misc.rst
  CHANGES/10740.misc.rst
  CHANGES/10744.misc.rst
Labels: bot:chronographer:skip, backport:skip

#10758 Increment version to 3.11.18.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10761 Speed up tests
  CHANGES/9705.contrib.rst
  CONTRIBUTORS.txt
  setup.cfg
  tests/conftest.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10764 Fix WebSocket reader with fragmented masked messages
  CHANGES/10764.bugfix.rst
  aiohttp/_websocket/reader_py.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10726 Disable TLS in TLS warning for uvloop
  CHANGES/7686.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/conftest.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10765 [PR #10764/e0cc020 backport][3.11] Fix WebSocket reader with fragmented masked messages
  CHANGES/10764.bugfix.rst
  aiohttp/_websocket/reader_py.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#10766 [PR #10764/e0cc020 backport][3.12] Fix WebSocket reader with fragmented masked messages
  CHANGES/10764.bugfix.rst
  aiohttp/_websocket/reader_py.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:provided

#10768 [PR #10726/feff48d backport][3.12] Disable TLS in TLS warning for uvloop
  CHANGES/7686.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/conftest.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:provided

#10767 [PR #10726/feff48d backport][3.11] Disable TLS in TLS warning for uvloop
  CHANGES/7686.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/conftest.py
  tests/test_proxy_functional.py
Labels: bot:chronographer:provided

#10770 Increase benchmark timeout to 9 minutes in the CI
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10769 [PR #10761/d884799 backport][3.12] Speed up tests
  CHANGES/9705.contrib.rst
  CONTRIBUTORS.txt
  setup.cfg
  tests/conftest.py
  tests/test_web_sendfile_functional.py
Labels: bot:chronographer:provided

#10775 Increment version to 3.11.19.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10776 Do not merge
  CHANGES.rst
  CHANGES/10764.bugfix.rst
  CHANGES/7686.bugfix.rst
Labels: bot:chronographer:skip, backport:skip
