Repository aio-libs/aiohttp, pull requests merged in 2025-03, with the labels that each got.

#10553 Add benchmark for JSON post requests that check the content type
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10552 Cache parsing of the content-type
  CHANGES/10552.misc.rst
  aiohttp/helpers.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10529 Fixed bug that lead to infinite wait for dns futures
  CHANGES/10529.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10534 Replace tcp_sockopts with socket_factory
  CHANGES/10474.feature.rst
  CHANGES/10520.feature.rst
  aiohttp/__init__.py
  aiohttp/connector.py
  docs/client_advanced.rst
  docs/client_reference.rst
  docs/conf.py
  requirements/runtime-deps.in
  setup.cfg
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.12

#10551 Re-raise OSError as ClientConnectionError when failing to explicitly close connector socket
  CHANGES/10551.bugfix.rst
  aiohttp/connector.py
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10556 Break cyclic references at connection close when there was a traceback
  CHANGES/10556.bugfix.rst
  aiohttp/_websocket/reader_py.py
  aiohttp/client_proto.py
  tests/isolated/check_for_client_response_leak.py
  tests/test_leaks.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10569 Break cyclic references when there is an exception handling a request
  CHANGES/10569.bugfix.rst
  aiohttp/web_protocol.py
  tests/isolated/check_for_request_leak.py
  tests/test_leaks.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10564 Log offending websocket client address when no protocols overlap
  CHANGES/10564.feature.rst
  aiohttp/web_ws.py
  tests/test_websocket_handshake.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10574 [PR #10534/3b9bb1cd backport][3.12] Replace tcp_sockopts with socket_factory
  CHANGES/10474.feature.rst
  CHANGES/10520.feature.rst
  aiohttp/__init__.py
  aiohttp/connector.py
  docs/client_advanced.rst
  docs/client_reference.rst
  docs/conf.py
  requirements/runtime-deps.in
  setup.cfg
  tests/test_connector.py
Labels: bot:chronographer:provided

#10542 only use `AI_ADDRCONFIG` when supported by getaddrinfo
  CHANGES/10542.bugfix
  aiohttp/resolver.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10577 Parametrize leak tests
  tests/test_leaks.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10584 Increment version to 3.11.15.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10583 Do not merge
  CHANGES.rst
  CHANGES/10529.bugfix.rst
  CHANGES/10542.bugfix
  CHANGES/10551.bugfix.rst
  CHANGES/10552.misc.rst
  CHANGES/10556.bugfix.rst
  CHANGES/10564.feature.rst
  CHANGES/10569.bugfix.rst
Labels: bot:chronographer:skip, backport:skip

#10597 Skip test_autobahn if python_on_whales is missing
  tests/autobahn/test_autobahn.py
Labels: bot:chronographer:skip, backport-3.12

#10602 Replace "requests" to "aiohttp" in docs
  docs/client_quickstart.rst
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10614 [PR #10597/01b2a86a backport][3.12] Skip test_autobahn if python_on_whales is missing
  tests/autobahn/test_autobahn.py
Labels: bot:chronographer:skip

#10634 Replace deprecated `asyncio.iscoroutinefunction` with its counterpart from `inspect`
  CHANGES/10634.bugfix.rst
  aiohttp/pytest_plugin.py
  aiohttp/web_urldispatcher.py
  aiohttp/worker.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10625 Improve performance of serializing headers
  CHANGES/10625.misc.rst
  aiohttp/_http_writer.pyx
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10568 Docs fixups following implement socket factory (#10534)
  CHANGES/10474.feature.rst
  docs/client_advanced.rst
  docs/client_reference.rst
  docs/conf.py
Labels: bot:chronographer:provided, backport-3.12

#10601 Reduce WebSocket buffer slicing overhead
  CHANGES/10601.misc.rst
  aiohttp/_websocket/reader_c.pxd
  aiohttp/_websocket/reader_py.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10644 Add benchmarks for streaming API
  tests/test_benchmarks_client.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12
