Repository aio-libs/aiohttp, pull requests merged in 2025-10, with the labels that each got.

#11533 Re-generated pickled cookie for python 3.14 compatibility
  .github/workflows/ci-cd.yml
  CONTRIBUTORS.txt
  tests/test_cookiejar.py
  tests/test_helpers.py
Labels: bot:chronographer:skip, backport-3.13

#11556 [PR #11546/92dee75 backport][3.13] Refactor websocket frame compression tests in test_websocket_writer
  CHANGES/11546.contrib.rst
  tests/test_websocket_writer.py
Labels: bot:chronographer:provided

#11558 Re-generated pickled cookie for python 3.14 compatibility (#11533)
  .github/workflows/ci-cd.yml
  CONTRIBUTORS.txt
  tests/test_connector.py
  tests/test_cookiejar.py
  tests/test_web_functional.py
Labels: bot:chronographer:skip

#11559 Add Python 3.14 to metadata
  setup.cfg
Labels: bot:chronographer:skip, backport-3.13

#11572 Add Linux Foundation Health Score badge to README (#11538)
  README.rst
Labels: bot:chronographer:skip

#11573 Move some badges to the bottom of the page
  README.rst
Labels: bot:chronographer:skip, backport-3.13

#11582 Bump version with .dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip
