Repository aio-libs/aiohttp, pull requests merged in 2025-01, with the labels that each got.

#10281 Update workflow to use upload-artifact v4 and download-artifact v4
  .github/workflows/ci-cd.yml
  CHANGES/10281.contrib.rst
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10300 Use kwargs in aiohttp.client.request
  CHANGES/10300.feature.rst
  aiohttp/client.py
  docs/spelling_wordlist.txt
  tests/test_client_functional.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10304 Add aiohttp-openmetrics to list of third party aiohttp-related python…
  CHANGES/10304.doc.rst
  docs/third_party.rst
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10301 Update docs for aiohttp.request
  docs/client_reference.rst
Labels: bot:chronographer:provided, bot:chronographer:skip, backport-3.11, backport-3.12

#10332 Log the remote that generates request errors
  CHANGES/10332.feature.rst
  aiohttp/web_protocol.py
  tests/test_web_server.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10339 Add sphinx configuration for readthedocs
  .readthedocs.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10342 Increase allowed import time for Python 3.12+
  tests/test_imports.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10303 [PR #10300/3d06cc1][3.11] Use kwargs in aiohttp.client.request
  CHANGES/10300.feature.rst
  aiohttp/client.py
  docs/spelling_wordlist.txt
  tests/test_client_functional.py
Labels: bot:chronographer:provided

#10330 Start building riscv64 platform wheels in CI/CD
  .github/workflows/ci-cd.yml
  CHANGES/10330.packaging.rst
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10366 Fix sdist make
  CHANGES/10366.packaging
  MANIFEST.in
  Makefile
  tools/gen.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12
