Repository aio-libs/aiohttp, pull requests merged in 2025-02, with the labels that each got.

#10371 Added 'partitioned' parameter to set_cookie method.
  CHANGES/9870.misc.rst
  aiohttp/helpers.py
  docs/web_reference.rst
  tests/test_helpers.py
Labels: bot:chronographer:provided, backport-3.12

#10378 [PR #10371/f46ccff backport][3.12] 'partitioned' parameter for set_cookie method.
  CHANGES/9870.misc.rst
  aiohttp/web_response.py
  docs/web_reference.rst
  tests/test_web_response.py
Labels: bot:chronographer:provided

#10383 [3.11] Bump packaging to 24.2
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc-spelling.txt
  requirements/doc.txt
  requirements/lint.txt
  requirements/test.txt
Labels: bot:chronographer:skip

#10137 Restore zero copy writes on Python 3.12.9+/3.13.2+
  .github/workflows/ci-cd.yml
  CHANGES/10137.misc.rst
  aiohttp/http_writer.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10390 [PR #10137/25c7f23 backport][3.11] Restore zero copy writes on Python 3.12.9+/3.13.2+
  .github/workflows/ci-cd.yml
  CHANGES/10137.misc.rst
  aiohttp/http_writer.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided

#10391 [PR #10137/25c7f23 backport][3.12] Restore zero copy writes on Python 3.12.9+/3.13.2+
  .github/workflows/ci-cd.yml
  CHANGES/10137.misc.rst
  aiohttp/http_writer.py
  tests/test_http_writer.py
Labels: bot:chronographer:provided

#10393 Revert "Start building riscv64 platform wheels in CI/CD"
  .github/workflows/ci-cd.yml
  CHANGES/10330.packaging.rst
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10397 [3.11] Amend changes to remove reverted riscv64 wheels
  CHANGES.rst
Labels: bot:chronographer:skip

#10396 Switch to native arm runners for wheel builds
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10400 Add workaround for segfaults during wheel builds
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10402 [PR #10400/9b33be3 backport][3.12] Add workaround for segfaults during wheel builds
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#10401 [PR #10400/9b33be3 backport][3.11] Add workaround for segfaults during wheel builds
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip

#10403 Disable wheel builds on PyPy
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10404 Start build wheels on armv7l musllinux
  .github/workflows/ci-cd.yml
  CHANGES/10404.packaging.rst
  docs/spelling_wordlist.txt
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10410 Fix runs-on for wheel builds for native arm
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10413 Fix missing ppc64le musllinux wheels
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10416 Fix wheel download-artifact by setting merge-multiple
  .github/workflows/ci-cd.yml
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10419 Do not merge
  CHANGES.rst
  CHANGES/10137.misc.rst
  CHANGES/10270.bugfix.rst
  CHANGES/10281.contrib.rst
  CHANGES/10300.feature.rst
  CHANGES/10304.doc.rst
  CHANGES/10332.feature.rst
  CHANGES/10366.packaging
  CHANGES/10387.bugfix.rst
  CHANGES/10404.packaging.rst
Labels: backport:skip

#10420 [3.11] Increment version to 3.11.13.dev0
  aiohttp/__init__.py
Labels: bot:chronographer:skip

#10222 Revert incorrect typing changes
  .github/workflows/ci-cd.yml
  .mypy.ini
  aiohttp/http_parser.py
  aiohttp/web_protocol.py
Labels: bot:chronographer:skip, backport-3.12

#10423 Disable writelines for test_write_large_payload_deflate_compression_data_in_eof
  CHANGES/10423.packaging.rst
  tests/test_http_writer.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10422 Add human readable error messages for WebSocket PING/PONG timeouts
  CHANGES/10422.misc.rst
  aiohttp/client_ws.py
  aiohttp/web_ws.py
  tests/test_client_ws_functional.py
  tests/test_web_websocket_functional.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10447 Fix test when symlink encountered
  tests/test_urldispatch.py
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10455 Cleanup questionable no cover comments
  aiohttp/_websocket/helpers.py
  aiohttp/_websocket/reader.py
  aiohttp/client_reqrep.py
  aiohttp/compression_utils.py
  aiohttp/helpers.py
  aiohttp/http_parser.py
  aiohttp/pytest_plugin.py
  aiohttp/resolver.py
  aiohttp/tcp_helpers.py
  aiohttp/test_utils.py
  aiohttp/web.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_urldispatcher.py
  aiohttp/worker.py
  tests/test_client_functional.py
  tests/test_http_parser.py
  tests/test_run_app.py
  tests/test_web_app.py
  tests/test_web_urldispatcher.py
  tests/test_websocket_parser.py
Labels: bot:chronographer:skip, backport:skip

#10434 Fix inappropriate "break in finally"
  CHANGES/10434.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_server.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10476 [PR #10434/ed84464 backport][3.11] Fix inappropriate "break in finally"
  CHANGES/10434.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_server.py
Labels: bot:chronographer:provided

#10475 [PR #10434/ed84464 backport][3.12] Fix inappropriate "break in finally"
  CHANGES/10434.bugfix.rst
  aiohttp/web_protocol.py
  tests/test_web_server.py
Labels: bot:chronographer:provided

#10377 --disallow-any-decorated
  .mypy.ini
  aiohttp/abc.py
  aiohttp/client.py
  aiohttp/client_reqrep.py
  aiohttp/helpers.py
  aiohttp/pytest_plugin.py
  aiohttp/test_utils.py
  aiohttp/web_app.py
  aiohttp/web_request.py
  aiohttp/web_routedef.py
  aiohttp/web_runner.py
  aiohttp/web_server.py
  aiohttp/web_urldispatcher.py
  aiohttp/worker.py
  tests/autobahn/test_autobahn.py
  tests/test_client_connection.py
  tests/test_client_request.py
  tests/test_client_session.py
  tests/test_connector.py
  tests/test_helpers.py
  tests/test_http_parser.py
  tests/test_http_writer.py
  tests/test_proxy.py
  tests/test_run_app.py
  tests/test_tracing.py
Labels: bot:chronographer:skip, backport:skip

#10433 Detect blocking calls in coroutines using BlockBuster
  CHANGES/10433.feature.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  requirements/lint.in
  requirements/lint.txt
  requirements/test.in
  requirements/test.txt
  tests/conftest.py
  tests/test_client_functional.py
  tests/test_cookiejar.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided, backport-3.12

#10464 Close the socket if there's a failure in start_connection()
  CHANGES/10464.bugfix.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  tests/conftest.py
  tests/test_connector.py
  tests/test_proxy.py
Labels: bot:chronographer:provided, backport-3.11, backport-3.12

#10480 [PR #10433/0c4b1c7 backport][3.12] Detect blocking calls in coroutines using BlockBuster
  CHANGES/10433.feature.rst
  CONTRIBUTORS.txt
  aiohttp/client.py
  requirements/lint.in
  requirements/lint.txt
  requirements/test.in
  requirements/test.txt
  tests/conftest.py
  tests/test_client_functional.py
  tests/test_cookiejar.py
  tests/test_web_functional.py
Labels: bot:chronographer:provided

#10481 Bump blockbuster to 1.5.22
  requirements/lint.txt
  requirements/test.txt
  tests/conftest.py
Labels: bot:chronographer:skip, backport-3.12

#10482 [PR #10481/60819de backport][3.12] Bump blockbuster to 1.5.22 (#10481)
  requirements/lint.txt
  requirements/test.txt
  tests/conftest.py
Labels: bot:chronographer:skip

#10474 Expose setsockopt in TCPConnector API
  CHANGES/10474.feature.rst
  CONTRIBUTORS.txt
  aiohttp/connector.py
  docs/client_advanced.rst
  docs/client_reference.rst
  tests/test_connector.py
Labels: bot:chronographer:provided, backport-3.12

#10492 Do not merge
  CHANGES.rst
  CHANGES/10422.misc.rst
  CHANGES/10423.packaging.rst
  CHANGES/10434.bugfix.rst
  CHANGES/10464.bugfix.rst
Labels: backport:skip

#10493 Document adjustments to the release process
  docs/contributing-admins.rst
Labels: bot:chronographer:skip, backport-3.11, backport-3.12

#10454 Fixes for strict-bytes
  .mypy.ini
  aiohttp/_websocket/reader_py.py
  aiohttp/_websocket/writer.py
  aiohttp/abc.py
  aiohttp/compression_utils.py
  aiohttp/http_writer.py
  aiohttp/web_response.py
  aiohttp/web_ws.py
Labels: bot:chronographer:skip, backport:skip
